### ISSUE TITLE
Motor: Specifying side = none does not work in simulation? 

### ISSUE THREAD

**Issue by DJuego** [OpenRoberta/robertalab#1004]
**Description**
The option "side" with value "none" for motors in Robot Configuration has a unexpected behavior in the simulator.

**To Reproduce**
Suppose there is a robot with a single motor in port A. This motor has side to "none".

Now we make a program than turn on this motor. "motor port A on Speed %30 for rotation 1" for example. Why does the robot move in the simulation? 

**Expected behavior**
The robot does not move.

I thought that when an motor has that configuracion (side = none) "means" this motor is not related with the wheels. It could be the motor of a clamp. And of course it would not be reflected in the simulation (but yes in the real robot).

**Device information**
Windows 10 x64
 Desktop (Google Chrome)

DJuego

P.S: Sorry for my English.

**Comment by bjost2s** [comment]
Hi, thank you for this issue.
The current version of the simulation does not take care of any configuration at all. Instead it uses internally   the standard configuration for executing and calculating the differential drive.
