### ISSUE TITLE
EV3Lejos Lists "insert at" wrong behaviour

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#1009]
**Describe the bug**
 - The `in list x insert at #` produces wrong results when `#` points to list elements in the center

**To Reproduce**
1. Create the following program:
![image](https://user-images.githubusercontent.com/7438960/46154097-bb598080-c274-11e8-94ec-a207617be015.png)

2. Run the program on the EV3
3. The printed list on the EV3 looks like this: [1.0, 0.0, 0.0, 2.0, 3.0]

**Expected behavior**
 - The shown list is [1.0, 0.0, 2.0, 3.0, 0.0] as in the simulation.

**Comment by VinArt** [comment]
I believe that changes made during the lists revision affected this issue, since using the program above I get exactly [1.0, 0.0, 2.0, 3.0, 0.0]
