### ISSUE TITLE
Old Block Names Missing for the stored programs

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#101]
Some of the blocks have new names, the prefix **rob** is added to the old name. This will make problem for the old programs that are stored in the database. Converting these blocks from xml to block object will throw unknown block exception. As I see we can do two things,

- replacing in the database the old names of the block with the new name; or
- duplicating the blocks with the old names

Blocks that have new names:

robGlobalvariables_declare => robGlobalVariables_declare
math_change => robMath_change ???
controls_forEach => robControls_forEach
controls_for => robControls_for
lists_repeat => robLists_repeat
lists_length => robLists_length
lists_isEmpty => robLists_isEmpty
lists_indexOf => robLists_indexOf
lists_getIndex => robLists_getIndex
lists_setIndex => robLists_setIndex
lists_getSublist => robLists_getSublist
lists_create_empty => robLists_create_with (add in mutation item="0")
text_append => robText_append

**Comment by bjost2s** [comment]
We will use your first suggestion, because we have to change the robot type of the programs created for the simulation anyway

**Comment by bjost2s** [comment]
But we need a program for this ;-)
