### ISSUE TITLE
Blocks with drop-down menus do not update the inTask property on drop-down change

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1014]
**Describe the bug**
 - Blockly blocks that change from sequential to the ones that provide output do not update the .inTask when changed via drop-down select

**To Reproduce**
1. Choose the in list block
2. Select remove option from the drop-down
3. Append the block to the program
4. Select get or get and remove option from the drop-down

This leads to wrong code generation, since the block is in detached state but is still .inTask

**Expected behavior**
 - This kind of blocks should be grayed-out as usual and displaced a bit away from their original position alike to blocks those types are inappropriate anymore (e. g. number->string)

**Screenshots**

![image](https://user-images.githubusercontent.com/3738015/46339791-01776100-c634-11e8-9948-af4293e5560b.png)
![image](https://user-images.githubusercontent.com/3738015/46339828-1227d700-c634-11e8-9fb2-d0f09e2e3d34.png)

The expected outcome should be like this:
![image](https://user-images.githubusercontent.com/3738015/46339898-3daac180-c634-11e8-9ba6-8aecc13cef9d.png)

**Comment by bjost2s** [comment]
Are there others than the "in list" block with the same problem?
