### ISSUE TITLE
Revise Lists in all robots: C++

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1015]
Parent issue: #1011
 
| op\sys  | Calliope 2017  | Calliope 2016  | Arduino  | Bob3  | Bot'n'Roll  | mBot  |
|---|---|---|---|---|---|---|
| create empty list  | ✔  | ✔  |✔   | ~  |  ✔ |  ✔ |
| create list with content  | ✔  | ✔  | ✔  | ~  |  ✔ | ✔  |
| create list with repeated element  | ✔  | ✔  | ✔  | ~  |  ✔ | ✔  |
| length of  | ✔  | ✔  | ✔  |  ~ | ✔  |  ✔ |
|is empty   | ✔  | ✔  | ✔  |  ~ | ✔  | ✔  |
|  find `first` | ✔  | ✔  | ✔  |  ~ | ✔  | ✔  |
| find `last`  | ✔  | ✔  | ✔  |  ~ | ✔  |  ✔ |
|get `#`   | ✔  |  ✔ | ✔  | ~  | ✔  |  ✔ |
| get `# from end`  | ✔  | ✔  | ✔  | ~  |  ✔ |  ✔ |
|  get `first` |  ✔ |  ✔ | ✔  | ~  |  ✔ | ✔  |
| get `last`  | ✔  |  ✔ | ✔  | ~  |  ✔ |  ✔ |
| get and remove `#`   |✔   | ✔  |✔   | ~  |  ✔ | ✔ |
| get and remove `# from end`  |  ✔ |  ✔ | ✔  | ~  | ✔  | ✔  |
|  get and remove `first` |  ✔ |  ✔ |  ✔ | ~  | ✔  |  ✔ |
|  get and remove `last` | ✔  |  ✔ |  ✔ |  ~ |  ✔ | ✔  |
| remove `#`  | ✔  |  ✔ | ✔  | ~  |  ✔ | ✔  |
| remove `# from end`  |  ✔ | ✔  |  ✔ | ~  | ✔  |  ✔ |
|  remove `first` | ✔  | ✔  |  ✔ |  ~ | ✔  |  ✔ |
| remove `last`  |✔   | ✔  |  ✔ | ~  | ✔  |  ✔ |
| insert at `#`  |  ✔ | ✔  |  ✔ | ~  | ✔  | ✔  |
|insert at `# from end`   |  ✔ | ✔  | ✔  |  ~ | ✔  | ✔  |
| insert at `first`  | ✔  |  ✔ |  ✔ | ~  |  ✔ | ✔  |
| insert at `last`  | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
| get sub-list from `#` to `#`  | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
| get sub-list from `#` to `# from end`   | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
|  get sub-list from `#` to `last` | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
|  get sub-list from `# from end` to `#` |  ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
| get sub-list from `# from end` to `# from end`  | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
| get sub-list from `# from end` to `last`  | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
|get sub-list from `first` to `#`   | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
| get sub-list from `first` to `# from end`  |✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
|  get sub-list from `first` to `last` | ✔  | ✔  | ✔  |  ~ |  ✔ | ✔  |
| sum  | ✔  | ✔  |  ✔ | ~  | ✔  |  ✔ |
| min  |  ✔ | ✔  | ✔  |  ~ | ✔  | ✔  |
| max  | ✔  | ✔  |  ✔ | ~  | ✔  | ✔  |
| average  | ✔  |✔   |  ✔ | ~  |  ✔ |  ✔ |
| median  |✔   | ✔  |✔   | ~  |  ✔ | ✔  |
| standard deviation  |  ✔ | ✔  | ✔  |  ~ | ✔  |  ✔ |
| for each  |  ✔ |  ✔ | ✔  |  ~ |  ✔ |  ✔ |
| assignment  | ? | ? | ✔  |  ~ | ✔  |  ✔ |

- [x] access random elements in lists # should not be supported anymore - random access was left for backwards compatibility, but does not generate code that accesses lists randomly. Should be deprecated and removed later.
- [x] reduce bob3 lists, so they have no strings

✔ - means that the source code is generated and compiles. Run-time errors may still occur.

? - encountered confusing bugs that got automagically resolved.

~ - works in general, but due to strict memory limitations it is impossible to build bigger programs, especially when using lists of strings. Source code is generated correctly and compiles. Run-time errors may occur.

**Comment by bjost2s** [comment]
What about calliope?

**Comment by VinArt** [comment]
All the C++ based robots can support the same implementation, calliope uses stl and arduino based robots ArduinoSTL, they both have the same interface, so the implementation is needed only once

**Comment by VinArt** [comment]
C++ related functionality is implemented and put to the NEPODefs.h for RobotArdu resources as well as for the RobotMbed resources. Functions were tested with standalone C++ programs. Currently GUI blocks are revised, needed ones added and unwanted options (random) removed.

**Comment by VinArt** [comment]
Calliope lists implemented, need to check arduino further. All commits form the feature branch were squashed into two: the one with the most of implementation and the other containig blockly copy and semmicolon fix.

**Comment by bjost2s** [comment]
Please check this again, the following program is not compilable:
![image](https://user-images.githubusercontent.com/1613069/49474123-32cb0380-f814-11e8-895f-28913bb420c7.png)
/home/bjost/git/robertalab/OpenRobertaParent/RobotArdu/resources/libraries/RobertaFunctions/NEPODefs.h:95:29: error: invalid cast from type ‘String’ to type ‘const char*’
         if ((P) (*iterator) == value) {
                             ^

**Comment by bjost2s** [comment]
still another problem!
![image](https://user-images.githubusercontent.com/1613069/49537613-b8f55180-f8c9-11e8-9188-662042987202.png)

**Comment by VinArt** [comment]
this:
![image](https://user-images.githubusercontent.com/3738015/49542886-03c99600-f8d7-11e8-81b6-e811e6a6157c.png)
will, however, fail. And I am not sure I can do anything about it right now. Although I cannot find a use case when one would want to insert a value in a temporary list and immediately throw the whole thing away.
