### ISSUE TITLE
Arduino write analog/digital program destroyeed in the front-end

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#1017]
**Describe the bug**
 - A clear and concise description of what the bug is.

**To Reproduce**
1. Create a configuration with LED on D0
2. Write a program, that sets digital pin D13 on, then wait, then off
3. save this program. D13 is reset to D0, digital is reset to analog
4. The same happens if you view the generated source

**Expected behavior**
 - The user selected pin name should persist

**Screenshots**
 ![nano-led](https://user-images.githubusercontent.com/15834363/46357099-60ed6500-c664-11e8-8865-1c7e2c5b369e.png)
- my test program

**Device information**
 - arduino nano

**Additional context**
 - looks like a refresh problem with blockly

**Definition of Done**
- the user selected pin name should persist export, see source, run program
- when an exported program is reloaded, it should show the original pin names

**Comment by sebastiankmilo** [comment]
and there is another problem, the arduino can´t write in analog pin(pwm), it only can in specific digital pin.
![image](https://user-images.githubusercontent.com/16965721/46574171-300f7780-c965-11e8-877d-f31d3e7d69cb.png)

**Comment by bjost2s** [comment]
@sebastiankmilo thank you very much for pointing to this additional problem!

**Comment by rbudde** [comment]
the same problem (blockly program vanishes, i.e. is reset to the initial program) for BOB3 programs (see file /OpenRobertaServer/src/test/resources/crossCompilerTests/bob3/eye.xml for instance)

**Comment by VinArt** [comment]
The last commit was meant for issue #1071, not #1017

**Comment by VinArt** [comment]
Program for bob3 was vanishing for different reason, colours were the problem. Implemented in #1071
