### ISSUE TITLE
USBProgram: double digit COM ports are not detected

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#1020]
**Describe the bug**
 - In the USBProgram double digit COM ports are not detected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect Arduino
2. Change COM port to double digits in Device Manager
3. Start the USBProgram
4. Observe that no robot connection is detected

**Expected behaviour**
 - The Arduino is always detected.

**Device information**
 - Type: Desktop
 - OS: Windows 10

**Comment by rbudde** [comment]
works.
