### ISSUE TITLE
As a kid I would like to create programs for the Makeblock with the Open Roberta Lab

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#1021]
- [x] Makeblock  -> C++ (http://www.mblock.cc/?noredirect=en_US), functions that are not robot-specific are shared with the robots from Arduino group #1024
- [x] Makeblock  configuration -> a configuration with a fixed robot brick that has ports for motors, actors and sensors
- [x] Makeblock compiler workflow -> Arduino-based connection to the USB-program
- [x] GUI blocks, messages, tooltips and toolbox #1025
- [ ] Makeblock simulation
- [x] Makeblock unit tests

**Comment by bjost2s** [comment]
already released, simulation is not planned yet
