### ISSUE TITLE
Makeblock code generation

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#1024]
Generate code for the following actors and sensors (standard configuration) 

- [x] light sensor (in the initial implementation it was an ambientlight sensor)
- [x] IR sensor (in the initial implementation it was a light sensor)
- [x] button
- [x] ultrasonic sensor
- [x] buzzer
- [x]  RGB LED
- [x] two motors
- [ ] gyro sensor (old code generation is not working)
- [ ] accelerometer (old code generation is not working)

**Comment by bjost2s** [comment]
The current state of the implementation for mbot will be reviewed and finalized in #1074, because most of the generated code above was not working as expected. (Not generating code is expected but working generated code)
