### ISSUE TITLE
Cannot Comment on start block

### ISSUE THREAD

**Issue by lotu** [OpenRoberta/robertalab#1026]
While working with middle school students I wanted to use comments the students to use a comment to remind themselves what a program does.  They meet once per week and it is very easy to forget in that time. 

The best place for such a comment is in the start block because it cannot be deleted  during changing the program, and because it could be added before the student write and code.   The latter is a clarifying task to help students solidify their thoughts.   

For the above reasons it would be nice if you could comment on the start block.

**Comment by lotu** [comment]
Oh... I just figured out how to use the comment block under Text..........................

**Comment by bjost2s** [comment]
There is also a comment possibility on the right panel, click on the 
![image](https://user-images.githubusercontent.com/1613069/46960447-dc0c3d80-d09e-11e8-83b6-739e6b4889ac.png)
icon and use the tiny editor to document the program
