### ISSUE TITLE
Decouple the server properties from the robot properties

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#1029]
**Is your feature request related to a problem? Please describe.**
 - adding a robot should nor need to update server parts (OpenRobertaServer) or general robot parts (OpenRobertaRobot) 

**Describe the solution you'd like**
 - change the name of all robot-specific property files to <plugin-name>.properties (lower/uppe case problem)
- move all robot-specific properties to the robot-specific property files
- refactor the ServerStarter and the robot-specific factories to work with these changes

**Additional context**
 - improves the structure a lot and decouples components in a nice way (it is works :-)

**Comment by rbudde** [comment]
remark: should we integrate the ports.properties into the regular properties? Sounds good.

**Comment by rbudde** [comment]
in this context we MUST change the name of the botnroll plugin from the (very misleading) name "ardu" to "botnroll". This is good anyhow.

**Comment by rbudde** [comment]
all plugin specific properties are moved to the properties of the plugin. Thus, only the white list of plugins to be activated are kept in the global properties. This solves the issue.

**Comment by VinArt** [comment]
updateResources.dir property is still in server properties.

**Comment by rbudde** [comment]
working. Will create a ticket for an update server of its own and put that into backlog.
