### ISSUE TITLE
register "new user" should NOT enforce typing a mail address

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#103]
validation says "This field cannot be empty!" if you don't supply a mail address. This seems too restrictive to me.

**Comment by cvejoski** [comment]
The email address is needed for password recovery. If we make the email address optional then we have to add some additional questions for example to verify the user identity.

**Comment by rbudde** [comment]
or: password recovery is disabled in this case. So a user may decide:
-	Recovery: with password
-	Potential data loss: password not supplied

**Comment by bjost2s** [comment]
password recovery is only possible, if the user has supplied an email address.
We should remove the validation.
