### ISSUE TITLE
[NXT] Changing the motor direction resets the rotation sensor (only on real hardware)

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/robertalab#1033]
**Describe the bug**

When changing a motors direction, the rotation sensor starts at 0 again, making it impossible
so e.g. "go back to where you started".

In the simulator, this works completely fine, but once the program is transferred to the NXT, it resets the sensor.

**To Reproduce**
1. Create a NXT program, e.g. the following:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/27221/47313968-98867600-d640-11e8-8cb0-cd2200712e35.png">

2. Transfer the program to your NXT
3. Run in
4. The NXT will start at 0 again when going backwards.

**Expected behavior**

The NXT should decrease the rotation sensor's value when going backwards without resetting it first

**Workaround to get it to behave as expected**

<img width="518" alt="image" src="https://user-images.githubusercontent.com/27221/47314372-bdc7b400-d641-11e8-89c4-5ffa761ace96.png">

**Comment by ensonic** [comment]
As a datapoint on EV3Dev the encoders are not reset automatically. Quickly tested with this:
![img_20181026_093728](https://user-images.githubusercontent.com/1279486/47602025-f3212880-d9d8-11e8-9df6-f81075fc83c7.jpg)
![img_20181026_093710](https://user-images.githubusercontent.com/1279486/47602031-07652580-d9d9-11e8-8239-ac4f9386152f.jpg)

**Comment by bjost2s** [comment]
@VinArt there is already a block for resetting encoders:
![image](https://user-images.githubusercontent.com/1613069/47668132-f28abc80-dba7-11e8-8e30-00ecc37ffad7.png)
So no need to change something on the blocks side. This is just a bug and we should use OnFwdRegEx with the flag RESET_NONE instead of OnFwdReg. EV3 lejos encoders are not reseted automatically, too.

**Comment by bjost2s** [comment]
@Stex many thanks for this notice!

**Comment by VinArt** [comment]
@bjost2s sorry, missed those, they are under "Sensor" category - probably that's the reason

**Comment by rbudde** [comment]
works
