### ISSUE TITLE
Text function "create text with" fails on type conversion (number to string)

### ISSUE THREAD

**Issue by mkern3** [OpenRoberta/robertalab#1035]
**Describe the bug**
Text function "create text with" does not perform type conversion (number to string).
On real ev3dev stretch (NOT leJOS) the function issues an exception. (In the Simulator it works OK.)

**To Reproduce**
1. create a program with a command which includes the "create text with" text function with a numerical variable as argument
2. run the program on a real ev3dev (stretch in my case) (NOT in the simulator)
3. the ev3dev display shows an exception
Fehler in EV3
TypeError
sequence item 1: expected str
Press any key

**Expected behavior**
 - As in simulator, the type casting should be handled. Alternatively, a new typacting function may be provided.

**Screenshots**
![2018-10-29-createtextwithbug](https://user-images.githubusercontent.com/44570559/47644822-82604480-db6f-11e8-855f-02413bb3dab7.png)

**Device information**
 - Type: LEGO Mindstorms EV3
 - OS: ev3dev, Debian stretch, kernel 4.14.71-ev3dev-2.3.0-ev3

**Additional context**
 - Same error, whether the *.py program is launched from the Browser or from the brick
 - this bug may be worked around by the command "append text", which performs the type conversion correctly

**Comment by bjost2s** [comment]
@mkern3 Thank you!
We should check other python implementations like NAO and micro:bit, if they show a similar behaviour/bug
