### ISSUE TITLE
Random integer block for WeDo broken

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#1038]
**Describe the bug**
The following program is not working:
![image](https://user-images.githubusercontent.com/1613069/47994819-c44f3480-e0f3-11e8-86da-661254aa4428.png)
The program/WeDo is not responding anymore. One have to reload the lab and create another program.
Any other math block instead of the random integer block is working. 

**To Reproduce**
execute the program above on WeDo

**Expected behavior**
Program should be executed, here schow 10 random numbers in the popup.

**Device information**
 - Type Android Smartphone (tested on different)
 - Open Roberta App for Android

**Comment by rbudde** [comment]
seems to be resolved now.
