### ISSUE TITLE
Change the name of robLocalVariables_declare in the old programs

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#104]
The name of the new **robLocalvariables_declare** and **robGlobalvariables_declare** are different from the old blocks which are **robLocalVariables_declare** and **robGlobalVariables_declare**. Since JavaScript is case sensitive for the old programs we will have invalid block exception.

We have to change in the these blocks.

**Comment by bjost2s** [comment]
new and old version of the variable declarations  blocks are now:
robGlobalVariables_declare
robLocalVariables_declare
