### ISSUE TITLE
Botnroll internal renaming

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1044]
- Botnroll plugin used to be called "ardu" internally, but with Arduino support it was renamed to "botnroll", so programs stored in DB should be checked against this change and modified accordingly. Imported programs should be checked as well.

- Blockly already incorporates needed changes, yet blocks should be checked and tested again.

**Comment by bjost2s** [comment]
related to #1031, no more mapping on blockly

**Comment by bjost2s** [comment]
This issue is not assigned to any project so it hasn't been reviewed so far. @VinArt , please move it to the corresponding project
