### ISSUE TITLE
[NXT] Missing parentheses in generated NXC code

### ISSUE THREAD

**Issue by Stex** [OpenRoberta/robertalab#1046]
**Describe the bug**

Parentheses are missing in generated NXC code for presumably almost every block that contains further internal calculations with a given value.

Feel free to mark this as a duplicate of #1041 (or the other way around), this problem seems to affect a lot of blocks.

Most likely incomplete list:

* Drive
* Motor
* Display

**To Reproduce**

1. Create a program like the following:
  <img width="398" alt="image" src="https://user-images.githubusercontent.com/27221/48205165-0682ab00-e36c-11e8-9026-d2aedda94ce3.png">

This generates the following NXC code:

```c
RotateMotorEx(OUT_BC, SpeedTest(30), (20 + 0 * 360 / (PI * WHEELDIAMETER)), 0, true, true);
```

The parentheses are missing, leading to an unexpected value.

While this is a constructed example, users will run into this as soon as they use variables with a little offset.

The following also happens with normal motor blocks:

```c
RotateMotor(OUT_B, SpeedTest(30), 360 * 0 + 20);
```

**Comment by bjost2s** [comment]
This issue is not assigned to a project, so I guess no one has reviewed this. @VinArt please move it to the corresponding project
