### ISSUE TITLE
Create list with values block is malformed in Arduino

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1056]
**Describe the bug**
 - Create list with values in Arduino is malformed in the toolbox

**To Reproduce**
1. Open list tab of the expert toolbox in Arduino

**Expected behavior**
 - The block would show values like in other systems

**Screenshots**
![image](https://user-images.githubusercontent.com/3738015/48409047-2387f700-e73b-11e8-95a0-dd9ff78ce5c2.png)
Second block from the top

**Comment by bjost2s** [comment]
Toolboxes and its contend is defined in the robots properties, so I change the labels
