### ISSUE TITLE
Revise Lists in all robots: NXC

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1059]
parent issue #1011 
Stub for an issue concerning NXT/NXC

**Comment by VinArt** [comment]
I think that Blockly.Msg.LISTS_*_TITTLE for nxc should be replaced with _TITLE_NXC and the titles themselves should not contain the word "list", instead the word "array" should be used.

**Comment by bjost2s** [comment]
We cannot easily rename blocks. What if a user has already programs with these blocks.

**Comment by bjost2s** [comment]
Please implement the checker so that an already labeled block (see #1060) will stop the compiler workflow and returns the exact error message.

**Comment by VinArt** [comment]
To sum up: there were two possibilities to implement the checker - either append the error tag and add the transformation, or add an attribute and change the XML schema. The second is merged to develop, the first is saved on feature/blockly-errors branch.

**Comment by VinArt** [comment]
set element from end needs additional -1 to the index.

**Comment by VinArt** [comment]
Average Operation on list needed an additional length parameter since the nxc compiler has a bug/feature that does not allow using ArrayLen in assignments and expressions.

**Comment by rbudde** [comment]
code generated for arrays still wrong (failing usages of ArrayLen)

**Comment by bjost2s** [comment]
What is the current state of this issue?
I will remove it from project 2.1.0 "to do" because it is already released
