### ISSUE TITLE
Block argument naming inconsistency

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#106]
The drive block and encoder sensor have different names for rotation.

![bildschirmfoto vom 2016-04-05 09 02 21](https://cloud.githubusercontent.com/assets/6226982/14273849/e72ff120-fb0d-11e5-8ba5-f0a8185faf90.png)

**Comment by BeateJ** [comment]
fixed in OpenRoberta/blockly@8ff6cfff25242f68228f30125ecbfa6781c6452a and committed in 1366bed
