### ISSUE TITLE
Arduino – "write-pin"-command reset 

### ISSUE THREAD

**Issue by matzup** [OpenRoberta/robertalab#1064]
**Description**
 - the write-pin-command will always be reseted to default (analog, pin A0) by any actions (save, see source-code, or "play" code) 

**To Reproduce**
0. open Nepo with Arduino Uno
1. create an "write-pin-command"
2. change to "digital" and Pin "A1" or any else Pin
3. open source-code view or download it or any other action...
4. the created command fall back to default settings: analog, A0

**Device information**
 - Tested on Chrome, Firefox, IE with Windows 10 and MacOS

**Comment by sebastiankmilo** [comment]
this problem had been already post
https://github.com/OpenRoberta/robertalab/issues/1017

**Comment by VinArt** [comment]
closed as duplicated
