### ISSUE TITLE
Seeed LED bar for Calliope won't turn off

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#1066]
**Describe the bug**
 - Once the LEDs of the LED bar are turned on, you can't turn them off anymore by setting their brightness to 0

**To Reproduce**
1. Go to 'https://lab.open-roberta.org/#'
2. Click on 'Calliope'
3. Choose the "set LED Bar x brightness" Block to set the Brightness of the LEDs to a number except from 0
4. Set them to 0
5. See the Error

**Expected behavior**
 - LEDs would turn off

**Device information**
 - Type: Laptop
 - OS: Windows 7 Enterprise
 - Browser: Firefox 63.0.3 (64-Bit)

**Additional context**
 - Code seems fine

**Comment by Dittse** [comment]
I tried with another Calliope and it worked fine

**Comment by VinArt** [comment]
So, does this work or is this still an issue?

**Comment by Dittse** [comment]
It depends on the Calliope that is used. I tested it on two (both 2017) and it works on one but not the other

**Comment by bjost2s** [comment]
@Dittse , if you find a second not working calliope, please reopen this issue ;-)
