### ISSUE TITLE
While page loading the browser detects a couple of errors

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#1069]
**Describe the bug**
 
![image](https://user-images.githubusercontent.com/1613069/49205111-47d80a80-f3ae-11e8-9897-49a5f7388c02.png)

**To Reproduce**
1. Go to https://lab.open-roberta.org
2. Click F12
3. See console output

**Expected behavior**
 Console should not show any error, maybe some warnings

**Device information**
 - Type Desktop
 - OS: LInux 18.04
 - Browser chrome latest

**Additional context**
 - seems to be a NaN problem during initialisation frm blockly, where a not visible element is asked for metrics

**Comment by VinArt** [comment]
NaN errors are gone, but the uncaught DOMException is still present
![image](https://user-images.githubusercontent.com/3738015/50287269-6e93d900-0462-11e9-8ba8-49023141d8f9.png)
