### ISSUE TITLE
Copying and pasting blocks shortcuts

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1076]
Currently the shortcuts for copying and pasting blocks are ctrl + c and ctrl + v respectively. However they are convenient only for right-handed use of mouse, for the left-handed use of the mouse ctrl + insert and shift + insert shortcuts are more convenient since one would have to take the hand off the mouse to use the ctrl + c and ctrl + v, whereas the ctrl + insert and shift + insert can be used without taking the hand off the mouse, therefore more convenient for the left-handed mouse use.

A solution can be to register additional shortcuts for the copy and paste operations in JS.

**Comment by bjost2s** [comment]
Please vote if someone else would like to have this feature!
