### ISSUE TITLE
Ev3 lejos V0 menu image has wrong name

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1079]
The image for  the menu entry of ev3 lejos v0 is not shown because the name is wrong (V0 is missing in the image filename)
![image](https://user-images.githubusercontent.com/3738015/49525765-bf2a0480-f8ae-11e8-8783-f0223341981b.png)

**Comment by bjost2s** [comment]
I would prefer to change the title to image renaming instead of image missing. The image has been always there.
