### ISSUE TITLE
include pictures with the code and remove from libs

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#108]
Right now we have a built-in list of pictures for the showPicture block. Those are compiled into the client libraries. Extending them would require library updates and would also increase the library size.

Since a picture is only 178*128/8 = 2848 bytes. I propose to store them on the server and include them in the generated code (as bytearray). This way we can add more picture with new releases and don't have to update the client libraries. This would also be a first step to allow custom pictures.

**Comment by cvejoski** [comment]
ev3 implementation: f7a3d1f

**Comment by cvejoski** [comment]
26f04bc

**Comment by cvejoski** [comment]
ev3 implementation: f7a3d1f,	26f04bc

**Comment by ensonic** [comment]
I'll do the changes for ev3dev tomorrow. One more thought still:
What about adding the used images to the brick-config and then referencing it from there? This would make the generated code more readable, since we would not have the long image data string in the the hal.drawPicture() call.

**Comment by bjost2s** [comment]
What is the current state?

**Comment by ensonic** [comment]
Its is working. The code is not perfect since we now include the image 'string' directly in the call. We could make a separate ticket for having a global asset storage (dictionary, hashtable).
