### ISSUE TITLE
Arduino read/write analog/digital pin implementation missing

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1080]
#1017 related

**Comment by pablopoo** [comment]
Hi @VinArt, with 2 or more digital or analog actuators, the switch between them don't work.
![imagen](https://user-images.githubusercontent.com/13492043/50231197-00c9ad80-038d-11e9-863f-853151c221d0.png)

**Comment by pablopoo** [comment]
Also found that the code generated in the program loop for the actuator variable name is in uppercase.
![imagen](https://user-images.githubusercontent.com/13492043/50235197-155e7380-0396-11e9-8cd2-dc7410648258.png)

**Comment by VinArt** [comment]
@pablopoo thank you for the comments. All that you mentioned is already fixed, but not yet released, stay tuned as it will go online soon.

**Comment by VinArt** [comment]
@pablopoo if you like, you can also join our gitter channel where we discuss testing: https://gitter.im/open-roberta-lab/Testing it is brand new, but you can write your findings there.
