### ISSUE TITLE
Wedo: In App Quickhelp needs revision

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#1085]
**Describe the bug**
 - The explanation texts in app are wrong (e.g. see infrared sensor)

**To Reproduce**
1. Open the Quickhelp (see screenshot) in app and compare with online version

**Screenshots**

![grafik](https://user-images.githubusercontent.com/25958792/49744908-20324d80-fc9e-11e8-89e4-af31aa1a1dc3.png)

**Device information**
-    Thorstens IPad 4
-    Open Roberta Mobile App Version 1.0.0

**Comment by bjost2s** [comment]
please check this in wiki.open-roberta.org.
