### ISSUE TITLE
Program never stopps

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#110]
dont no why program does not stop in sim and real
(Thorsten)
![not_stopping](https://cloud.githubusercontent.com/assets/1613069/14438128/c09f505c-0024-11e6-8a9a-8411ecf094f0.png)

**Comment by cvejoski** [comment]
This is working, for me maybe 17 rotations is too long to wait. Try with less rotation and it stops

**Comment by rbudde** [comment]
Different issue with non-termination is #107 . This error occurs only sometimes :-<

**Comment by ensonic** [comment]
Works on ev3dev.

**Comment by bjost2s** [comment]
Works for me as well

**Comment by bjost2s** [comment]
can't be reproduced
