### ISSUE TITLE
Functions do not return the return value if the function body is empty

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/robertalab#1101]
**Describe the bug**
When creating a function with a return value and only the return value is specified, but no command is put into the function body, the generated code will not return the specified return value. This bug is present for NAO and micro:bit.

**To Reproduce**
1. Start the Open Roberta Lab and select either NAO as robot or the micro:bit
2. Switch to expert mode
3. Drag a "function with return value" block from the functions category into your program.
4. Select "Number" or "String" as return type and add a return value to the connector according to the chosen type.
5. Drag a "say" block (NAO) or "show text" block (micro:bit) into your program.
6. Drag the "call function"(your function's name) block from the functions category onto the connector of the block from step 5, to output the result from the function in a human understandable way.
7. Run the program or open the code view and take a look at the function declaration.

**Expected behavior**
 - The robot will say or show the result, that you defined as result value in your function.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10925094/50346990-6f953b00-0534-11e9-99c3-7b498095d635.png)

**Test progam (micro:bit)**
https://lab.open-roberta.org/#loadProgram&&microbit&&NEPOprog&&%3Cexport%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%3E%3Cprogram%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22microbit%22%20xmlversion=%222.0%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%220%22%20y=%220%22%3E%3Cblock%20type=%22robControls_start%22%20id=%22uqExaD%7D8@Vdi-J(#CLH7%22%20intask=%22true%22%20deletable=%22false%22%3E%3Cmutation%20declare=%22false%22%3E%3C/mutation%3E%3Cfield%20name=%22DEBUG%22%3E%3C/field%3E%3C/block%3E%3Cblock%20type=%22mbedActions_display_text%22%20id=%22wfL-fH@EK!(+5S1vA_x4%22%20intask=%22true%22%3E%3Cfield%20name=%22TYPE%22%3ETEXT%3C/field%3E%3Cvalue%20name=%22OUT%22%3E%3Cblock%20type=%22robProcedures_callreturn%22%20id=%22E6pT%7CT%7BpIOIex%5Bl6%7DxJA%22%20intask=%22true%22%3E%3Cmutation%20name=%22helloBug%22%20output_type=%22String%22%3E%3C/mutation%3E%3C/block%3E%3C/value%3E%3C/block%3E%3C/instance%3E%3Cinstance%20x=%220%22%20y=%2280%22%3E%3Cblock%20type=%22robProcedures_defreturn%22%20id=%22z?y%60%5B%5BXQ%60%7DC%5E8,EWKy2;%22%20intask=%22true%22%3E%3Cmutation%20declare=%22false%22%20return_type=%22String%22%3E%3C/mutation%3E%3Cfield%20name=%22NAME%22%3EhelloBug%3C/field%3E%3Cfield%20name=%22TYPE%22%3EString%3C/field%3E%3Crepetitions%3E%3Cvalue%20name=%22RETURN%22%3E%3Cblock%20type=%22text%22%20id=%22?3s!=1X%7Ck)yoH(tQ%5Dr4b%22%20intask=%22true%22%3E%3Cfield%20name=%22TEXT%22%3EHello%20bug.%3C/field%3E%3C/block%3E%3C/value%3E%3C/repetitions%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/program%3E%3Cconfig%3E%3Cblock_set%20xmlns=%22http://de.fhg.iais.roberta.blockly%22%20robottype=%22microbit%22%20xmlversion=%222.0%22%20description=%22%22%20tags=%22%22%3E%3Cinstance%20x=%22138%22%20y=%2288%22%3E%3Cblock%20type=%22mbedBrick_microbit-Brick%22%20id=%221%22%20intask=%22true%22%3E%3C/block%3E%3C/instance%3E%3C/block_set%3E%3C/config%3E%3C/export%3E

**Device information**
 - Type: Laptop
 - OS: Windows 10
 - Browser: Firefox 60 ESR

**Comment by bjost2s** [comment]
This issue seems to be solved but never reviewed in any project.Please move it to the corresponding project that we can review it (although it might have been released already)
