### ISSUE TITLE
Simulation fps is fluctuating

### ISSUE THREAD

**Issue by jironer** [OpenRoberta/robertalab#1110]
Hi,
I've entered a contest, which's first part is creating a program than can make a robot move along a line in the roberta lab simulation enviroment. Unfortunately the fps at which roberta lab's simulator runs at seems to change randomly (for example this afternoon it was about 60fps in firefox and 500-1000 fps when I was using Google Chrome, however a few hours later it was 60fps in both, so I decided to change the computer I was using and I got there fps between 333 and 500). I've tried installing my own server, however that didn't seem to affect anything. So my question is, if there is any way to stabilize the fps, preferebly to something like 500 or 1000.
Thank you for any advice you can give me

**Comment by bjost2s** [comment]
The fps are not server related, only browser. So you findings with firefox and chrome are the same that we have made. There are good and not really good days with chrome, depending on the version.
In general the fps should be between 30 and 60, depending on the machine and the workload.
If you want to have it stable I would suggest you to use firefox.
Btw. the simulation of our robots takes care of the fps, so the behaviour should be the same.
