### ISSUE TITLE
EV3: Setting list with another list element destroys itself

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#1112]
**Describe the bug**
 - If you try to set an element of a list with another list element (out of itself or another list) as shown in the screenshot, the first list given will detach itself. It also doesn't become pale like other not attached blocks.

**To Reproduce**
Build the first screenshot with one of the following list types:
- Boolean
- String
- Colour
- Connection

**Expected behavior**
 - The Block doesn't detach itself.

**Screenshots**
Before Compiling:
![grafik](https://user-images.githubusercontent.com/25958792/51395051-22f54d80-1b3c-11e9-901d-714889e35858.png)
After Compliling:
![grafik](https://user-images.githubusercontent.com/25958792/51395415-19201a00-1b3d-11e9-8fe1-c54657c5e4e1.png)

**Device information**
Type: Laptop
OS: Windows 7 Enterprise
Browser: Firefox 63.0.3 (64-Bit)

**Additional context**
 - Only a list of numbers works fine

**Comment by rhasel4s** [comment]
Works now also for the other datatypes. 

When importing old programs the block will still detach itself since the mutation is missing. Attach the block again and export the program to update the mutation.
