### ISSUE TITLE
Additional variable assignments generated when not needed

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#1117]
**Describe the bug**
 - In the arduino plugin when a variable is used in the function it generates not needed assignment in the setup.

**To Reproduce**
1. Go to arduino plugin
2. Create a function with arguments
3. Call it
4. See additional lines in setup function

**Expected behavior**
 - Those lines are not generated

**Screenshots**
![image](https://user-images.githubusercontent.com/3738015/51899327-17631b80-23b3-11e9-9cc1-fc15d5570128.png)

**Additional context**
@pablopoo provided the solution to this one and it will be applied

**Comment by bjost2s** [comment]
Seems that this issue was not part of the lasts release project.
