### ISSUE TITLE
Add a "deactivate display" block for calliope

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/robertalab#1118]
**Is your feature request related to a problem? Please describe.**
 - You can currently select all pins in the "write digital value to pin" block, yet the pins C04-C12 collide with the LED-Matrix (display).
- If you write a value to one of this pins, the display will start wild flickering. 

**Describe the solution you'd like**
 - Add a "deactivate display" and "activate display" block, that deactivates the display, so no flickering occurs while this pins are being used.
- Alternatively an "activate display [true|false]" block could be used as well.

**Additional context**
 - The calliope API offers a function to deactivate or activate the display for these exact purposes.

**Comment by boonto** [comment]
- [ ] Blockly
- [ ] Serverside Action
- [ ] Code generation
- [ ] Tests
- [ ] Test on Calliope
- [ ] Test on Calliope 2016
