### ISSUE TITLE
Ev3dev broken with 3.1.0 (still works with 3.0.3)

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#1130]
**Describe the bug**
Ev3dev based robots receive a http 500 (internal server error) when starting a prora from the lab.

**To Reproduce**
1.Connect an ev3dev based lego mindstorms robot
2. Create a program (does not matter, e.v. drive forward 20cm)
3. Click play
4. The robot gets http 500 and disconnects

**Comment by bjost2s** [comment]
Is it connected via the cable or via wifi?
Same issue on local machines or https://test.open-roberta.org?

**Comment by rbudde** [comment]
Artem already solved that issue by stored the Python sources in the file system. We have merge his changes and then hotfix this tomorrow

**Comment by rbudde** [comment]
@bjost2s Better assign it to Artem

**Comment by bjost2s** [comment]
@rbudde please prepare the hotfix today if possible so that I can publish it in the evening or tommorrow morning, otherwise it will be published next week. @VinArt , please assign yourself.
