### ISSUE TITLE
No connection possible with EV3 lejosv0

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#1132]
**Describe the bug**
 - When trying to connect a EV3 lejosv0 with the lab, an error message appears
**To Reproduce**
1. Go to connect
2. Type the token in the corresponing field
3. Click on ok
4. See popup

**Expected behavior**
 - connection can be established

**Screenshots**
![image](https://user-images.githubusercontent.com/1613069/53050080-cb2e6700-3498-11e9-8779-d1a084515aeb.png)

**Comment by the-matzup** [comment]
Same here. Suddenly unable to connect with EV3 leJOS 0.9.0.
