### ISSUE TITLE
Link to the real lab on the test server

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#1136]
**Is your feature request related to a problem? Please describe.**
 - If users access the test server by accident:
   - they may not notice the difference
   - they may not find back to the deployed server

**Describe the solution you'd like**
 - Add a prominent disclaimer and a link to the real lab on the start popup

**Comment by WckD123** [comment]
Hi, I would like to start contributing. This issue seems easy from the outside, is this something that a beginner can do? (I wouldn't want to take up a bug only to later realise that it was too big a task)
