### ISSUE TITLE
Old picture of calliope mini at Roboter-Configuration 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#1141]
**Describe the bug**
 - I expect the latest picture of calliope mini at Robot-Configurtaion 

**To Reproduce**
1. Go to 'Open Roberta Lab.'
2. Click on 'RobotKonfiguration'
3. See old version of Calliope mini

**Expected behavior**
 - New version of Calliope mini.

**Screenshots**
![calliopemini2019](https://user-images.githubusercontent.com/19221359/53432202-615f1180-39f2-11e9-8f7d-0c665b78b861.jpg)

**Device information**
- all devices

**Comment by bjost2s** [comment]
Todo:
Merge our background picture with the new calliope version as background. The picture above is not suitable for this, we need a new svg with only calliope, no labeling

**Comment by VinArt** [comment]
As I understand in 0b3af4d1ef95af0fc5e37ca502c92b27ea105ea5 new backgrounds were uploaded, and on lab server I see currently different ones in configuration, so I think this is resolved.
