### ISSUE TITLE
No Simulation within IE 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#1142]
**Describe the bug**
 - With IE the OR Simulation is not working.

**To Reproduce**
1. Go to 'open-roberta.org'
2. Click on 'SIM'
3. Nothing happens

**Expected behavior**
 - Open Roberta Simulator shows up and simulation is running

**Screenshots**
 - Nothing to show because nothing happens.

**Device information**
 - Type Desktop
 - OS: Windows 10 Enterprise 2016 LTSB, Version 1607
 - Browser Internet Explorer 11, Version 11.2485.433.0, Updateversion: 11.0.85

**Additional context**
 - Add any other context about the problem here.

**Comment by bjost2s** [comment]
Unfortunately IE 11 only supports ES5, not ES6
We have to update the following lines
`var blocklyprograms = programs.map(x => BUILDER.build(x.javaScriptProgram));` 
` programEvals = programs.map(x => new ProgramEval());` 
which are causing an error

**Comment by bjost2s** [comment]
Are you using IE frequently?
Maybe you would like to become one of our testers?
