### ISSUE TITLE
Calliope: uBit.display.disable()

### ISSUE THREAD

**Issue by the-matzup** [OpenRoberta/robertalab#1145]
(feature request or bug?)

**Is your feature request related to a problem? Please describe.**
The pins C04-C15 can not be controlled as long as the display is enabled (or not disabled). 

**Describe the solution you'd like**
Therefore it is necessary that there is the possibility to use a block that implements this code:
`uBit.display.disable()`

**Alternative**
Only enable the display if appropriate LED blocks are used.

**Additional context**
- This problem was also mentioned here (german): https://forum.calliope.cc/t/c04-bis-c15/868
- This is how it is solved with makecode:
![image](https://user-images.githubusercontent.com/47818886/53522824-87141580-3adb-11e9-88b1-30b775a96ba5.png)
![image](https://user-images.githubusercontent.com/47818886/53522807-7cf21700-3adb-11e9-9151-9d6154b55349.png)
- Compare the information at mirco:bit, in which Calliope has taken a lot (also the led deactivation): https://lancaster-university.github.io/microbit-docs/ubit/display/ 
--> 
> 'enable' and 'disable' turn on and off the display. When disabled, you can reuse many if the GPIO pins. See the MicroBitIO class for more information.

**Comment by bjost2s** [comment]
Thank you, it seems that this is the same issue than #1118
