### ISSUE TITLE
Add a stop button in the workspace to abort running WeDo (javascript) programs

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#1152]
**Is your feature request related to a problem? Please describe.**
 - Sometimes, e.g. if your program is in a kind of infinite loop the stop button would make programming with WeDo much easier.

**Describe the solution you'd like**
 - For WeDo (and maybe future BLE robots) the start/run button should not be greyedout and disabled but turn into a stop button once the program is running
**Describe alternatives you've considered**
 - The button on the WeDo could be used for it, but it is already used by the hardware (long press) and should also be programmable by the user.
**Additional context**
 - Android and IOS apps should not be affected, that is good
 - related to #218, maybe we could support this one day, the button will than be there ;-)

**Comment by VinArt** [comment]
tested with Android app on Chromebook.
