### ISSUE TITLE
Calliope simulation: wait-block fails

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#1170]
A program waiting for a button press doesn't work in the simulation, but works on the real device.

**Device information**
 - win laptop
 - chrome and firefox. Independent of browsers.

**Comment by bjost2s** [comment]
For me it is working, e.g. with the following program
![image](https://user-images.githubusercontent.com/1613069/54739015-ce5f6480-4bb6-11e9-90e3-9f28f3c526f2.png)

chrome on linux, windows 10

**Comment by bjost2s** [comment]
the difference is in the xml:
new
`<field name="SENSORPORT">button_a</field><field name="SLOT"/></block>`
old
`<field name="SENSORPORT">A</field>`

but
the new version should **not** work! but the old, very strange

**Comment by rbudde** [comment]
Remark: this problem occurs, when an old Calliope program is loaded from the database. Its wait-block is not decomposable and the simulator freezes (the actual wait block from the tool box is ok, simulation works).
