### ISSUE TITLE
create list with images cannot be compiled

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#1175]
**Describe the bug**
 When trying to compile the following program, an error message appears
*Screenshots**
![image](https://user-images.githubusercontent.com/1613069/55157230-39331180-515c-11e9-8214-ec331e44872b.png)

**Expected behavior**
 The program should be compiled and after executing it should behave similar to the simulation

**Comment by VinArt** [comment]
The title of the issue is wrong, should be: show animation block does not work with list-create block. Since list create block with image data type on it's own works.

**Comment by bjost2s** [comment]
For me a show animation with a variable works, so the problem is not the show animation
