### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Wodric** [OpenRoberta/robertalab#123]
Hi all,

On source code I found partial french translation. It could be interesting to finish it's integration. 

What do you think about this?

**Comment by bjost2s** [comment]
In general we use the translations for the blocks from blockly. All non blockly blocks (robot blocks) and meny stuff will be translated in a google table. Someone else just started with the french translation. Would you like to help? If so I would send you an invitation to the doc ;-) 
Many thanks for you interest in Open Roberta

**Comment by Wodric** [comment]
You can invite me, I don't know when I will have time to contribute, I will help as much as possible.

**Comment by ensonic** [comment]
Please contribute through the doc.
