### ISSUE TITLE
SSO connector

### ISSUE THREAD

**Issue by Wodric** [OpenRoberta/robertalab#124]
Hi,

In french education system, there are lot of educationnal sofwares which are connect by SSO (mostly with [shibboleth](https://shibboleth.net/) or [CAS](http://jasig.github.io/cas/4.2.x/index.html)). The integration Open Roberta  in these could be much more easier. 
I didn't see anything about it on Open Roberta. What do you think about the idea? 

 I could get involved in this.

**Comment by bjost2s** [comment]
This sounds interesting! A long time ago we have discussed this, but unfortunately nobody of us has had time for this. Currently the Open Roberta Team is focussing on integrating new robot systems, but it would be great if you would like to help us. Let's discuss necessary steps here.

**Comment by ensonic** [comment]
A first step would be to collect which SSO solutions are used in various countries (with links to who provides them - for 'CAS' I find a lot of hit, but nothing that looks like SSO). Ideally we can figure on what technology they are based (e.g. OAuth2). This could be done on a wiki page liked from here.

**Comment by Wodric** [comment]
I let you create the wiki page, can't contribute to it.
As I know, CAS and Shibboleth is very used in France, I already heard about OAuth2 in some systems. 

LMS (Moodle for exemple) are using LTI protocol to import courses or exercise.

**Comment by rbudde** [comment]
not feasable at the moment
