### ISSUE TITLE
"wenn taste gedrückt" (if button pressed) does not work

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#125]
probably an error in the javascript simulation: a button needs a STATE pressed (from the DOWN event to the UP event).

I could not make the attached program executing the then part in the simulation as expected.

![button-pressed](https://cloud.githubusercontent.com/assets/15834363/14981899/b866d332-1132-11e6-983d-e1f294ff2679.png)

**Comment by bjost2s** [comment]
indeed, we check for the "click" event, so this program could work as expected, if you manage to click exactly between the end of the wait block and the if statement.
We should check for pressed
