### ISSUE TITLE
suggestion: set default branch on github to "develop"

### ISSUE THREAD

**Issue by dlech** [OpenRoberta/robertalab#13]
In the settings for each repository, github allows you to select the default branch that is displayed when anyone visits the site. If you have master as the default, then people will do like I just did and send a pull request to master instead of develop. :grin:

**Comment by bjost2s** [comment]
We have had that in the old repository and switched to master as default. We have people (none developers) that clone the repository to run the server locally. It is hard to explain for them how to switch to master.

**Comment by dlech** [comment]
That makes sense. Another option is to tag releases. GitHub automatically provides .zip and .tar.gz files for each tag. You could point people that want a known working release to download from there instead.

Or you should add a note to the readme in master (because that is the one people are going to see) that explains your workflow.

**Comment by ensonic** [comment]
So actually at least until the next release we're doing new changes against develop.
