### ISSUE TITLE
NXT compiler workflow

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#130]
Implement the NXT specific workflow from generating porgrams code to sending binary to the robot.

More details later

**Comment by BeateJ** [comment]
will be done in #131

**Comment by dpyka** [comment]
NXT roundtrip is now working for Windows on server side and Windows on client side.

**Comment by dpyka** [comment]
Some paths are resolved quite strange in the NxtCompilerWorkflow, but they are working somehow. Taken from the output of the compiler binary:
# Status: Current file = "E:\Development\Repositories\robertalab\**OpenRobertaServer\../OpenRobertaServer**/userProjects/YSW7S26A/NEPOprog.nxc"
# Status: Include path = .\;E:\Development\Repositories\robertalab\OpenRobertaServer\;E:\Development\Repositories\robertalab\RobotNXT\resources\;resources**//hal.h\**
# Status: Searching for file: E:\Development\Repositories\robertalab\OpenRobertaServer**\.\hal.h**
# Status: Include path = .\;E:\Development\Repositories\robertalab\OpenRobertaServer\;E:\Development\Repositories\robertalab\RobotNXT\resources\;resources**//hal.h\**
# Status: Current file = "E:\Development\Repositories\robertalab\**OpenRobertaServer\../OpenRobertaServer**/userProjects/YSW7S26A/NEPOprog.nxc"
# Status: Current file = "E:\Development\Repositories\robertalab\**OpenRobertaServer\../OpenRobertaServer**/userProjects/YSW7S26A/NEPOprog.nxc"
# Status: Include path = .\;E:\Development\Repositories\robertalab\OpenRobertaServer\;E:\Development\Repositories\robertalab\RobotNXT\resources\;resources**//hal.h\**
