### ISSUE TITLE
Refactoring GUI

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#135]
first steps:
- [ ] update to the latest blockly version
- [x] use bootstrap tabs 
- [x] use bootstrap tables in the list tabs
- [ ] use TypeScript
- [ ] refactor popups - to many declarations in the html

**Comment by rbudde** [comment]
note, that -if I rememer right- there is a bootstrap version of the jquery-datatables plugin (which is used in its plain version now)
