### ISSUE TITLE
Unit Tests Clean Up

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#142]
There are parts of the Unit test that are bit messy. We have to do clean up
- add code coverage tool to the project
- find and remove duplicate unite test (testing same functionality)
- add unit tests for the new functionality
- fix or remove the ignored unit tests

**Comment by ensonic** [comment]
One advice for unit tests. Please follow http://c2.com/cgi/wiki?ArrangeActAssert
To summarize, a test

- has a descriptive name (that tells what the tests tests)
- had only one assert that check what the name describes

If the setup code is complicated, extract it into a helper.
