### ISSUE TITLE
Blockly Performance Issue

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#15]
Every time when block is moved in the workspace additional HTML <path> attribute is added for the connector of the block. This have big impact on the performance of blockly.

**Comment by ensonic** [comment]
This will be fixed when we upgrade to latest blockly.

**Comment by cvejoski** [comment]
This is just reminder, to check if everything is ok after updating to the new blockly because this bug is from our side not from Blockly.

**Comment by bjost2s** [comment]
Thanks, I will check all the old issues and add them here, if they are still relevant

**Comment by bjost2s** [comment]
fixed in new blockly
