### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#154]
Hello,

I have read the readme file and it turns out to be that ora.sh should be run with --start-server key, not just --start. Also I was able to build the whole thing with maven 3.1.1 and run it with java (build 1.8.0_51-b16). Maybe the readme should be updated.

Cheers.

**Comment by bjost2s** [comment]
Thanks, I'll check this and update the readme.

**Comment by ensonic** [comment]
Fixed by https://github.com/OpenRoberta/robertalab/pull/157
