### ISSUE TITLE
Spelling mistake in SERVER_NOT_FOUND message

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab#155]
![screenshot from 2016-07-14 11 52 30](https://cloud.githubusercontent.com/assets/632207/16835549/89b09c20-49b9-11e6-8c48-b6feb72de7f4.png)

Mistake is "hasitate" instead of "hesitate".

**Comment by ensonic** [comment]
@BeateJ which file should be updated? Is it robMessages.js?

**Comment by bjost2s** [comment]
all messages from Open Roberta have to be fixed in folder robMsg in the blockly project. Usually the json files have to be updated, only for english it is  the robMessages.js from which the en.json file is automatically created
