### ISSUE TITLE
if- else if block

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#159]
It was fixed in the main project, however, on develop branch this block shows " if (true) " no matter what was in the block. (for both NXT and EV3)

![image](https://cloud.githubusercontent.com/assets/13983474/16836969/d449a784-49c0-11e6-9163-ba26c84cbea3.png)

**Comment by cvejoski** [comment]
This bug is caused by invalid generation of XML code. The element **repetition is empty**, and should contain the all the if-else elements inside.
