### ISSUE TITLE
Extract update procedure for lejos

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#162]
```
There is a new firmware version for your robot available. You can try to run programs with the old version, but best bet is to update your robot now! You just have to click >>Update now<<.
```

As discussed having a separate server that hosts the package updates for lejos and make the lejos systems checking for updates is probably a better solution.

The firmware check is right now done on the js side in:
OpenRobertaServer/staticResources/js/app/roberta/roberta.robot.js

**Comment by bjost2s** [comment]
Does the user has to connect implicitly to the update server or is it possible to redirect the robot automatically?

**Comment by bjost2s** [comment]
we should start working on this after #308

**Comment by rbudde** [comment]
will be a topic when we re-arrange our servers.
