### ISSUE TITLE
Use the JavaCompiler as a library for lejos

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#165]
The idea is to avoid tempfiles and shelling out to tools.

Examples: 
http://stackoverflow.com/questions/12173294/compile-code-fully-in-memory-with-javax-tools-javacompiler
http://www.java2s.com/Code/Java/JDK-6/CompileaJavafilewithJavaCompiler.htm

We need to be careful to set the right bytecode level.

**Comment by bjost2s** [comment]
would that mean, we do not need the sdk on serverside anymore?

**Comment by ensonic** [comment]
No, we'd still need the sdk. We just lower the load on the server (less context switches and less file-io).
