### ISSUE TITLE
ButtonPressed sensor, buttons naming

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#166]
The best way to implement this function without hardcoding is to get button key directly from the block:
 this.sb.append("ButtonPressed(" + brickSensor.getKey() + ", false)");
Would it be possible to change the naming in xml in the following way:
ENTER -> BTNCENTER
LEFT -> BTNLEFT
RIGHT -> BTNRIGHT
Or at least ENTER to CENTER?

**Comment by bjost2s** [comment]
for the xml I could do it but I think enumerations are handled specially on server side, so perhaps we could do it there?
