### ISSUE TITLE
The initial modal dialog is too large and doesn't scroll

### ISSUE THREAD

**Issue by larsrc-google** [OpenRoberta/robertalab#169]
On a laptop screen, the checkbox to not show the initial dialog is inaccessible. Fix: add overflow:auto to the .modal style.

**Comment by bjost2s** [comment]
can you please provide the browser and system. For me windows and linux, chrome and firefox and on android it works fine

**Comment by larsrc-google** [comment]
This was with Chrome on a fairly recent 13" MacBook Air - can't say the exact versions as I have updated since then.

**Comment by bjost2s** [comment]
due to be not reproducable, I close this. Please open again if error occurs.
