### ISSUE TITLE
Integrate latest blockly

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#18]
as a submodule of the robertalab. 
Add all necessary changes to the OpenRoberta/blockly fork.
- accept RGB values as block colour
- typed variables
- in task check
- Open Roberta layout

**Comment by cvejoski** [comment]
I have modified the new Blockly version to generate OpenRoberta compatible XML. This should be tested with the XML programs in Open Roberta project when the new Blockly is added to the Open Roberta.

**Comment by bjost2s** [comment]
Further work 
* Open Roberta layout
* reimplement buttons
will be done in the "require" branch (just rebased on newblockly)

**Comment by bjost2s** [comment]
please have a look in OpenRoberta/blockly
most work is there
