### ISSUE TITLE
Provide robot specific data when robot system is switched

### ISSUE THREAD

**Issue by BeateJ** [OpenRoberta/robertalab#181]
The rest call /admin/setRobot returns now only success. 
It should return the robot specific data for the GUI like toolbox, configuration ... These information is currently stored in the database but should be supplied by the specific robot project directly.

json
```json
{ "result": "ok",
    "robot": {
        "ev3": {
            "program": {
                "toolbox": {
                    "beginner": "<xml>",
                    "expert": "<xml>"
                },
            "defaultProgram": "<xml>"
        },
        "configuration": {
            "toolbox": "<xml>",
            "defaultConfiguration": "<xml"
        }
    }
}
```

**Comment by bjost2s** [comment]
The rest call /admin/setRobot now returns all the necessary information, but it is hardcoded in the ClientAdmin.java. See commit cc2e4c0340c46ce5b10e03677b01bcfbf3686a99
