### ISSUE TITLE
"Show Text" block, remove arrays

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#182]
The block works well with all types except for arrays, so that would be better to remove them from possible types accepted by this block.

**Comment by bjost2s** [comment]
![image](https://cloud.githubusercontent.com/assets/1613069/17032067/b764c3b2-4f77-11e6-962b-bde170d9ecab.png)

All types are working fine now with "show text" or they are not allowed, except connection.
Should I remove it or is it a bug?

**Comment by elhele** [comment]
No, it should be there, the problem is in Bluetooth block, not "show text". I guess, it would be still "undefined" if you remove "show text" block.
I didn't manage to fix Bluetooth yet.

**Comment by bjost2s** [comment]
Thanks!
