### ISSUE TITLE
Turn color on color sensor on is not working

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#184]
![image](https://cloud.githubusercontent.com/assets/1613069/17032343/06ea88b2-4f79-11e6-8026-23e75b86b366.png)

**Comment by elhele** [comment]
Is it a new block? I did't implement it and I don't remember it in EV3.
Is it replacing "EV3 brick light" block that was for brick's backlight, not for sensor? If it is there, I can fix it quickly tomorrow.
