### ISSUE TITLE
improve the generated code of wait-statements

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#201]
The wait-statements generate quite verbose code right now:

``` python
while True:
  if ( hal.getUltraSonicSensorDistance('4') < 48 ) or hal.isKeyPressed('enter'):
      break
  hal.waitFor(15)
```

It would be nice to use this instead:
``` python
while not ( hal.getUltraSonicSensorDistance('4') < 48 ) or hal.isKeyPressed('enter'):
  hal.waitFor(15)
```

The motivation here is to create code that looks like what a good developer would write, since one can look at the generated code.

Unfortunately the conditions on connects to the wait-until block are pre-wrapped with 'if' + 'break' somewhere, so that right now the codegen would create:
``` python
while not if hal.getUltraSonicSensorDistance('4') < 48:
  break:
  hal.waitFor(15)
```

I think the waitstatement should contain a simple (compound) statement with the waiting condition.

**Comment by cvejoski** [comment]
We can change the code when we have only one conditions statement like you propose in the ticket, but for the following case:
`while ( true ) {
            if ( hal.isPressed(SensorPort.S1) == true ) {
                hal.driveDistance(DriveDirection.FOREWARD, 30, 20);
                break;
            }
            if ( hal.getColorSensorAmbient(SensorPort.S3) < 50 ) {
                hal.drawText("Hallo", 0, 0);
                break;
            }
            hal.waitFor(15);
        }`

this would no work.

**Comment by ensonic** [comment]
I am talking about the "wait-until" block. This cannot have children:
![screenshot from 2016-08-12 11 50 39](https://cloud.githubusercontent.com/assets/1279486/17619043/404f4c94-6083-11e6-9058-413b6fe73b4b.png)
