### ISSUE TITLE
update 'track width' in brick configuration to match the default robot model

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#203]
The track width is currently set to 18cm by default. In the default roberta model the track width is 12cm.

**Comment by bjost2s** [comment]
The default Open Roberta Model has a track width of 18cm. Unfortunately the link is brocken to the instructions. This should be fixed. See #194

**Comment by ensonic** [comment]
Is the model different to what roberta teachers usually built ("Bauanleitung RobertaEV3")? That would be sad.

**Comment by Thorlogy** [comment]
The original / official Roberta model isnt perfect for mounting the color sensor. Therefore we decided to design an Open Roberta EV3 model...  the plan is to integrate this model in the updated Roberta-Grundlagenband which will be published end of October.

**Comment by ensonic** [comment]
I am happy to test the new instructions. I made a few small tweaks to the current instructions to manage the cables.
