### ISSUE TITLE
Wait Statement Block Comparison Operator change

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#204]
In the wait statement block changing the sensor also changes the comparison operator.

![1](https://cloud.githubusercontent.com/assets/6226982/17622341/0521167c-609a-11e6-8071-2fca94c7a8ee.png)

![2](https://cloud.githubusercontent.com/assets/6226982/17622344/0730eed8-609a-11e6-9d7e-9b1a4b2b1429.png)

changing from light to ambient light also changes **>** to **<**

**Comment by Thorlogy** [comment]
Its not only in the wait statement block its within the logic block.
And the bigger (than) operator changes always to less (than) - not the other way around.

**Comment by bjost2s** [comment]
please check also #185
