### ISSUE TITLE
EV3 Brick connected when BnRoll is chosen

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#206]
It is possible to connect EV3 robot when BnRoll or NXT robot is chosen.

I am not sure if this is intentional or it is a bug :)

**Comment by bjost2s** [comment]
The GUI side doesn't know the type of robot at connecting time. There is some work to do on server side, see #181
-> Best would be to switch to the connected type of robot, I think

**Comment by cvejoski** [comment]
fixed: b50555771892d74351464be56333d7d5cd3c67fb
