### ISSUE TITLE
Light Sensor 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#210]
The light sensor block is not working  - pop up "server error" appears

**Comment by cvejoski** [comment]
The light sensor is working on the nxt when is used outside wait statement, but it is not working in the simulation. 

When the light sensor is used inside a wait statement then we have "server-error"

**Comment by cvejoski** [comment]
The light sensor in wait statement bug is fixed by commit: https://github.com/OpenRoberta/robertalab/commit/5cc34393d3b0e3d6330ea6ac9caf2271a4c0b8e5

New ticket is opened for the light sensor implementation in the simulation: #221
