### ISSUE TITLE
Set volume

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#214]
The nxt version of set volume block - no changes the volume of the sound - but it changes the volume if a button is pressed. 

Please check the spec.

**Comment by elhele** [comment]
It was intentionally implemented like this, there is no way to change the volume of tone, only the buttons. "Set volume. Set the user interface volume level. Valid values are from 0 to 4."
http://bricxcc.sourceforge.net/nbc/nxcdoc/nxcapi/group___ui_module_functions_ga998e2678b97428b98796548bd7a8f164.html#ga998e2678b97428b98796548bd7a8f164
Should the blocks be changed so it would be more clear? Was it different for EV3?
