### ISSUE TITLE
Sound file block

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#216]
The EV3 brick can play sound files. This should also be possible with Open Roberta / NEPO

**Comment by ensonic** [comment]
For this we need to fix #90 first.

**Comment by peacepro** [comment]
Is there a way to play a .wav sound file with the EV3 an Open Roberta?

**Comment by ensonic** [comment]
Unfortunately not yet. See comment 2. We need to add a way to upload assets (sounds and images) and store them with the program.

**Comment by peacepro** [comment]
For my son it is very easy to use Open Roberta.
He is very sad that he can not play audio files.
He wants to show off his friends a talking EV3.

**Comment by rbudde** [comment]
espeak. GSOC.
