### ISSUE TITLE
Changes in blocks for botnroll

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#224]
Action

1)  Move  blocks.
First there was no option for moving only one motor in the library. Now José  is adding new functions. However, I'm not entirely sure that he'll make it till September. In this case two motor function and two speed variables to store non-changed motor speeds will be used. 
- Blocks "motor port on speed" and "set motor speed" are the same for this robot, we need to merge them. It might make sence to chenge this block so it could applz some speed for both motors.
- Block "motor port on speed for rotation/degree" can not be implemented, because there is no encoder.
- Block "get speed motor port" can not be implemented because there is no encoder.
- Block "stop motor port float/brake" can be implemented after José  creates a function for separate stop of the motors with these modes (not sure that till September). So far it can only be done using a function for motor speed with a speed of the required motor set to 0.

2) Drive blocks.
There are no functions exactly for turning, all blocks are implemented using move motors function.
- Block "drive forwards/backwards speed" is not a problem, there is a function for it in the library. 
- Block "stop" is not a problem, there is a function for it in the library (stop, "It cuts the energy to the motors and they rotate freely until they stop"). There is also a function for brake. Perhaps we could add it into block.
- Blocks "drive forwards/backwards speed" and "turn right/left degree" are hard to implement without encoder. If we try to rely on time, it won't work since speed depends on battery. José  was going to fix it, but not clear when excalty. We could change blocks so it would work with time instead of distance.

3) Display blocks work fine, but instead of "in column" and "in row" we have should have  only lcd line number (1 or 2)- there are two functions lcd1 and lcd2.

4) Sounds.
- Block "play frequency duration" works well;
- Blocks "set volume" and "get volume" are reallz hard to implement on Arduino. As I understand, it maz require some hardware changes.

5) Lights. As we discussed, we can use a block similar to EV3, but without colors and with only "on/off" options.

++  there are two additional servo motors which can move from 0° to 180°;
++ infrared emitters action (?) ;
++ curve movement.

Sensors
- There is no touch, sound, light and encoder sensor.
- We need to put back infrared sensor. There are two relevant functions: read infrared sensor that can only detect another infrared signal and obstacle sensor that we could use, This function returns numbers from 0 to 3 (no obstacles, left obstacle, right obstacle and obstacles on  both sensors).
  If it is needed, we could ask José  to implement it differently,
- There are two ultrasonic sensors (front and on the robot's "head"). Front one is divided into three parts (brm.readSonars(&sonarL,&sonarC,&sonarR);) and returns distances up to 200 cm from three directions.
- There is a compas sensor that can be implemented as EV3 gyro sensor.
- Timer can be implemented just like in NXT, also with only one timer.
- Color sensor. There are two RGB color sensor those can be read separately (readRgbL(byte_,byte_,byte_), readRgbR(byte_,byte_,byte_)). So, we get three standart (0-255) values fro red, green and blue. Should we convert it to some colors or return it like it is and change the block? 

General
- byte type is widely used in Arduino programming, I think, we should add it to the variable type list.

UPD: 
- replace gyro sensor with compass in brick configuration;
- remove ambient mode and add ports up to 8 for light sensor;
- fix block "wait until" so it would compare infrared sensor value with a boolean value; add light sensor to this block.
  -remove connection data type.
  Arrays:
- it would be better to live only "get/set" item in block "in list get/set". Insert and delete would be hard to implement.

**Comment by bjost2s** [comment]
I think encoders are available, so not removing the encoder sensors make sense.

**Comment by elhele** [comment]
On some models- the older ones- encoders are available, but, as I understand, they removed the encoders from the newer models. I guess yes, we just could make it possible to remove and include them in the robot configuration.
