### ISSUE TITLE
Checking Program-Configuration Compatibility at Wrong Place

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#232]
Checking the program-configuration compatibility should be in the compiler workflow and specific for each robot project.

At the moment we check this at https://github.com/OpenRoberta/robertalab/blob/d28e780352a261bf95074f66dc86d2c0301a1fb4/OpenRobertaServer/src/main/java/de/fhg/iais/roberta/javaServer/restServices/all/ClientProgram.java#L238-L240

This is also true when we run a program in the simulation

https://github.com/OpenRoberta/robertalab/blob/d28e780352a261bf95074f66dc86d2c0301a1fb4/OpenRobertaServer/src/main/java/de/fhg/iais/roberta/javaServer/restServices/all/ClientProgram.java#L268

**Comment by rbudde** [comment]
yes
