### ISSUE TITLE
User information about EV3 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#246]
If the EV3 is choosen the user should get infrormation what is needed to enable the EV3 working with Open Roberta
- Open Roberta Image
- Open Roberta Starter Kit
- Open Roberta firmware update

**Comment by bjost2s** [comment]
This information is available in the help menu, do we need more?

**Comment by bjost2s** [comment]
As a preliminary solution a hint/link to the wiki while connecting the robot will do the job.
