### ISSUE TITLE
error massage Safari

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#250]
![or-massage_safari](https://cloud.githubusercontent.com/assets/19221359/18865225/61dc6e9c-849a-11e6-9dff-2865fa8ad371.png)

**Comment by bjost2s** [comment]
getUserMedia is not supported in Safari, 
only fix is to remove alert and write this to the console.

**Comment by bjost2s** [comment]
please close this, if it is fixed, because I don't have Safari to test.
