### ISSUE TITLE
Plugin structure to ease integration of new robots

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#253]
Goal:
if a new robot is integrated, this must be a simple process. Modification of generic code should not be necessary (every violation of this rule needs a good argument).

Todos:
- allow registration of new robots based on a configuration file
- allow robots to add new blocks and give developers the possibility to reuse existing code generators and to extend them

**Comment by bjost2s** [comment]
This works very well and makes it much easier to add new systems!

**Comment by bjost2s** [comment]
Last thing to do:
separate EV3lejos and EV3dev. Treating the both systems as two different robots plugins will make the workflow for developers and users! much easier to understand.

**Comment by bjost2s** [comment]
see #308
