### ISSUE TITLE
Wrong direction in OR Sim

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#256]
If the NEPO Blocks:  
- motor port B on speed X and 
- motor port C on Speed Y and 
- Wait ms Z - is used 
--> than the simulated robot moves backwards ;

**Comment by bjost2s** [comment]
generated sim code looks ok:
var stmt0 = createDebugAction();
var stmt1 = createMotorOnAction(createConstant(CONST.NUM_CONST, 30), CONST.MOTOR_RIGHT);
var stmt2 = createMotorOnAction(createConstant(CONST.NUM_CONST, 10), CONST.MOTOR_LEFT);
var stmt3 = createWaitTimeStmt(createConstant(CONST.NUM_CONST, 3000));
