### ISSUE TITLE
NXT US sensor values

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#257]
If the distance is too close the US sensor messures wrong valus >900

**Comment by Thorlogy** [comment]
Real robot

Am 05.10.2016 8:12 nachm. schrieb Beate Jost <notifications@github.com>:

real or simulated robot?
In sim it works fine for me

**Comment by bjost2s** [comment]
![image](https://cloud.githubusercontent.com/assets/1613069/19145546/b4c8baf4-8baf-11e6-8461-6bf2881aab80.png)
In this program the value shown on the display is between 5 and 255

**Comment by Thorlogy** [comment]
Your are absolutely right – show text + get distance needs the clear display block!

Von: Beate Jost [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. Oktober 2016 10:31
An: OpenRoberta/robertalab
Cc: Leimbach, Thorsten; Author
Betreff: Re: [OpenRoberta/robertalab] NXT US sensor values (#257)


[image]<https://cloud.githubusercontent.com/assets/1613069/19145546/b4c8baf4-8baf-11e6-8461-6bf2881aab80.png>
In this program the value shown on the display is between 5 and 255

**Comment by bjost2s** [comment]
nothing tho do
