### ISSUE TITLE
function variables are shown outside of the function

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#262]
The variable 'x' is local to the function 'incr'. Still I could select it outside of the function. Our code gen seems to be somewhat awer since we don't create a global var for x.

![screenshot from 2016-10-06 15 23 15](https://cloud.githubusercontent.com/assets/1279486/19153994/f2c9ec6e-8bd8-11e6-8193-a291446ddae8.png)

**Comment by bjost2s** [comment]
Have you tried to choose x?
![image](https://cloud.githubusercontent.com/assets/1613069/19156980/0853bb72-8be4-11e6-8bb7-ce88fb130195.png)
It will be marked as false.
