### ISSUE TITLE
Wrong transaltion - wenn_gebe_zurück

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#263]
In the function categorie: 
German translation "wenn ... gebe zurück" is wrong - right: "wenn ... gib zurück"

**Comment by bjost2s** [comment]
This is a translation from the blockly translators. If we overwrite this (it is possible) we will overwrite is again with the blockly translation if we sync again with blockly. Is it important?

**Comment by Thorlogy** [comment]
Then we should inform the blockly guys

Am 08.10.2016 12:06 nachm. schrieb Beate Jost <notifications@github.com>:

This is a translation from the blockly translators. If we overwrite this (it is possible) we will overwrite is again with the blockly translation if we sync again with blockly. Is it important?

**Comment by bjost2s** [comment]
could be fixed, problem with overwriting only exists in english translations
