### ISSUE TITLE
Too many sensors in Botnroll "wait until" block 

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#265]
![image](https://cloud.githubusercontent.com/assets/13983474/19190871/184c2c64-8ca0-11e6-90a7-781163250bc8.png)

There is no touch, ambient light color and gyroscope sensors. Instead of gyroscope there should be compass.

**Comment by bjost2s** [comment]
There is already a new block wait_for_ardu with the correct sensors for botn roll

**Comment by bjost2s** [comment]
fixed in 3a9274eccfd4fd97465298ede4a210663e6d848f
