### ISSUE TITLE
unify blocks between ev3 and sim

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#28]
As I a first step to make programs exchangeable between actual robot and simulator we need to offer the same blocks for the simulator.

I think it is okay to have some of the blocks to be dummies in the beginning.

What we're missing right now in the simulator according to the [doc](https://mp-devel.iais.fraunhofer.de/wiki/display/ORInfo/Programmieren+mit+NEPO#ProgrammierenmitNEPO-OpenRobertaSim)
- [ ] Actions
  - [x] screen - can be simulated as a panel on the web-ui
  - [ ] tones - can be done via web-audio
  - [x] leds - only missing flash/double flash
- [x] Sensors
  - [x] keys
  - [x] motor encoders - can be simulated (rotations are implemented, but not exposed)
  - [x] others (gyro, ...) - dummies?
- [x] Math
  - [x] operations on list
  - [x] increase variable values
- [x] List
- [ ] Function
  - [x] Void Function
  - [ ] Return Function

Simulated operations need to be implemented here:
https://github.com/OpenRoberta/robertalab/blob/develop/OpenRobertaServer/staticResources/simulation/simulationLogic/simulation.js#L190

**Comment by bjost2s** [comment]
done
