### ISSUE TITLE
Server Error: when in robot configuration wheel diameter with , instead of . is given

### ISSUE THREAD

**Issue by filipwoz** [OpenRoberta/robertalab#286]
When I put in robot configuration wheel diameter 3,6 and start the simulation a server error pop up appears
Better error handling or field content format validation would be good.

**Comment by bjost2s** [comment]
cannot reproduce the error
can you make a screenshot of the error message?
btw. the simulation doesn't care about configuration, it uses always the standard configuration.

**Comment by filipwoz** [comment]
Steps to reproduce in attachment
[Steps to reproduce.pdf](https://github.com/OpenRoberta/robertalab/files/591418/Steps.to.reproduce.pdf)

**Comment by bjost2s** [comment]
Thanks, the error is more or less the message. usually we ignore configuration modifications in the simulation

**Comment by cvejoski** [comment]
I was trying to reproduce the error following the instruction from @filipwoz  but everything was fine.

Can you please tell me @filipwoz which browser and OS have you used? After changing the values in the configuration for confirmation did you use the ENTER or TAB key or you just simply switch to another   tab?

**Comment by bjost2s** [comment]
@filipwoz please reopen you find a way to reproduce it
