### ISSUE TITLE
use webbluetooth to avoid the need for a helper program

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#287]
webbluetooth is shaping up. This would allow us to talk to bluetooth devices directly from the browser (js), without having an extra proxy.

Spec: https://webbluetoothcg.github.io/web-bluetooth/

Here is the current status: 
* http://caniuse.com/#search=webbluetooth
* https://www.chromestatus.com/feature/5264933985976320

Although when reading:
https://www.w3.org/community/web-bluetooth/web-bluetooth-community-group-charter/
they don't seem to plan to cover e.g. RFCOMM channels initially.

Having a full web-bluetooth stack could help e.g. #180,

**Comment by bjost2s** [comment]
Still only for chrome :-(
Any idea when or if other brothers will follow?

**Comment by ensonic** [comment]
Here is an example how people use webbluetooth with the Espruino microcontroller. 
http://www.espruino.com/Web+IDE

**Comment by rbudde** [comment]
not feasable at the moment
