### ISSUE TITLE
use webusb to avoid the need for a helper program

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#288]
webusb is a new api. This would allow us to talk to usb devices directly from the browser (js), without having an extra proxy.

Spec: https://wicg.github.io/webusb/

Here is the current status:
* https://www.chromestatus.com/feature/5651917954875392

Having a full web-usb stack could help e.g. #180,

**Comment by tuxlego** [comment]
This feature is very welcome, because I'm still struggling connecting our NXT via Linux.

**Comment by cvejoski** [comment]
@tuxlego did you build the USB program from the sources or did you install it as a package?

**Comment by tuxlego** [comment]
I've installed it from the Chrome Extension menu, Extension: Open Roberta 1.4.0
https://chrome.google.com/webstore/detail/open-roberta/pgdcbhlffbmoegkehoookdmghakdjieh?utm_source=chrome-app-launcher-info-dialog

**Comment by ensonic** [comment]
@tuxlego please create a new ticket for NXT and linux.

**Comment by rbudde** [comment]
not feasable at the moment
