### ISSUE TITLE
OR Stand-alone-server problem with USB connection and EV3

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#293]
We have recurring problems with the USB connection if we use the stand alone server. 
Within a 2 hour course the EV3 robot has to be reconnected 3 to 4 times. 

Reconnected means: 
- disconnect via USB program, 
- connect via USB program
- copy token
- and connect via OR Lab

**Comment by bjost2s** [comment]
to which ip do you connect to your server in the usb program?
on which system does this appear?

**Comment by dpyka** [comment]
By the way, the USB program stores a log file on your hard drive. I think on Windows it is somewhere in %APPDATA%. If you can provide the log file everytime you think the USB program did something wrong, we can investigate.

**Comment by Thorlogy** [comment]
We used the chrome app and a chrome book.

**Comment by bjost2s** [comment]
We have to check what are the differences to the usb program connection wich is working fine in this case

**Comment by bjost2s** [comment]
What exactly was the error message? Can you provide a screenshot?

**Comment by bjost2s** [comment]
@Thorlogy please reopen, if there is a way to reproduce this bug.
