### ISSUE TITLE
Lists: AddItem(itemvalue) / RemoveItemAt(position)

### ISSUE THREAD

**Issue by filipwoz** [OpenRoberta/robertalab#295]
It would be nice to have the following list functions available:
AddItem(itemvalue) adding a new item at the end of the list and returning the index of the new item
RemoveItemAt(position) removing an item from the given position of the list

**Comment by bjost2s** [comment]
If you select the expert toolbox, there are some list blocks available. 
![image](https://cloud.githubusercontent.com/assets/1613069/20295504/9ed61456-ab05-11e6-97af-8944916d8e45.png)

**Comment by filipwoz** [comment]
ok the "get sub-list from" can serve as RemoveItemAt workaround.
But AddItem cannot be implemented with the existing functions

**Comment by bjost2s** [comment]
![image](https://cloud.githubusercontent.com/assets/1613069/20480802/6dd90afa-afe4-11e6-8d96-caafee37c977.png)

Is this not working for you?

And what is the problem with this?
![image](https://cloud.githubusercontent.com/assets/1613069/20480845/98506166-afe4-11e6-9b98-23ed05929d81.png)

**Comment by filipwoz** [comment]
OK I did not know that there are such additional functions in the combo box. 
But these are existing only in the EV3 version. I would need them ported also on NXT.

**Comment by bjost2s** [comment]
Currently we do not support all of the list functions in NXT. The reason is that we have agreed to use the original lego firmware. With this firmware it is not possible to support more array functions like the EV3 does.

**Comment by bjost2s** [comment]
Please reopen if this is still an issue
