### ISSUE TITLE
OR I cannot login to my account and also cannot reset the password

### ISSUE THREAD

**Issue by filipwoz** [OpenRoberta/robertalab#298]
Guys, have you deleted my Open Roberta account? filipwoz

**Comment by filipwoz** [comment]
I have recreated my account. But all my programs which I saved in the cloud are lost. Please think over a migration procedure when you release a new version so that this does not happen again. At least all registered users should be notified to backup their programs locally.

**Comment by bjost2s** [comment]
We are very sorry for this. The reason is, as usual, a combination of unpredictable issues on our servers. Now we have made several arrangements that this should not happen anymore.
