### ISSUE TITLE
issue with xml codegen when using subroutines

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#300]
There seems to be an issue with the visitor how the function are traversed. In the attached example, if one of the function blocks is moved higher (y coordinate) than main, it is generated before main and this causes trouble with the python indentation.
[PropDerivAndTurn.xml.zip](https://github.com/OpenRoberta/robertalab/files/600362/PropDerivAndTurn.xml.zip)

**Comment by elhele** [comment]
Fixed with ae1b9e7
