### ISSUE TITLE
When running a local server, I'd like to change the default robot cfg

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#301]
When running an openroberta server, e.g. on the raspi, it would be nice to modify the default in the database. Maybe we can document the schema or have a script to modify the defaults. The specific case that was asked on the mailing list, was to change the default track-width.

**Comment by bjost2s** [comment]
See #181 
You can easily configure each toolbox and blockx in the robot specific properties in the robot projects

**Comment by bjost2s** [comment]
Please reopen if this is still an issue
