### ISSUE TITLE
Code using Bluetooth communication does not compile for NXT

### ISSUE THREAD

**Issue by filipwoz** [OpenRoberta/robertalab#304]
When I try to transfer the attached program to NXT (simple remote controlled 3 wheel model) I am getting an error that the program cannot be translated into the target machine code.
A similar program without using the Bluetooth blocks goes through.
[SpinneFernbedingung.zip](https://github.com/OpenRoberta/robertalab/files/606077/SpinneFernbedingung.zip)
[BluetoothNXT.pdf](https://github.com/OpenRoberta/robertalab/files/606078/BluetoothNXT.pdf)

**Comment by cvejoski** [comment]
fixed with 	0cb6709
