### ISSUE TITLE
Double semicolon in method calling inside conditional statements

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#311]
NXT: 

  macheEtwas();
  while ( true ) {
    macheEtwas();;
  }

EV3:

 if ( true ) {
            while ( true ) {
                macheEtwas();;
            }
        }
        hal.closeResources();
    }
        
    private void macheEtwas() {
    }

**Comment by elhele** [comment]
fixed with 96a13da

**Comment by ensonic** [comment]
@elhele are you sure the fix is correct. The test does not contain valid java code after the change, or did I misread it?

**Comment by elhele** [comment]
@ensonic The generated code seemed to be correct. I'll check if there is a problem with the test or code generation tomorrow.

**Comment by elhele** [comment]
@ensonic Yes, you were right, there was a bug. Fixed with 58ddfcc.

**Comment by ensonic** [comment]
Thanks!
