### ISSUE TITLE
ev3dev codegen: bad indentation when function comes before start

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab#320]
1. Create a program with a function up and left from the start block:
![image](https://cloud.githubusercontent.com/assets/632207/20828874/d963766e-b879-11e6-8253-8d4203879b3b.png)
1. Connect to an ev3dev robot.
1. Go edit -> show code.

The code in doSomething() is not indented properly:

```
def doSomething():
hal.setRegulatedMotorSpeed('B', 30)
def run():
    hal.setRegulatedMotorSpeed('B', 30)
```

Expected code:

```
def doSomething():
    hal.setRegulatedMotorSpeed('B', 30)
def run():
    hal.setRegulatedMotorSpeed('B', 30)
```

**Comment by cvejoski** [comment]
the issue is already reported in ticket #300
