### ISSUE TITLE
OpenRoberta Lab doesn't use shadow blocks

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab#323]
Blockly's shadow blocks let you have an easily editable parameter in a block by default, which can be replaced without removing the original block:

![blockly shadow blocks](https://cloud.githubusercontent.com/assets/632207/20829640/2f627684-b87d-11e6-9453-0b9fe812ef68.gif)

Some OpenRoberta blocks have no block by default, meaning you have to fill in both blocks every time you create it:

![image](https://cloud.githubusercontent.com/assets/632207/20829625/1db8fa2a-b87d-11e6-8112-06574bd9c4b7.png)

Others come with a normal block by default, which has to be deleted after being replaced:

![openroberta shadow blocks](https://cloud.githubusercontent.com/assets/632207/20829635/2bde5f28-b87d-11e6-8da9-abe56df0a291.gif)

It would be better if OpenRoberta used shadow blocks like Blockly.

**Comment by bjost2s** [comment]
We could use shadow blocks in some cases, but unfortunately not in all cases. E.g. if you declare a global variable with a list 
![image](https://cloud.githubusercontent.com/assets/1613069/20861865/dcc5879e-b99a-11e6-94e3-2a1cfc826c26.png)

you would expect the list block and the text blocks as shadow blocks. The version of blockly we are using doesn't support this. 
Another reason is  that blockly is using the same texture for shadow blocks that we are using for unreachable code.
