### ISSUE TITLE
Workspace jumps when you press play

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab#324]
1. Make a program that doesn't fit on the screen.
2. Scroll away from the start block.
3. Press play.

Observed behaviour: workspace jumps back to the start block.

![openroberta jump on play](https://cloud.githubusercontent.com/assets/632207/20830497/041b1220-b881-11e6-97e2-1c1e2463c6a3.gif)

Expected behaviour: workspace doesn't jump, you can keep editing what you were editing before.

**Comment by bjost2s** [comment]
seem to fixed, please reopen if it still appears.
