### ISSUE TITLE
DriveDirection.FOREWARD is spelled incorrectly

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab#325]
It should be DriveDirection.FORWARD.

https://github.com/OpenRoberta/robertalab/blob/028f32a363091d19536d412e0b154abe7351a913/OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/mode/action/DriveDirection.java#L8

**Comment by bjost2s** [comment]
If we fix this, old programs will not be executable anymore. It is not visible for the users, we will leave it as it is

**Comment by ensonic** [comment]
I think we should make the backends take both spellings for a transition period, then fix it and then remove the bad spelling.

**Comment by ensonic** [comment]
It shows up in the generated code though :/ In ev3dev I am checking for direction == "backwards", so there we could savely change it.
