### ISSUE TITLE
Text doesn't fit in fields after zooming

### ISSUE THREAD

**Issue by drigz** [OpenRoberta/robertalab#327]
I can't reproduce this any more (either on my Linux laptop or desktop), so this is not a high priority, but I'm filing it just in case.

I saw this several times during the IT-Gipfel on 16. and 17. November. I found that after zooming in/out with the touchpad scroll on the HP Chromebook 14 we were using, the text wouldn't fit in the boxes:

![screenshot 2016-11-17 at 8 06 18 am](https://cloud.githubusercontent.com/assets/632207/20830999/6a1b1d02-b883-11e6-9193-05deb159cbef.png)

Zooming further would make it normal again.

**Comment by bjost2s** [comment]
It seems to be a blockly issue, maybe fixed already there?
