### ISSUE TITLE
Variable names can be reserved words

### ISSUE THREAD

**Issue by maweki** [OpenRoberta/robertalab#329]
I can set variable names to reserved words in the OpenRobertaLab which leads to uncompilable code and no error message. I think there should be an exclamation-mark by the chosen variable name with an explanation.

![bildschirmfoto von 2016-12-06 10-44-00](https://cloud.githubusercontent.com/assets/613272/20920674/2d1af564-bba1-11e6-8b21-8be9d03691cd.png)

This should be a problem for all supported languages.

**Comment by bjost2s** [comment]
Unfortunately we allow in the blocks to use reserved words, but before the code compilation (not executed for show code) we check for reserved words and the user get a (not really helpful) message.
If we don't allow reserved words in blockly we should take into account, that the check will go over all programming languages used (currently java, python, c++, c) in the Open Roberta Lab, eg for EV3 also "def" won't be allowed.

**Comment by maweki** [comment]
I think it would be fine to have the union of the reserved words of all supported languages as not-allowed identifiers. Is this information we should hide (from a learning-perspective), that languages *do* indeed have reserved words that I am not allowed to use as identifiers?

**Comment by bjost2s** [comment]
We have now language list in blockly, where the variable and procedure names can be validated against.
TODO extend these list with names generated from us, that are not allowed.

**Comment by maweki** [comment]
The Python reserved word list is not correct. This is the python 2.7 list. MicroPython, which is running on the bbc micro bit is based on Python 3 which has different keywords.

https://docs.python.org/3.4/reference/lexical_analysis.html#keywords

 `False`, `None`, and `True` got promoted to keywords while `print` went from keyword to function.

**Comment by ensonic** [comment]
@maweki thanks for checking, could you send a PR with the fixes?

**Comment by maweki** [comment]
@ensonic sure. Just to make sure: Is the MicroPython target static or are there any other robots/implementations/interfaces in the works that might target 2.7 so that we'd want the union of both sets of keywords?

**Comment by ensonic** [comment]
@maweki: lego ev3 via ev3dev.org uses python3 as well

**Comment by maweki** [comment]
@ensonic I was just working on that and I saw that apparently the python that targets NAO is 2.6/2.7

http://doc.aldebaran.com/1-14/dev/python/install_guide.html#python-install-guide

Since python2 and python3 are in some ways different languages, would we have two sets of keywords for py2 and py3 respectively or have a union of both?

**Comment by ensonic** [comment]
Lets make it a union to play safe. I'll check if we can move nao to python3 as well.

**Comment by maweki** [comment]
Do we want to use this mechanism as well to solve #333 by pretending that the imports we use are keywords?

**Comment by JanisM91** [comment]
@ensonic The SDK for NAO only supports Python 2.6/2.7 and the python runtime on the robot is also 2.7. It is part of the NAOqi so we can not change the version to python3.

**Comment by maweki** [comment]
I added the keywords and split the imports and variable names that (i think) belong to ev3dev and added two more exceptions.
