### ISSUE TITLE
Drive in curve bug

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#330]
der Block „Steuere ...“ zeigt folgendes Fehlverhalten auf dem EV3-Brick (Simulation ist in Ordnung):

Wenn Tempo links invers zu Tempo rechts ist, der Roboter also auf der Stelle drehen soll, bleibt der EV3 ohne Reaktion. Wenn die Tempoangaben sich unterscheiden, also in der Summe von 0 verschieden sind, fährt der Roboter, allerdings nur in der Geschwindigkeit, die der Differenz beider Tempo-Angaben entspricht. Wenn ich 50 und -49 einstelle, dreht der Roboter mit Tempo 1.
 
![image](https://cloud.githubusercontent.com/assets/6226982/20928633/0eb010de-bbc7-11e6-95e0-48b6827c7286.png)

Im erweiterten Steuere-Block mit Streckenangabe ist fast das Gleiche zu beobachten. Wenn beide Tempo-Angaben invers sind (-30 und 30), dann zeigt der EV3 die Fehlermeldung „Error message: Zero arc radius“.

![image](https://cloud.githubusercontent.com/assets/6226982/20928643/1a1455e8-bbc7-11e6-88c1-ef4a924deb72.png)

**Comment by ensonic** [comment]
Both work fine on ev3dev.
