### ISSUE TITLE
Variable definitions are allowed to hide imports

### ISSUE THREAD

**Issue by maweki** [OpenRoberta/robertalab#333]
In languages that support it, variable definitions can possibly hide imports which leads to unexpected behaviour. Especially since the user does not know the names of the imports.

![bildschirmfoto von 2016-12-07 14-17-05](https://cloud.githubusercontent.com/assets/613272/20969109/de066980-bc87-11e6-934e-aa645dae4f2b.png)

In Python imported namespaces are just objects in the defining scope, which allows them to be redefined. One possible fix would be to use or build a wrapper that at least hides all the imports under one name.

```
from argparse import Namespace
import math
__imports = Namespace(math=math)
```

From here on `__imports.math` would be a reference to the import as well. This still allows hiding, of course.

In Java this is not a problem since imports aren't objects.

**Comment by bjost2s** [comment]
Further issues are handled in separate tickets, like #391
