### ISSUE TITLE
Variable definitions can be the names of existing variables

### ISSUE THREAD

**Issue by maweki** [OpenRoberta/robertalab#334]
This is similar to #333 but is specific to Java. I can define variables for my program that have names of already used variables in the class of the program, which makes the program uncompilable.

![bildschirmfoto von 2016-12-07 14-30-20](https://cloud.githubusercontent.com/assets/613272/20969643/362fb3e4-bc8a-11e6-952e-3d87b360f62a.png)

`main` and `run` are not a problem, since functions aren't objects, but I am not allowed to name a variable `hal`. This can either be solved by not allowing those names or maybe hiding this stuff (it's private anyway) in an abstract base class. This would lead (thanks Java) to multiple files for a program.

**Comment by bjost2s** [comment]
we should check the user defined names before generation own once.

**Comment by bjost2s** [comment]
I think we fixed it with #333?
If so, please close this issue.

**Comment by maweki** [comment]
We kinda did for python. We have to recheck all imports across the board whether we're hiding anything.
