### ISSUE TITLE
calliope sim "clear display" block not handled?

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#341]
when running this I get the heart when I click the button in the simulation, but the image is not cleared when I release the button.

![screenshot from 2016-12-21 10 49 53](https://cloud.githubusercontent.com/assets/1279486/21384587/713a1f60-c76b-11e6-8b94-21f2eafbd1e5.png)

If I tweak the code to be like below, I can see that the beep stops when I release the button, but the image stays:
![screenshot from 2016-12-21 10 53 19](https://cloud.githubusercontent.com/assets/1279486/21384680/cfbedbde-c76b-11e6-9f55-17321bf6e9b8.png)

**Comment by bjost2s** [comment]
seems to be just a forgotten implementation ;)
