### ISSUE TITLE
calliope sim "images" block has some icon mixups

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#342]
at least one of the images is wrong. When selecting the "smile", I get the same as the last image in the list.

![screenshot from 2016-12-21 11 00 40](https://cloud.githubusercontent.com/assets/1279486/21384927/beea7448-c76c-11e6-8287-3b72cabd76ea.png)

**Comment by bjost2s** [comment]
same bug for microbit

**Comment by bjost2s** [comment]
smile is still wrong
