### ISSUE TITLE
BOB3 Integration

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#345]
BOB3 is a small programmable board, like mirco:bit or calliope, based on an arduino
http://www.bob3.org/

 - [x] BOB3  code generation
 - [x] BOB3 compiler workflow
 - [x] BOB3 GUI blocks and toolbox
 - [ ] BOB3 Adopt simulation 
 - [x] BOB3 adopt USB program (using Create Agent) #492

arduino libraries are available

**Comment by VinArt** [comment]
An icon is needed for Bob3 menu items and start screen.

**Comment by VinArt** [comment]
@bjost2s 52b9b00d010d2bb41a5b5511771bb000657667e6 gives an exception de.fhg.iais.roberta.util.dbc.DbcException: There was no correct configuration block found! robControls_loopForever_ardu

If I change it to the robBrick_EV3-Brick that I understand is wrong, there are no exceptions...

**Comment by bjost2s** [comment]
Please do not close this ticket before it is labeled as resolved

**Comment by bjost2s** [comment]
Please check, if it is possible to instantiated the timer only when the timer is used in the wait-for block

**Comment by bjost2s** [comment]
GUI is logging every second (or two) list success in comm.js function listRobotsFromAgent
although I switched to EV3lejos!
![image](https://user-images.githubusercontent.com/1613069/30828248-51a3e7c8-a23d-11e7-952d-48bd698bbaba.png)
