### ISSUE TITLE
NAO brick configuration

### ISSUE THREAD

**Issue by JanisM91** [OpenRoberta/robertalab#347]
The NAO is not modular. Therefore neither actors nor sensors need to be added to the configuration.

Add a picture for the configuration tab and use it as a information tab.

**Comment by bjost2s** [comment]
The configuration in general is there to make sure the program "knows" what sensors and actors are plugged in at which port. For NAO we cannot exchange sensors or actors, or?

**Comment by JanisM91** [comment]
It is not possible to exchange sensors or actors for NAO.
Do you recommend to use it to inform about the sensors and actors with a picture or would you prefer to make a Block and add undeletable Blocks that represent the sensors and actors?
I attached two examples out of the NAO documentation to this comment.

![](http://doc.aldebaran.com/2-1/_images/nao_h25_pres.png)

![](http://doc.aldebaran.com/2-1/_images/hardware_motortype_h25V5.png)
