### ISSUE TITLE
Provide connection program

### ISSUE THREAD

**Issue by JanisM91** [OpenRoberta/robertalab#350]
A program that initiates the connection between NAO and the Open Roberta Lab is needed. Maybe a program is needed to send a file to the robot to establish the connection.

Development takes place in the github/OpenRoberta/robertalab-nao repository.

A program to transfer a file to a NAO robot and execute it is already available in the mentioned repository.
It needs a GUI in the style of the usb-program.

A python 2.7 implementation of the Robot Server Protocol (http long polling) as described in the wiki is implemented. This code runs on the robot and provides the connection but has some flaws due to the restrictions of NAOs body.

**Comment by bjost2s** [comment]
Please demonstrate it, before closing
