### ISSUE TITLE
Calliope - display sensor data at Simulator

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#353]
Within the calliope simulator the compass text has a star* maybe a bug

Using firefox browser

![or_cal2](https://cloud.githubusercontent.com/assets/19221359/21716696/4e10d238-d40c-11e6-986a-cb2ae0ef1752.png)

**Comment by bjost2s** [comment]
This is a circle (degree).

All sensor data is temporarily removed form simulation until we have a better representation of this.

**Comment by ensonic** [comment]
It would be better to have the units behind the values. That is:

Label | Value
-------|-------
Time | 11.12s
Compass | 0°
Temperature | 25°C

**Comment by bjost2s** [comment]
please check out the test server or the develop branch and comment
