### ISSUE TITLE
split ev3 plugin into ev3@lejos and ev3@ev3dev

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#363]
The ev3 plugin currently switches the code generator once a robot is connected. For lejos we generate java and for ev3dev we generate python. This is not optimal, since we generate java by default (see #24).

Also ev3dev has some extra features that we'd like to expose in the blocks (dimmable leds and a speech synth).

**Comment by bjost2s** [comment]
do you mean #308?
