### ISSUE TITLE
Add a background picture for NAO

### ISSUE THREAD

**Issue by JanisM91** [OpenRoberta/robertalab#365]
Examples for background picture:

![](http://doc.aldebaran.com/2-1/_images/doc_naoqi_nao.jpg)

![](http://doc.aldebaran.com/2-1/_images/battery_step1.png)

![](http://doc.aldebaran.com/2-1/_images/nao_pose_secu_face_3_4.png)

**Comment by bjost2s** [comment]
Please attach one or two good ones to this ticket and I will forward it.
