### ISSUE TITLE
Block show picture in EV3 is neither evaluating x nor y values

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#370]
![image](https://cloud.githubusercontent.com/assets/1613069/22252747/7ecbd250-e24f-11e6-8b85-3ba906c72731.png)

We should discuss what to do
-  remove input fieds x and y
-  implement x and y (shifting the image)

**Comment by bjost2s** [comment]
we decided to remove the input fields.
If we once have new block for custom pictures it probably will make sence to offer them there, because it will then be possible to show smaller pictures.

**Comment by bjost2s** [comment]
Removing seems to be difficult, because old programs causes problems: x and y math blocks cannot connect to show block.

**Comment by bjost2s** [comment]
ORA-2.2.1 will not have an update for the EV3, so moved to ORA-2.3.0

**Comment by bjost2s** [comment]
We will create a new block without x and y that will substitude the old one. For backwards compatibility the old one will still work and create code, but it won't be available in the toolbox anymore.

**Comment by bjost2s** [comment]
fixed here b5c59970d02c69353fa9cfb337cba86c648a8da6 applied wrong ticket number #307

**Comment by ensonic** [comment]
Tested on the ev3dev:
- import old program into the git HEAD version: okay
- use the new block without x/y in the HEAD version: okay
