### ISSUE TITLE
Calliope - Compiling (sometimes) fails when using timer

### ISSUE THREAD

**Issue by larspelz** [OpenRoberta/robertalab#391]
There seems to be problem using the timer sensor block in NEPO in Calliope mode. Some of my programs using it can't be compiled.
Here is a basic test using only one line of code which yields an error:
[NEPO-calliope-compile-fails-timer-simple-output.zip](https://github.com/OpenRoberta/robertalab/files/761399/NEPO-calliope-compile-fails-timer-simple-output.zip)

Another test using a variable to buffer the timer value doesn't work either:
[NEPO-calliope-compile-fails-timer-test.zip](https://github.com/OpenRoberta/robertalab/files/761407/NEPO-calliope-compile-fails-timer-test.zip)

However, this more complex program always compiles, although the blocks from the broken demos are used as well (timer reset, get timer value):
[left-right-trainer-points-working.zip](https://github.com/OpenRoberta/robertalab/files/761411/left-right-trainer-points-working.zip)

**Comment by cvejoski** [comment]
This is because get timer value is returning `unsigned long int` and showing  number of type `unsigned long int` is not supported by Calliope yet.

We work on this problem.
