### ISSUE TITLE
Support for custom sensor/actor blocks

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#392]
Many robots support a large variety of hardware addons. Even robots like the LEGO MINDSTORMS® EV3 can be used with 3rd party sensors and actuators. In this project the student would design a system that lets the user create new blocks to support additional hardware.

Initially such blocks would be stored with the project. A better way would be to store them in the user's account (if logged in). A stretch goal would be to add support for contributing/sharing blocks.

On the technical side, the project involves: code generators for the new blocks (maybe based on some template) a way to include custom library code (e.g. on the Arduino side)

Mentor: Stefan

**Comment by rbudde** [comment]
see the wiki page "projects"
