### ISSUE TITLE
Beim Setzen des Farbsensors (Statusleuchte) werden drei Farbwerte angeboten, rot, grün und blue. Es sollte im deutschen blau heißen.

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#398]
![image](https://cloud.githubusercontent.com/assets/1613069/22853439/8e33fadc-f056-11e6-8b51-6cbdff2a453e.png)
by J.

**Comment by JanisM91** [comment]
This is not NXT exclusive. The LED Block for NAO has the same bug.
![led_bug](https://cloud.githubusercontent.com/assets/22591228/23542781/4f9e3bfe-ffef-11e6-85f2-75b97311fa2e.PNG)

**Comment by JanisM91** [comment]
fixed with 0333ea2
