### ISSUE TITLE
'Run on simulation' not working with Chrome

### ISSUE THREAD

**Issue by alesolano** [OpenRoberta/robertalab#402]
In the last two days I have been unable to 'Run on simulation' using Chrome. The map just stays blank and the web page freezes.
![image](https://cloud.githubusercontent.com/assets/17273316/22883781/155758a0-f1f2-11e6-9f0c-539e19bd1667.png)
It works properly with Internet Explorer. I have not tried more web browsers.

**Comment by cvejoski** [comment]
Probably you have problem with the cache. Can you please empty the cache and then try again.

**Comment by alesolano** [comment]
It works! Thanks for the quick response!
