### ISSUE TITLE
Open Roberta Sim - reposition Robot 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#405]
As a user i would like to repostion the robot, so that i can test my program on exactly the same position.

Now i have to close the sim window and reopen it.

**Comment by bjost2s** [comment]
The only way that I see here is to add another button in the simulation to reset the robot. 
![image](https://cloud.githubusercontent.com/assets/1613069/23153007/46b0d092-f806-11e6-9313-011f679eabfb.png)
