### ISSUE TITLE
How to use sayText (ev3dev)

### ISSUE THREAD

**Issue by bidaian** [OpenRoberta/robertalab#407]
Is there a way to use the text-to-speech function found in ev3dev? I can see the [code](https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L266) but don't know how to make it work from labs.open-roberta.org.

**Comment by ensonic** [comment]
Not yet. I just started to prepare adding this for ev3dev. I am trying to add this to lejos as well and we need blocks on the roberta server side.

**Comment by bjost2s** [comment]
see #425
