### ISSUE TITLE
Variable Handling?

### ISSUE THREAD

**Issue by ScottMcl** [OpenRoberta/robertalab#408]
Wondering if the variable "item" in the attached program is being handled correctly.

Thanks.
[TextVariable.zip](https://github.com/OpenRoberta/robertalab/files/791356/TextVariable.zip)

**Comment by ScottMcl** [comment]
Oh.... I see a post below mine about the simulator being unable to break out of a loop. Perhaps this is why my program doesn't stop.

**Comment by ScottMcl** [comment]
I'll test it with a brick later today.

**Comment by ScottMcl** [comment]
Yes, the program fails to break out of the loop with the simulator but works fine with the brick.

**Comment by cvejoski** [comment]
We have bug in the break statement for the simulation. Currently we work on the bug and for the next release probably it will be fixed.

**Comment by alesolano** [comment]
Same problem as #406 

Should I close the other issue?

**Comment by cvejoski** [comment]
Yes you can close it.
