### ISSUE TITLE
Support CodeBugs (similar to MicroBit/Calliope)

### ISSUE THREAD

**Issue by tcriess** [OpenRoberta/robertalab#409]
Hi,
I'd love to see support for the CodeBug (http://www.codebug.org.uk - it is actually quite similar to the MicroBit and the Calliope) in OpenRoberta. Unfortunately, the CodeBug specs are afaik not fully open (yet?).

**Comment by bjost2s** [comment]
hi, thank you, I also think it is an interesting project. I will try to get in contact with them.
