### ISSUE TITLE
New blocks for calliope / microbit

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#410]
- [x] get pixel (led from matrix)
- [x] set pixel
- [x] get brightness of display
- [x] set brightness of display
- [x] support for groove connectors, A0 seems to be P19, old and new
- [x] getOrientationAngle({x,y,z})
- [x] getAcceleration({x,y,z})
- [x] shiftImage
- [x] invertImage
- [x] microphone sensor

**Comment by larspelz** [comment]
I hope it's not too late to say...
I'd really like to see a more low-level access to the accelerometer, something like the PXT has:
`getOrientationAngle({x,y,z})`
`getAcceleration({x,y,z})`
In beginner mode, `getAcceleration()` would be nice, giving just the resultant of the three vectors.
Should I create a new issue for this idea?

**Comment by cvejoski** [comment]
No, I think we modify this ticket

**Comment by larspelz** [comment]
Cool, thanks a lot!

**Comment by bjost2s** [comment]
getAcceleration() seems to be similar to the gesture event 3g,6g,8g (also not implemented yet ;-) but maybe it is easier for kids to understand the function of this sensor in general?

**Comment by larspelz** [comment]
`getAcceleration()` should deliver a number, whereas the gesture events deliver boolean values as far as I can see.
The way `gesture ... active?` is implemented neatly gives students a basic understanding of what can be achieved with the sensor. But for more complicated projects, e.g. a bicycle acceleration meter or water rocket flight timer (very enthusiastic, but feasible!), access to the sensor's raw readings would be appreciated I think.
