### ISSUE TITLE
Please provide IRC or gitter info

### ISSUE THREAD

**Issue by Krashcan** [OpenRoberta/robertalab#412]
There is no way a student can contact the developer-team to get started with contributing . Please provide gitter or irc where the discussions can take place.

**Comment by cvejoski** [comment]
you can join the irc channel **open-roberta**

**Comment by bjost2s** [comment]
We offer several ways of communication. Please read 
https://github.com/OpenRoberta/robertalab/wiki/Community

**Comment by Krashcan** [comment]
I went to the irc channel. There weren't many people active there. I wish to start contributing to the project and be a part of GSoC'17 if we do get selected. I have setup the project locally. Any suggestion on which issue I should start from?

**Comment by cvejoski** [comment]
During the weekends there are not many people active on the IRC channel. Regarding on which issue to start working that depends on you, any preferences client or server side?

**Comment by Krashcan** [comment]
I prefer server side

**Comment by Krashcan** [comment]
I can try to solve both , client and server side issues.
