### ISSUE TITLE
for loop cannot be used to count down

### ISSUE THREAD

**Issue by larspelz** [OpenRoberta/robertalab#413]
In a for loop (expert blocks), the "<" operator will always be used in the condition statement, even if the start count is larger than the end count. Thus, for loops that count down will never execute their loop body, as their condition always yields false.
I created an example to show the problem for the Calliope platform, but I noticed that the problem will persist when using other platforms, too.
[nepo-calliope-for-loop-no-downcount.zip](https://github.com/OpenRoberta/robertalab/files/800428/nepo-calliope-for-loop-no-downcount.zip)

**Comment by Krashcan** [comment]
Can I work on this issue?

**Comment by bjost2s** [comment]
Yes please! Please send a pull request against develop, if you have a solution or maybe we can have a look at it in your fork and give you some feedback

**Comment by bjost2s** [comment]
Feel free to ask, if you need help

**Comment by Krashcan** [comment]
I am trying to understand the source code. Can you direct me once? I am looking for the folder where we have code for generating source code from blocks. I might find it if I continue looking around but it is my first time contributing to such a huge project and I am kind of lost. Any hint would help.

**Comment by Krashcan** [comment]
Okay, I got it. Its under robertalab\OpenRobertaRobot\src\main\java\de\fhg\iais\roberta\syntax\codegen . Working on the issue.

**Comment by Krashcan** [comment]
I have made my changes locally. Do I need to re-run mvn clean install? But it takes time, what should I do next to check if my changes work as expected locally?

**Comment by cvejoski** [comment]
If you run the server using the _ora.sh_ script you should build the project again. You can use _mvn clean install -DskipTests_ and it will be faster since the test won't be executed. 

If you run the server using eclipse then you don't have to build the project.

You can create program in Blockly and see the generated source code.

**Comment by Krashcan** [comment]
I have made a pull request.

**Comment by bjost2s** [comment]
Thank you. Maybe we could improve this and provide a more generic solution. The current solution is only working, if the summand is not an expression or a function. We could have a look in how blockly is doing it for variables eg.
![image](https://cloud.githubusercontent.com/assets/1613069/23481421/8daf4836-fecb-11e6-9245-15535fd4f876.png)
https://blockly-demo.appspot.com/static/demos/code/index.html
