### ISSUE TITLE
one needs to select "new" twice to discard a program

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#42]
When I select "new" from the menu I get the:

'''
Attention
You have unsaved changes in your program or configuration. Sign in and save your program or configuration.
'''
warning with an "ok" button. When I click "ok"  the code is still there. I then have to select "new" from the menu again and the code is discarded without warning. Here is the code for it:

https://github.com/OpenRoberta/robertalab/blob/develop/OpenRobertaServer/staticResources/roberta/roberta.js#L387-L409

I think the dialog should have two buttons "delete code" and "cancel", where "delete code" will proceed and "cancel" will get me back to the code. Right now it seems we only have message dialogs there :/

**Comment by bjost2s** [comment]
This should be fixed for switching from one robot system to another robot system. Switching from robot to simulation is no longer needed. We do not have a second robot in 1.4 but we should implement that as if we have one, to have the gui prepared for many robot systems.

**Comment by ensonic** [comment]
This is not related to robot switching.

**Comment by bjost2s** [comment]
done
