### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#424]
Menu (and Welcome-Screen): Roboter-Vorbereiten: https://mp-devel.iais.fraunhofer.de/wiki/display/ORInfo/Vorbereitung

Welcome-Screen: Bauanleitung: https://mp-devel.iais.fraunhofer.de/wiki/display/ORInfo/Vorbereitung#Vorbereitung-Bauanleitung

**Comment by bjost2s** [comment]
should be reopened, if the wiki is moving to a new server
