### ISSUE TITLE
when switching to the simulator the robot is not disconnected

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#43]
Repro:
* start as ev3
* pair the ev3
* switch to sim
* note: the robot is still connected (on the robot side)
* switch  back to ev3
* the robot is still connected, but the ui shows it as disconnected
* when I reconnect the robot with the same token I get an exception:
https://gist.github.com/ensonic/fecbd222f41fc7530bbb

I have a fix:
https://gist.github.com/ensonic/245f7171f11eb7a5f970

But I wonder, once the simulator matches the real robot, wouldn't be better to retain the connection instead. This way you can switch back and forth without having to reconnect. Additionally I wonder what we want to do once we support multiple robots. I think constraining to one robot that can be connected to one session at a time makes things easier.

**Comment by ensonic** [comment]
Once the simulator matches the real robot, the question is if it wouldn't be better to retain the connection instead. This way you can switch back and forth without having to reconnect.

**Comment by bjost2s** [comment]
Should be fixed with #29. I think right now the connection is still there, but the gui is ignoring the robots server state. If we remove the switching from robot to simulation anyway this problem shouldn't appear anymore.

**Comment by ensonic** [comment]
We need to remember to revert my change then.

**Comment by bjost2s** [comment]
We will need it, if one switch from one robot system to another, because then disconnecting is reqested.

**Comment by bjost2s** [comment]
from my understanding this is done, please reopen, if not
