### ISSUE TITLE
NAO - Charset for String Blocks

### ISSUE THREAD

**Issue by fgras-erm** [OpenRoberta/robertalab#434]
Hi,

When I entry a text with accent _(é è ç à ï ...)_ in String Bock, the generated python code replace the text with a empty string.

NAOqi use UTF-8.

Regards,
fgras-erm

**Comment by JanisM91** [comment]
I tried to entry a small letter a with grave into the String block. For me it is not replaced by an empy string but with the corresponding unicode.

![unicode](https://cloud.githubusercontent.com/assets/22591228/23752649/8286f240-04d6-11e7-8698-7da6c74216cf.PNG)

**Comment by fgras-erm** [comment]
Hi,

Indeed, the first time I tested, I had the same thing than you.
The second test, I had nothing, maybe it's because I wasn't on the good version or on good server.


Nao works on Python 2.7.  My version, on Windows, doesn't support "\u00E0" _(I'm out of NAO this week, but I rather am sure it's the same on and in NAO)_
NAOqi 2.1.4 doesn't support unicode. Consequently, the communication with NAO must be in str in utf8, it should be either 
`self.tts.say("\xC3\cA0")`
or
`self.tts.say( u"à".encode('utf8') )`


Regards
fgras

**Comment by JanisM91** [comment]
The special characters in the strings are converted on the server. Therefore the unicode the server generates is converted to a proper utf-8 string in the hal.
