### ISSUE TITLE
NAO - hal.py - setLeds intensity

### ISSUE THREAD

**Issue by fgras-erm** [OpenRoberta/robertalab#436]
Hi,
In setLeds(), the function self.led.setIntensity() put all leds in white with a intensity. So, in hal.py, it's impossible to put a red, a dark green or a light blue color.

I propose :
 - either you keep intensity parameter but it applies a ratio on the color
 - or you replace the combox with a "Color Blocks" with at least 24 choices of color

Regards,
fgras-erm

**Comment by JanisM91** [comment]
Hi,

i think it is best to remove the intensity and change the block so that the color is not a dropdown field but a color value. This way it is possible to add a predefined color block or to use a rgb block.

Regards
Janis

**Comment by JanisM91** [comment]
Blocks now look like this:
![lightblocks](https://cloud.githubusercontent.com/assets/22591228/23794374/16f081ee-0590-11e7-8042-77a5ca1dee2a.PNG)
In addition to the color picker it is also possible to use a RGB Block that takes a variable number for each channel (red,green,blue).

**Comment by fgras-erm** [comment]
OK, it's a better idea than I thought.
I let you close this ticket when it's done and tested?

Regards,
fgras

**Comment by JanisM91** [comment]
fixed with 5772445 and 2e417e6
