### ISSUE TITLE
NAO - hal.py - Set Mode Block

### ISSUE THREAD

**Issue by fgras-erm** [OpenRoberta/robertalab#437]
Hi,

In the hal.py, set mode ("rest") means sit down. Sit down isn't a rest position.

I propose :
1) separate Sit and Rest. It's two differents states and moves for NAO
`self.motion.rest()`

2) reduce the motor speed to 0.8. It's that manufacturer do in his programs

Regards,
fgras-erm

**Comment by JanisM91** [comment]
Hi,

it is a nice idea to separate Sit and Rest. I will make Sit available as another variable for the set mode block and reduce the motor speed.

Regards,
Janis

**Comment by JanisM91** [comment]
added with 80e07a6 and OpenRoberta/robertalab-naoprogram@24ce1d8
