### ISSUE TITLE
NAO - hal.py - case in fsr and  touchsensors function

### ISSUE THREAD

**Issue by fgras-erm** [OpenRoberta/robertalab#438]
Hi,

For parameters of **fsr** or **touchsensors** functions, the generated python code create string with the first letter in upper.
In the hal.py, all is wrote in lowercase.

Furthermore, for head touchsensors, "position" variable is tested with "Front", "Middle" and "Rear" values, when it's "side" variable which have this values.

Regards,
fgras-erm

**Comment by JanisM91** [comment]
Hi,

the difference in the capitalization was fixed with 32f3b37.

I will have a look into the variables for the touchsensors.

**Comment by fgras-erm** [comment]
Hi,
The variables was already fixed too. Good job!

Do it miss a `return False` at the end?

Regards,
fgras

**Comment by JanisM91** [comment]
`return False` added with OpenRoberta/robertalab-naoprogram@b2a9bdb

**Comment by fgras-erm** [comment]
great!
