### ISSUE TITLE
detect/check robot configuration

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#44]
Right now we leave robot configuration to the user. If the session is connected to an ev3, we could actually send connection data along with each push request (there already is a "configuration" entry in the protocol for this already).
Now the question is how can me make use of that in the UI.
1. we could add a "check" button that is the counterpart of the "check" button in the program tab. This would flag out-dated configuration entries.
2. we could have an auto-update checkbox. Then the configuration will auto update to reflect the latest config we got via push.

Once we figured that, I'd love to show the current sensor values / motor positions in the configuration too.

**Comment by dpyka** [comment]
I prefer option 2 with auto-update by default. But we also have to make the brick configuration more visible to the user.

**Comment by bjost2s** [comment]
option two is also for me a good solution

**Comment by VinArt** [comment]
Does not work for all robots, e.g. Arduino.
