### ISSUE TITLE
New startscreen

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#444]
![or_startscreen_release_2_3_schritt1](https://cloud.githubusercontent.com/assets/1613069/23996168/b46ef5b6-0a4c-11e7-8d10-97a680a110fa.jpg)
![or_startscreen_release_2_3_schritt2](https://cloud.githubusercontent.com/assets/1613069/23996170/b58d7954-0a4c-11e7-85df-29728410f84a.jpg)

**Comment by ensonic** [comment]
Looks awesome. Only concern is the 'back' ('zurück') button. Maybe change the title on the 2nd screen to "Wähle dein Calliope (zurück zur Auswahl)".

**Comment by bjost2s** [comment]
@ensonic, could you please attache an image of the menu from ev3dev, so that we can distinguish the two ev3 systems by the menu layout?

**Comment by ensonic** [comment]
@bjost2s I have images here:
https://github.com/OpenRoberta/robertalab-ev3dev

**Comment by bjost2s** [comment]
Thanks
