### ISSUE TITLE
Detect unused messages in robMessages.js

### ISSUE THREAD

**Issue by lauBudde** [OpenRoberta/robertalab#447]
To avoid useless work, all messages, that are not used (anymore), should be detected and removed.

**Comment by rbudde** [comment]
sorry. Assigned gregorsamsa183 erroneously.

**Comment by bjost2s** [comment]
I could delete 47 messages! I fixed some and added some ;-). 
This is the only one that should stay, because we simply forgot to implement it(almost everywhere) 
VARIABLES_TYPE_ARRAY_COLOUR
A ticket for this will follow!
