### ISSUE TITLE
Edge Save Target As not working

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#449]
For all the embed systems downloading the hex code using _save target as_ is not working. The save dialog is not opened.

**Comment by bjost2s** [comment]
seems to be an issue of edge
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4282810/
someone pointed out, that there is a limitation of 2000 chars limitation

**Comment by bjost2s** [comment]
Think we cannot limit the hex file

**Comment by cvejoski** [comment]
No, we cannot :). Maybe we should have alternative way of downloading the hex on Edge

**Comment by bjost2s** [comment]
If you download it directly, (accepted once the hint that you have changed your download folder) it will work
![image](https://cloud.githubusercontent.com/assets/1613069/24143242/5b32ab06-0e29-11e7-81d0-cb413fa1b25b.png)
so I will check for edge and treeted it as accepted download folder

**Comment by bjost2s** [comment]
And I will take this into account
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7260192/
:-(

**Comment by bjost2s** [comment]
fix is only a workaround, we should think about putting the browser and/or device system into the GUI state to react in general more specificly
