### ISSUE TITLE
microbit: "get value ambient light" has no code representation

### ISSUE THREAD

**Issue by larspelz** [OpenRoberta/robertalab#451]
Hey @all!

When I use the block "get value ambient light" in the microbit version of NEPO, no code will be generated for the block. The program can be downloaded but yields a syntax error message on the microbit.

Greetings - Lars Pelz

**Comment by cvejoski** [comment]
micropython microbit does not provide "ambient light", therefore there is no implementation in NEPO.

Probably we have to remove this block from the toolbox.

**Comment by bjost2s** [comment]
There is already a ticket for this here https://github.com/bbcmicrobit/micropython/issues/248, but I don't think that they are working on it.

**Comment by larspelz** [comment]
So currently there is no way to retrieve the light sensor's value of the microbit in NEPO?

**Comment by bjost2s** [comment]
We will check micropython and add it back, if it it is available
