### ISSUE TITLE
support for HiTechnic NXT Color Sensor V2

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#454]
reported by a user

**Comment by bjost2s** [comment]
seems to be supported by nxc already. I will provide a block for the configuration.

**Comment by elhele** [comment]
We would have to add mapping of a simple color sensor colors: 
1 = black
2 = blue
3 = green
4 = yellow
5 = red
6 = white
to HiTechnic NXT Color Sensor:
0 = black
2 = blue
4 = green
6 - yellow
8 = red
17 = white

It should be possible to obtain ambient light using SetSensorType(port, SENSOR_TYPE_LIGHT_INACTIVE)
