### ISSUE TITLE
Missing translation - Calliope picture - ger

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#472]
![or_2-2-2_shift_de](https://cloud.githubusercontent.com/assets/19221359/24788671/173d1186-1b6f-11e7-88b4-430ac6e0a209.png)

invert : umkehren, umdrehen, invertieren, umstellen, umwenden, auf den Kopf stellen
is not translated into German

also shift and up/down/right/left are not transalted into German

**Comment by bjost2s** [comment]
Should we use arrows for the dropdown?
￩ ￪ ￫ ￬
