### ISSUE TITLE
Missing translation - Save/load program

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#478]
German language selcted

![image](https://cloud.githubusercontent.com/assets/19221359/25222369/91ca6536-25b8-11e7-83a1-ae5e20eb3c8c.png)

Still english: Showing 1 to 1 of 1 rows

Also the mouse over tooltip (First button right hand corner) is not translated: Hide/show pagination

**Comment by bjost2s** [comment]
see #475, already fixed
