### ISSUE TITLE
Calliope 2016/2017: Microphone block yields value ~520

### ISSUE THREAD

**Issue by larspelz** [OpenRoberta/robertalab#487]
Hi openroberta team!

I tried the microphone block (see screenshot below) but I'm only getting a constant value around 520. I tried both Calliope versions, which behaved the same. Thanks in advance for looking into this problem!

![grafik](https://cloud.githubusercontent.com/assets/12141354/25615906/1485ff64-2f3a-11e7-8458-7cdde86e39dc.png)

**Comment by cvejoski** [comment]
This is a bug in Calliope firmware as soon as they fix it we will update the firmware

**Comment by bjost2s** [comment]
see https://calliope-mini.myjetbrains.com/youtrack/issue/MINI-51

**Comment by bjost2s** [comment]
in version 2.2.7 we map the output from the calliope to 0-100, so old  hardware version will get a value between 0-10 and newer versions 0-100 (not testet, no device available :-() to simply messure the volume.

**Comment by larspelz** [comment]
I tested it and can confirm it's working. Thanks for fixing!
