### ISSUE TITLE
Layout problems - Android Smartphone

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#488]
It seems like a layout issue:

![responsive_bug_or-lab](https://cloud.githubusercontent.com/assets/19221359/25692855/e1e82c5e-30a5-11e7-853c-1de0fd96d757.png)

Android Nexus 5 Chrome 
LCD, 4,95″ Diagonale
1920 × 1080 Pixel, 445 ppi

**Comment by cvejoski** [comment]
This is probably handled by the bootstrap library. One solution is to check out the new bootstrap version and see if it is fixed.
