### ISSUE TITLE
Calliope language changes to BUTTON_A after activation SIM

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#490]
![image](https://cloud.githubusercontent.com/assets/19221359/25818737/f155a4d0-342b-11e7-8185-73cedca1b10d.png)

With Calliope 16 and 17

**Comment by larspelz** [comment]
Oh, I thought that had gone away. I can confim it still exists...

**Comment by bjost2s** [comment]
The bug is new in 2.2.3 ;-), but already fixed for 2.2.4+
Waiting for compass fix in calliope to set it online
