### ISSUE TITLE
Direct Link/URL 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#498]
As a teacher I would like to use a "direct Link/URL" to programm a specific System with Open Roberta Lab e.g. lab.open-roberta.org/calliope17 lab.open-roberta.org/EV3 ...

**Comment by bjost2s** [comment]
needs to split the first popup into two, because of legals, that has to show up anyway.

**Comment by bjost2s** [comment]
Still thinking about this. Now the user has to click on the right robot system. If we offer a direct link the user has to confirm the popup without choosing a system, but still he has to click something. Is it still worth to be implemented?

**Comment by rbudde** [comment]
will be done (implicitly) when we remove all cookies from the lab
