### ISSUE TITLE
EV3 RobotKonfiguration extension 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#505]
As a teacher i would like to configurate a parameter "friction" within the RobotKonfiguration.

So far i only can change the track width (or wheel parameter) to react on different friction.

**Comment by ensonic** [comment]
How would one determine the friction between the wheels and the material?

How would this be applied to motor blocks? Right now our speed is set as % and not as e.g. m/s.

With regard to the design, this would be a factor >= 1.0.

**Comment by bjost2s** [comment]
move this again out of won't fix because we need more discussion
