### ISSUE TITLE
Calliope Bug - repeat while loop

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#506]
It seems that the repeat while loop is not working correctly.

If this loop is used the whole program will not be executed.

![image](https://cloud.githubusercontent.com/assets/19221359/26346207/c552278e-3fa5-11e7-8643-4a3b6f577ae5.png)

**Comment by cvejoski** [comment]
This is working fine for Calliope 2016 and Calliope 2017. Can you explain more what is not working correctly?

**Comment by cvejoski** [comment]
hardware bug
