### ISSUE TITLE
Open Roberta Sim - Math constants not working

### ISSUE THREAD

**Issue by Knorrke** [OpenRoberta/robertalab#513]
When I use a math constant like Pi or sqrt(1/2) in the Open Roberta simulator the program doesn't run, and the following error is logged:

```
uncaught exception: Invalid Math Constant Name
```

**Comment by ensonic** [comment]
From the js console:
Uncaught Invalid Math Constant Name
evalMathConst @ program.eval.js:1057
evalExpr @ program.eval.js:832
evalBinary @ program.eval.js:931
evalExpr @ program.eval.js:811
evalShowTextAction @ program.eval.js:385
ProgramEval.step @ program.eval.js:114
render @ simulation.js:289

The code in program.eval.js should print the name in the error message, but if I sert a break point, I get '"right.value"'?
