### ISSUE TITLE
NXT: play frequency in a function could not be transformed

### ISSUE THREAD

**Issue by Mathias573** [OpenRoberta/robertalab#521]
play frequency on NXT is ok:
![play_sound](https://user-images.githubusercontent.com/29167259/27009263-bf4dd93a-4e89-11e7-98c3-c9dd34fededa.PNG)
put this in a function:
![play_sound_function](https://user-images.githubusercontent.com/29167259/27009266-d025f012-4e89-11e7-927f-37c3291566ce.PNG)
get errorr message:
![error_message](https://user-images.githubusercontent.com/29167259/27009268-dc344f2a-4e89-11e7-8a33-dc57f238f869.PNG)
simulation works fine

**Comment by elhele** [comment]
Fixed with play frequency (fae1a48), but there is the same problem with timer that should also be fixed.

**Comment by elhele** [comment]
Fixed with f65a6c3
