### ISSUE TITLE
NXT: get light

### ISSUE THREAD

**Issue by Mathias573** [OpenRoberta/robertalab#522]
if you use the function "get light from light sensor" you get different results depending on the status of the LED at start.
Test:
![get_light](https://user-images.githubusercontent.com/29167259/27013904-2991444a-4eed-11e7-9a8c-5e9899db0ac5.PNG)
For the test I had the light-sensor 5 mm in front of a white paper in a dark environment. The first result is 5 an the second result is 75.
I think, if the LED is off and you use this function, the LED is turned on but it takes a while. So you get at first only the ambient light. If you use the prgram-snippet in a programm, where the LED is on, both results are the same.
I played around and shortened the wait time: for 10...20 ms you get the same results. This is the time the LED need to turn on.

I don't know how to handle. If you insert a wait time in the function (turn on LED, wait 20 ms, read sensor) then the function always takes longer than now (although it is not neccessary if the LED is on). Perhaps you can insert a wait time only if the LED is off?

**Comment by rbudde** [comment]
solved
