### ISSUE TITLE
Update welcome tour

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#532]
There were many improvements in enjoyhint library. We need to adjust our welcome tour to those changes.

**Comment by bjost2s** [comment]
The new version of enjoyhint doesn't recognize the menu as part of the  website. Also the escape button has disappeared.
![image](https://user-images.githubusercontent.com/1613069/28662895-fec5ac04-72bb-11e7-8729-34eb6bfc83a8.png)

**Comment by elhele** [comment]
@bjost2s  It was just a wrong z-index. Fixed it with 41eb0f8

**Comment by elhele** [comment]
Now tour seems to be working fine except for the devices with touch screen:
when the tour is supposed to be finished when "sim" button is pressed:
![tourend1](https://user-images.githubusercontent.com/13983474/29208364-08deaa04-7e8a-11e7-8716-63c16c8399f2.png)
instead of going back to the list of robots it just closes the simulation and stays in a welcome tour:
![tourend2](https://user-images.githubusercontent.com/13983474/29208414-35b70b2a-7e8a-11e7-8b21-257db08982f4.png)
