### ISSUE TITLE
Calliope 2016 - server error - 2.2.6.

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#533]
Using Motor block causes a server error

**Comment by cvejoski** [comment]
The motors are working for 2016 and 2017. Maybe there is a another block. Can you upload the program too?

**Comment by Thorlogy** [comment]
Sorry my fault - the server error pops up - running the program in the simulation

**Comment by cvejoski** [comment]
fixed with d3727420fb50999d653773cbf2a146f891dc0197
