### ISSUE TITLE
fix calliope microphone

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#535]
map the analog output to 0-100, approximately
see http://www.elektronik-labor.de/Microbit/Calliope2.html#kl 
new calliopes will have an amplification of 10, so this is the majority

**Comment by larspelz** [comment]
Happy to see progress on this! I tested it on both the old and new boards and can confirm it's working. However I don't get raw values higher than ~25 even on a new board. I attached my test program.
[nepo-mic-test-c17.zip](https://github.com/OpenRoberta/robertalab/files/1121606/nepo-mic-test-c17.zip)

**Comment by bjost2s** [comment]
Normally the microphone needs to have an amplification on the hardware side. Here it is explained in detail: http://www.elektronik-labor.de/Microbit/Calliope2.html
Unfortunately I do not have a calliope where the problem with the resistor is fixed, but I 've heard that newer once will have it. Once I have one, I could will improve the mapping if necessary.
