### ISSUE TITLE
Usability OR Lab - category action

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#537]
Especially if action blocks used its hard to select new blocks within the category action

![image](https://user-images.githubusercontent.com/19221359/27378705-fc34d2e4-5678-11e7-9736-728eecf9ecc7.png)

**Comment by bjost2s** [comment]
Which problem should be solved? Please make proposals how it should look like, that we could fix it.

**Comment by Thorlogy** [comment]
My suggestion would be to increase the color saturation of the background layer

**Comment by bjost2s** [comment]
I will convert the current opacity from css to a lighten value for the background with opacity = 1. We will have the same or similar color of the background but no transparency anymore.
