### ISSUE TITLE
Different behavior Sim vs. Real EV3 robot - lejos

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#538]
This program causes different behavior 

![image](https://user-images.githubusercontent.com/19221359/27378890-8fcddc6c-5679-11e7-8a8a-9b2adc53d77e.png)

In OR Sim it works fine. On the real EV3 robot - using lejos firmware - the robot does not move (or moves very slowly)

**Comment by cvejoski** [comment]
The problem is that "drive forward" block is called two often. If you put it outside repeat it will work fine.

**Comment by Thorlogy** [comment]
1. yes i know - but the problem is the different behavior of sim vs real robot 
2. putting the block outside repeat loop the behavior is is a different program with a different behavior

**Comment by bjost2s** [comment]
![image](https://user-images.githubusercontent.com/1613069/27405243-1a172df4-56d1-11e7-8f5f-0b48d9769400.png)
Please program "events" in this way. NEPO is exspecially designed for this. This program will work on both, real and sim, the same. Why?
The drive forwards block needs time to be executed. Go through the blocks from the beginning to the end.
The drive forwards block will only be executed after the robot bumped into an obstacle.
We already have talked about this.

**Comment by Thorlogy** [comment]
The problem for the user is the different behavior Sim vs Real robot.

**Comment by ensonic** [comment]
The simulator is not a physical simulation. I agree with @bjost2s suggestion.It is not feasible to model the same behavior on the simulator. There we'd need to add a micro delay for starting the motors or something like it.
