### ISSUE TITLE
Improve Error Handling 

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#54]
During some testing I detected, that ALL errors sent from the server to the client are ignored. A log message "network changed" (???) is written (and lost), the user gets no information at all.
Further the behavior of the frontend is (at least) irritating if the server is not available at all.

**Comment by bjost2s** [comment]
As a quick fix the gui will inform the user with an "Attention popup"

**Comment by bjost2s** [comment]
done
