### ISSUE TITLE
NXT: drive forward with speed more than 100%

### ISSUE THREAD

**Issue by Mathias573** [OpenRoberta/robertalab#540]
if I use "drive forward" with speed=150 my robot drives backwards.
![drive_forward](https://user-images.githubusercontent.com/29167259/27399516-5200abf0-56bd-11e7-88ec-6d65f4fc8f01.PNG)
some tests:
120%: forward
130%: backward
200%: backward
250%: no movement (but the program is still running)
300%: forward

(I know the maximum is 100%  but the kids don't know and try it and their robots move backwards and the kids wondering why)

**Comment by bjost2s** [comment]
Please check, 
- why do we not check for lower than -100, which is still allowed
- what about all other methods like drive in curve (steerdriveex) ....
