### ISSUE TITLE
Blocks disappear when uploading to EV3 leJos (or when simulate)

### ISSUE THREAD

**Issue by patrickschaerer** [OpenRoberta/robertalab#543]
When I try to upload a more complex programm to EV3 most of the blocks disappear in the browser window. The program loads to the EV3 perfectly.
To see all the blocks again I need to reload the page, login and load the program.
before uploading:
![beforeuploading](https://user-images.githubusercontent.com/28363068/27515714-7a468aa4-59aa-11e7-857f-09ea2cbe1f13.png)
after uploading:
![afteruploading](https://user-images.githubusercontent.com/28363068/27515717-8cd7f252-59aa-11e7-9406-4c6529406718.png)

**Comment by bjost2s** [comment]
When this had happened, could you please have a look into the help menu - logging? If there is a red marked line, please send us a screenshot. Also can you attach the exported xml from the program? Thank you

**Comment by patrickschaerer** [comment]
This is the log (created without connection to EV3 but with simulate) ... it seems there is a bug in my syntax
`NO.
TYPE
MESSAGE
NO.
TYPE
MESSAGE
25	[[TIME]]	10 msec: help clicked
24	[[TIME]]	2 msec: log list activated
23	[[ERR ]]	[[TIME]] 1 msec: run program 'SimonSays2' with configuration 'EV3basis', then EXCEPTION: SyntaxError: Unexpected token var
22	[[ERR ]]	[[TIME]] 62 msec: run program 'SimonSays2' with configuration 'EV3basis', then EXCEPTION: Connection checks failed.
21	[[TIME]]	240 msec: tabProgram clicked
20	[[TIME]]	7 msec: back to previous view
19	[[TIME]]	28 msec: help clicked
18	[[TIME]]	3 msec: log list activated
17	[[TIME]]	230 msec: tabProgram clicked
16	[[TIME]]	9 msec: load program 'SimonSays2' owned by 'Pschaerer'
15	[[TIME]]	6 msec: Load program from listing double clicked
14	[[INFO]]	loadFromList SimonSays2
13	[[TIME]]	20 msec: load program list`


[SimonSays2.xml.txt](https://github.com/OpenRoberta/robertalab/files/1101209/SimonSays2.xml.txt)

**Comment by bjost2s** [comment]
thank you, it seems that the create empty list block causes the problem. This little test program is behaving similar:
![image](https://user-images.githubusercontent.com/1613069/27559207-fb9a9bd4-5abf-11e7-9c35-698d9e769ae7.png)

**Comment by patrickschaerer** [comment]
I changed the code to your example but it did not correct the problem
![bildschirmfoto 2017-06-27 um 11 10 25](https://user-images.githubusercontent.com/28363068/27579949-88eb6fea-5b29-11e7-8e7c-d838c3a87e81.png)
![bildschirmfoto 2017-06-27 um 11 10 38](https://user-images.githubusercontent.com/28363068/27579957-8d11ccf4-5b29-11e7-9034-8a24a373187d.png)
[SimonSays3.xml.txt](https://github.com/OpenRoberta/robertalab/files/1104781/SimonSays3.xml.txt)

**Comment by elhele** [comment]
The problem is caused by array rewriting. it wouldn't matter if it is empty or any other array. This would't work either: 
![screenshot from 2017-06-27 12-09-56](https://user-images.githubusercontent.com/13983474/27582677-0871e2fa-5b32-11e7-9fb0-c85699ed55b3.png)

Also, it is a problem of all robots, not only ev3.

**Comment by VinArt** [comment]
Just for the information: the problem was in assignment block, when it was doing transformations, it capitalised the first letter of block name and made everything else lowercase, but the first letter of type (which is part of blockname) should have been capital.
