### ISSUE TITLE
Calliope 2017: motor runs with constant velocity

### ISSUE THREAD

**Issue by herb91** [OpenRoberta/robertalab#558]
I expected the motor starts with speed 10% and increase the speed to 80% after a second. But the motor runs with constant speed and stops at the end. With negative values the motor doesn't move.

```javascript
while ( true ) {
  if ( uBit.buttonA.isPressed() ) {
    uBit.soundmotor.motorAOn(10);
    uBit.sleep(1000);
    uBit.soundmotor.motorAOn(80);
    uBit.sleep(1000);
    uBit.soundmotor.motorAOff();
}
uBit.sleep(1);
}
```

**Comment by cvejoski** [comment]
There is bug in the calliope firmware that if you use the motors separately they both must be active.
Can you please first set both motors (A and B) to 0 and then try to the rest of the program that you have.

**Comment by bjost2s** [comment]
The problem is, that we do not offer a block for using the motor driver with one motor. There is another function in the firmware that can also accept negative values and will work as expected. Our motor block is for using calliope with two motors, for robotic matters.
Maybe we will add the single motor block in the next version.

**Comment by herb91** [comment]
@cvejoski 
I've tried this code with the result that the motor A didn't turn.
```javascript
    while ( true ) {
        if ( uBit.buttonA.isPressed() ) {
            uBit.soundmotor.motorAOn(0);
            uBit.soundmotor.motorBOn(0);
            uBit.display.scroll(ManagedString("10"));
            uBit.soundmotor.motorAOn(10);
            uBit.sleep(1000);
            uBit.display.scroll(ManagedString("50"));
            uBit.soundmotor.motorAOn(50);
            uBit.sleep(1000);
            uBit.display.scroll(ManagedString("100"));
            uBit.soundmotor.motorAOn(100);
            uBit.sleep(1000);
            uBit.display.scroll(ManagedString("0"));
            uBit.soundmotor.motorAOff();
        }
        uBit.sleep(1);
    }
```
Without the lines
```javascript
            uBit.soundmotor.motorAOn(0);
            uBit.soundmotor.motorBOn(0);
```
the motor works, but with constant high speed.
I will check the behaviour with 2 motors as mentioned from @bjost2s

**Comment by bjost2s** [comment]
Could you please show us how the motor at the example above  is connected?

**Comment by herb91** [comment]
In the example the connected pins are:
VM(max 9V): + of a 9V Lego power supply
GND: - of the power supply
Motor A: + of the motor
Motor B: empty
GND: - of the motor

**Comment by cvejoski** [comment]
Do you use the public open roberta lab version or local version?

**Comment by herb91** [comment]
I have used the open roberta lab version https://lab.open-roberta.org/
With this code (one motor connected to A) 
![onemotor](https://user-images.githubusercontent.com/9220918/28288576-ed72e47c-6b3f-11e7-976c-2aa0f3e1ce6d.PNG)
the motor starts turning with 100% if the button is pressed until the motor stops.
If the code controls 2 motors
![twomotors](https://user-images.githubusercontent.com/9220918/28288741-798f6642-6b40-11e7-9af4-551d7d519dfa.PNG)
both motors starts with 40% up to 100% and everything works fine.
This code works for one motor too. It doesn't matter if the motor is connected to A or B.

**Comment by cvejoski** [comment]
The solution to the problem will be to implement new block only for one motor. The current motor blocks should be used when one have two motors

**Comment by cvejoski** [comment]
check ticket #582 for the new motor block
