### ISSUE TITLE
Apply suggested fixes reported by pagespeed

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#56]
https://developers.google.com/speed/pagespeed/insights/
I still have this installed as a chrome extension which now is deprecated :/ There is a variant of this in the chromestore too which I haven't tested.
https://chrome.google.com/webstore/detail/pagespeed-insights-with-p/lanlbpjbalfkflkhegagflkgcfklnbnh

The downside of the online version is that one cannot analyze the current local dev version. We can also potentially integrate this as a test: https://github.com/addyosmani/psi

Anyway the tool points out some interesting ways to optimize the page loading speed for the lab. Right now we have a score of 13 test cases passing and 12 open suggestions:
- [ ] Minimize payload
  - [x] **H** Enable compression
  - [x] **H** Serve scaled images
  - [ ] **H** Minify JavaScript
  - [x] **M** Serve resources from a consistent URL
  - [ ] **M** Optimize images
  - [ ] **L** Minify HTML
  - [x] **L** Minify CSS
- [ ] Minimize delay in page load 
  - [ ] **L** Specify image dimensions
  - [ ] **L** Specify a character set
- [ ] Other 
  - [ ] **H** Leverage browser caching
  - [ ] **H** Specify a cache validator
  - [x] **L** Defer parsing of JavaScript
  - [ ] **L** Specify a Vary: Accept-Encoding header

For minifying js and css we can try [this maven extension](http://samaxes.github.io/minify-maven-plugin/usage.html).

**Comment by ensonic** [comment]
@rbudde I have this patch to enable gzip compression
https://gist.github.com/ensonic/f47946a07941545cda12336ff9509f35
This will compress files as we sent them and thus create load on the server.
There should be also a way to enable gzip compression for jetty on the DefaultServlet by setting the "gzip" init-parameter, but I could not find the related API. That would also require to have a maven rule to gzip static content.
See: https://wiki.eclipse.org/Jetty/Feature/GZIP_Compression

**Comment by drigz** [comment]
#176 should improve this by compressing JS and CSS. I haven't enabled minification for either - it should be harmless for CSS but might break the JS.

Here is the current breakdown of page size with the compression:

- Total: 807 KB
- Javascript: 454 KB (could be improved with an optimizer, eg [r.js](http://requirejs.org/docs/optimization.html))
- CSS: 33 KB
- Images: 155 KB (mostly already compressed, <5 KB SVGs)
- Sounds: 15KB
- Fonts: 83 KB (typicons.ttf, could be gzipped)
- HTML: 44KB (all index.html, could be gzipped)
- Mystery: 23 KB (overhead? not in Chrome network tab)

**Comment by ensonic** [comment]
"Enable compression" is now a "M" severity due to the index,html and the css/svg/NEPO_Logo_RGB.svg

**Comment by drigz** [comment]
For "Serve resources from a consistent URL": https://api.jquery.com/jquery.getscript/#caching-requests

**Comment by VinArt** [comment]
@ensonic currently it is possible to analyse latest develop, because the test server is running it

**Comment by VinArt** [comment]
Compression is done, complete solution will be available when using webpack
