### ISSUE TITLE
Code generation: variables sequence in assignment

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#565]
For this kind of program the following java code is generated, which will lead to an exception:
![grafik](https://user-images.githubusercontent.com/3738015/28212313-1ae6557a-68a1-11e7-954d-4af66fcf7852.png)

In c/c++ it is not a problem, since variables are declared beforehand and will be just initialised with garbage or 0 depending on the compiler, but for java and python this is a problem.

**Comment by elhele** [comment]
Tested on ev3, the code doesn't compile when trying to upload to the robot.

**Comment by bjost2s** [comment]
related to #417, please commend on my proposal to  fix the bug in the following way:
"What we could do easily is to make the declaration more save that users cannot change the preassigned blocks, but changing the value. The user than cannot assign a function to the declaration anymore."
Where cannot assign a function means also cannot assign a variable.

**Comment by cvejoski** [comment]
I think not allowing to the declaration will be the best solution. In this way we will fix all the problems related to calling sensors that they are not setup yet.
