### ISSUE TITLE
Open Roberta Simulator does not open if function parameter is image

### ISSUE THREAD

**Issue by goerge** [OpenRoberta/robertalab#567]
With the attached program loaded the simulator does not open anymore.

If the image parameter of the function is removed, the simulator opens fine.

[NEPOprog-FunctionWithImageParameter.xml.txt](https://github.com/OpenRoberta/robertalab/files/1150223/NEPOprog-FunctionWithImageParameter.xml.txt)
(I had to add a `.txt` extension as GitHub refuses `.xml`)

**Comment by bjost2s** [comment]
Thank you, we will fix this asap
