### ISSUE TITLE
calliope lists problem

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#570]
executing this program is not working, neither on calliope nor in simulation
![img-20170717-wa0000](https://user-images.githubusercontent.com/1613069/28301091-541e8a5c-6b84-11e7-8206-3186c5b399a3.jpg)

**Comment by cvejoski** [comment]
For me it is working on the Calliope 2017 but not on the simulation.

Which version of calliope do you use?

**Comment by cvejoski** [comment]
This is fix for the simulation

**Comment by bjost2s** [comment]
It comes from a user request, so Calliope 2916 is also fine. Seems to be fixed now, thanks.
