### ISSUE TITLE
NAO speech recognition block

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#573]
Currently speech recognition block from NAO looks like this:
![grafik](https://user-images.githubusercontent.com/3738015/28308362-3cba8d30-6ba6-11e7-9f1a-f5bb7e8f0998.png)
and generates the following code:
`h.recognizeWord()`
If we take a look at hal.py [originalHal](https://github.com/OpenRoberta/robertalab-naoprogram/blob/master/OpenRobertaNAO/src/main/resources/originalHal.py) invocation of this method should also contain vocabulary (before my last commit it was like that too), so the block should accept a list of words or phrases.

Speech recognition on NAO is event based, so it might be tricky to use it from blockly (without blocking).

**Comment by VinArt** [comment]
Discussed solution would be to start speech recognition engine in the background if this block is used and let it update a lastRecognizedWord variable of hal. So all the speech recognition will be in reading the contents of that variable. Initialisation block would require a vocabulary though.

**Comment by VinArt** [comment]
`#!/usr/bin/python

from hal import *
import time

h = Hal()

speechRecognition = SpeechRecognitionModule("speechRecognition")
speechRecognition.setVocabulary(["one", "two", "three"])
speechRecognition.toggleVisualExpression(False)
speechRecognition.toggleAudioExpression(False)

while(True):
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print "Interrupted by user, shutting down"
        speechRecognition.memory.unsubscribeToEvent("WordRecognized", speechRecognition.getName())
        h.myBroker.shutdown()
        sys.exit(0)

`

Speech recognition works like this. I will try and make it better, for now it is like this.

**Comment by bjost2s** [comment]
what is the current state?

**Comment by VinArt** [comment]
I believe it is done, @cvejoski helped finishing it and it is in sync with haribo

**Comment by VinArt** [comment]
Sorry, I meant #560, not #550 above
