### ISSUE TITLE
webapp manifest is not expanded during build

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#574]
When building ./OpenRobertaServer/staticResources/manifest.webapp.json we need to expand the project properties.

**Comment by bjost2s** [comment]
I do not really know, why this was a bug, but after your commit we have a bug:
![image](https://user-images.githubusercontent.com/1613069/28373406-8ae3407c-6ca2-11e7-89dc-0817ca8c3335.png)
Please always test with deleting the cache

**Comment by ensonic** [comment]
The missing icons? I'll take a look.

**Comment by ensonic** [comment]
I'll check if maven can do the filtering just for specific files.

**Comment by ensonic** [comment]
Now it only expands the expected file types.

**Comment by bjost2s** [comment]
As I do not know exactly what the reason for your changes are, I think should leave this open until someone, you?, has done more tests.

**Comment by ensonic** [comment]
Sorry I don't understand. Before this change 	da5fc63 the manifest.webapp.json was not expanded during the build, now it is.

``` patch
diff ./staticResources/manifest.webapp.json ./target/classes/staticResources/manifest.webapp.json
4c4
<   "version": "${openRobertaServer.version}",
---
>   "version": "2.2.7",
8c8
<     "url": "${project.parent.url}"
---
>     "url": "http://www.open-roberta.org"
```

I compared the whole ./target/classes/staticResources with the source dir and no other files are touched, as explained in the commit message.

**Comment by bjost2s** [comment]
ah, ok.
Wouldn't it be easier, more safe, to have a dedicated filter only for this one file. Otherwise we have to take care of this each time we add new files/binaries.

**Comment by ensonic** [comment]
I can do this as well. I thought it is a good idea to have the filetype list in addition to protect those file types in general.
