### ISSUE TITLE
NXT does not start program automatically

### ISSUE THREAD

**Issue by RicardoUsbeck** [OpenRoberta/robertalab#575]
Hi, 

first of all, thanks for OpenRoberta. 

We are playing around with our NXT and OpenRoberta. When I click to run it on the robot, it transfers the files but does not execute it automatically. However, I can manually navigate to the file and run it just fine. Is there an option to change that?

**Comment by cvejoski** [comment]
This is intentional behavior, and the purpose is to have time to disconnect the NXT and put it on a desired location and then run the program.

**Comment by RicardoUsbeck** [comment]
I see, thanks for clarification. I was trying to bug fix this feature this morning.
