### ISSUE TITLE
Bug - Welcome tour 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#576]
![image](https://user-images.githubusercontent.com/19221359/28557349-3321a158-710c-11e7-9e64-db58ec4a4546.png)

Using Chrome on Mac. Same "bug" on Firefox and Safari on Mac

**Comment by elhele** [comment]
Hello, @Thorlogy , it seems to be online version. I've updated the tutorial framework, so now the develop version should work fine.

**Comment by Thorlogy** [comment]
Thanks. Then i think this ticket can be closed.

**Comment by bjost2s** [comment]
see    #532
