### ISSUE TITLE
After expanding and collapsing wait until block

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#577]
![image](https://user-images.githubusercontent.com/19221359/28557441-bfaa58fe-710c-11e7-906d-f11ddefc0b02.png)

After expanding (+) and collapsing (-) the wait until block the logic-block does not disappear.

**Comment by Dittse** [comment]
This behavior is not limited to the wait block. Every expandable block shares this behavior so you don’t lose your transition conditions while modifying your program.

**Comment by bjost2s** [comment]
This is not a bug. In 2015 we added this behaviour because of a user request.

**Comment by Thorlogy** [comment]
Ok. I agree, best to discuss this in the google group, because i definitely can't see the added value.
