### ISSUE TITLE
program list view disables the new button

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#58]
if the list of my programs is shown, it is not obvious how to cancel this action without selecting one of the programs: the "new" button should be enabled and cancel the listing. Actually only selecting the programming tab (again) cancels the listing.

**Comment by bjost2s** [comment]
What about the buttons on the bottom of the side, are they hidden for you?
![image](https://cloud.githubusercontent.com/assets/1613069/13418600/444a8eb8-df77-11e5-87a2-d748e4d34dc5.png)
