### ISSUE TITLE
when having a tab oopen (code, help, sim) and resizing the window the tab-handles get detached

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#580]
below I opened the code view, then grabbed the right window border and made the window smaller. If I'd make the window larger, the '<>' icon would be moved under the code pane. The issue also happens in develop.

![screenshot from 2017-07-28 16 00 58](https://user-images.githubusercontent.com/1279486/28720782-7954cc1e-73ae-11e7-830e-844097379510.png)

**Comment by VinArt** [comment]
Interesting, are there special conditions to reproduce? For me strange things happen only if I resize the window (Linux, Chrome 60, X11), but when I start dragging the pane the '<>' icon goes back where it should be.

**Comment by ensonic** [comment]
Same here. Tested with chrome/firefox on linux. And yes, it only happens when you resize the width of the window.

**Comment by VinArt** [comment]
Also this is true for all other buttons, e.g. sim. So must be a common button bug.

**Comment by elhele** [comment]
Another button bug:
if in the end of the welcome tour I don't press the simulation button, but just close the tour, I cannot use the simulation button and cannot close the simulation without reloading the page. Ev3's simulation from the tour will just stay there even if I choose some robot that doesn't have any simulation.
