### ISSUE TITLE
Unable to access lists in Calliope

### ISSUE THREAD

**Issue by alexgit2k** [OpenRoberta/robertalab#584]
You are unable to access lists in Open Roberta Lab with Calliope. Wether they are defined in Start or in a for-each-item-loop. The simulator skips the for-each-item-loop: [lists.xml](https://github.com/OpenRoberta/robertalab/files/1203323/lists.xml.txt)

![lists](https://user-images.githubusercontent.com/7514221/29005942-856e6ffc-7ae6-11e7-8873-2b1164d1de4c.png)

**Comment by cvejoski** [comment]
this is fixed with commit d28a15be6243c1fa94b0927d06023540721ab70f

In the new version it would not be a problem any more
