### ISSUE TITLE
Feature request "pin pressed" at get-sensor-value in Calliope

### ISSUE THREAD

**Issue by alexgit2k** [OpenRoberta/robertalab#585]
Option "pin pressed" should be available in the get-sensor-value-block:
![pin](https://user-images.githubusercontent.com/7514221/29006068-f04ac472-7ae8-11e7-87d9-6d6ce3c40288.png)

**Comment by VinArt** [comment]
Maybe this should look like: wait until pin high/pin low?

**Comment by alexgit2k** [comment]
Ah, I forgot that the pins can not only be touched, but also can have a digital or an analog value. So the new options should be:
- get "pin (touched)" 0/**1**/2/3 **=**/≠ **true**/false
- get "pin (digital)" 0/**1**/2/3 **=**/≠ **true**/false
- get "pin (analog)" 0/**1**/2/3 **>**/≥/</≤/=/≠ Integer (**50**)

Bold-values should be default values.
Touched and Digital could be grouped together as "pin (touched/digital)".
