### ISSUE TITLE
Feature request: add a "play note"-block like it is in scratch

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/robertalab#595]
Hello!

Pupils love to see the NXT dancing. But the "play frequency"-block is hard to use: to program a melody you must know the frequencies of the notes to play.
It would be very nice if you could add a "play note"-block with a little keyboard integrated like there is in scratch.

Keep up the good work
corvus-albus

**Comment by bjost2s** [comment]
Please check the calliope system in the lab. There we already have such a kind of block. Do you mean this?

**Comment by corvus-albus** [comment]
Yes, that's it. I would love it if the keyboard would be available for NXT too!

Cheers 
corvus-albus

**Comment by corvus-albus** [comment]
Sorry, closed the issue unintentionally.

**Comment by bjost2s** [comment]
you can look at the source code in e.g. calliope view, when you used one of the note blocks. I made it simple, a whole note has a duration of 2000 ms, a half note 1000 ms ....
I will check, if we can make it for the next release.

**Comment by bjost2s** [comment]
new issue for all systems here: #640
