### ISSUE TITLE
Add Method to Add Status Text for Server Administrator

### ISSUE THREAD

**Issue by labcode-de** [OpenRoberta/robertalab#597]
Add a method where the server admin can add a status text like 'The server will be restarted at 19.5.2017 at 7.pm'.

**Comment by bjost2s** [comment]
Currently it is not possible to change the text

**Comment by labcode-de** [comment]
Working on it

**Comment by labcode-de** [comment]
Hi! Can you not add a text or could you not change the text?

**Comment by bjost2s** [comment]
I think I made a mistake with the date, so it is working!
