### ISSUE TITLE
Automated snap builds

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#599]
Maybe it would be a good idea to package OpenRoberta for users that would like to run the server locally, so they will not need build everything from source. Snaps have a documentation page on how to integrate with Travis [https://snapcraft.io/docs/build-snaps/ci-integration](snap integration with CI)

**Comment by bjost2s** [comment]
WE already have the binaries. No need for users to build the server at all. See releases and the installation wiki pages here.

**Comment by bjost2s** [comment]
Please comment, if you don't agree. 
For users with internet access it is highly recommended to use the web lab

**Comment by VinArt** [comment]
This will be resolved with introduction of Docker.
