### ISSUE TITLE
Mathematik - Division nicht eindeutig

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#60]
Wenn zwei ganzzahlige Parameter eingegeben werden, wird eine Ganzzahldivision durchgeführt, also z.B. 50/90 = 0. Ist einer der Parameter eine Variable, dann erfolgt eine „normale“ Dezimaldivision. Die angehängte Bilddatei zeigt das Problem.
![divisionsfehler](https://cloud.githubusercontent.com/assets/1613069/13393035/27be8148-dedf-11e5-8eb7-4c368b843124.png)

**Comment by bjost2s** [comment]
Is it also an issue on ev3dev?

**Comment by ensonic** [comment]
On ev3dev it is both times 0
```python
bla = 90
hal.drawText(str(50 / 90), 0, 0)
hal.drawText(str(50 / bla), 0, 2)
 ```
Even worse is that we don't have a way to 'enforce' float math. I can't enter '''90.0''' for the value to show that it is a float; it will be reduced to '''90'''. Maybe we need to have two number blocks; one for int and one for float and alias the old number to int?

**Comment by bjost2s** [comment]
We check on client side the  decimal mark, why not simply add a ".0" there. when sending to the server. all computed results will have a decimal mark then by default.

**Comment by ensonic** [comment]
That's what I said. I've tried to use ```90.0```, but something strips the ```.0```. We should not do that for a start.

**Comment by bjost2s** [comment]
is it fixed? I'm not sure

**Comment by cvejoski** [comment]
@ensonic can you please check if everything is fine on the ev3dev side with the division

**Comment by ensonic** [comment]
First one gives 0.555555556 on ev3dev.
