### ISSUE TITLE
mirco:bit simulation. Button always pressed?

### ISSUE THREAD

**Issue by zarrock13** [OpenRoberta/robertalab#600]
In the micro:bit simulation it looks like the buttons (A and B) count as "pressed" all the time. 
Example: the heart is shown as soon as i start the simulation.
The code workes as intended if i use the "pin touched?" block.
![image](https://user-images.githubusercontent.com/31468737/29860494-7dbbfc10-8d66-11e7-8205-4ed13c4a7be1.png)

**Comment by bjost2s** [comment]
Thank you, we will fix it!
