### ISSUE TITLE
Feature request: flashing multiple robots simultaneously 

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#603]
Create Agent integration #602 #492 allows users to see a list of multiple robots if more than one robot of the same type is connected. As a user I may have up multiple robots that I want to pre-flash with demonstration programs or use the same program on all robots that implements some robot interaction behaviour. For these purposes it would be nice to have not only "play" ('>') button, but also 'play all' ('>>') button that will flash this program to all robots in the list.

**Comment by bjost2s** [comment]
Unfortunately we only have one robot system, where the create agent works. Additionally most users have the problem of not having any robot system so having more than one is probably rare.

**Comment by bjost2s** [comment]
Please reopen, if this is still a whish
