### ISSUE TITLE
travis build is broken

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#607]
Right now the travis build is broken, since we interactively ask when resetting the db:
https://travis-ci.org/OpenRoberta/robertalab

This is the code:
https://github.com/OpenRoberta/robertalab/blob/develop/ora.sh#L189

A few options:
1. we replace the ./ora.sh --reset-db with a shell command to init the db
1. we remove our custom code to ask for overwrite and use cp --interactive instead
1. ...

**Comment by rbudde** [comment]
already fixed. Have to commit that.

**Comment by ensonic** [comment]
Thanks, please push. Almost fixed it myself again.

**Comment by rbudde** [comment]
... at least a get a green sign from travis :-)

**Comment by rbudde** [comment]
reopened to allow reviewing
