### ISSUE TITLE
Der Experten-Block Text - Erstelle Text aus arbeitet nicht korrekt.

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#61]
Wenn am Eingabeslot ein mathematischer/logischer Ausdruck steht, wird dieser nur korrekt verarbeitet, wenn er am ersten Slot angedockt wird. Falls ein anderer als der erste Slot einen Ausdruck erhält, gibt es eine Fehlermeldung (siehe angehängte Datei).
![erstelletextaus-fehler](https://cloud.githubusercontent.com/assets/1613069/13393092/8c15f522-dedf-11e5-8874-dfd5189f3d6e.png)

**Comment by bjost2s** [comment]
Please check if this is also an issue on ev3dev

**Comment by ensonic** [comment]
Jeps, also broken on ev3dev with python:
```
BlocklyMethods.textJoin("17 + 4 = "; 17 + 4)
```

**Comment by ensonic** [comment]
Hmm, there is probably something wrong with the AST:
https://github.com/OpenRoberta/robertalab/blob/19a58ba2fd5185bad4ab4e470c380bcaca682a5b/OpenRobertaRobot/src/main/java/de/fhg/iais/roberta/syntax/codegen/ev3/Ast2Ev3JavaVisitor.java#L1249-L1256

The loop is always just iterated once with expr being an ArrayList with the params. That also explains why the visitExprList is called.

**Comment by cvejoski** [comment]
There was bug (strange code :)) in the implementation of the AST transformer for the text join block.
