### ISSUE TITLE
Feature request ev3-dev: support NXT Light Sensor

### ISSUE THREAD

**Issue by corvus-albus** [OpenRoberta/robertalab#612]
Hello,

ev3dev does support NXT light sensors according to their documentation: [click](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-jessie/sensor_data.html#lego-nxt-light-sensor). It would be very nice to support this device in Open Roberta. As the displays of our NXTs at school slowly give up (up to now 50%) the sensors are still alive. It would be very nice to have the possibility to use them with the EV3.

Cheers 
corvus-albus

**Comment by bjost2s** [comment]
We always have to check new features for ev3 against all systems. We will have a look into the lejos libraries and come back to this feature ASAP

**Comment by corvus-albus** [comment]
Thank you for the new snapshot 2.3.1 and for your promising reply. I had a look at the lejos EV3 api documentation and found a description:
http://www.lejos.org/ev3/docs/lejos/hardware/sensor/NXTLightSensor.html
I hope that is helpful.

Cheers
corvus-albus

**Comment by bjost2s** [comment]
Thanks, we will add it to our wish list here #458

**Comment by bjost2s** [comment]
see #458

**Comment by rbudde** [comment]
see #458
