### ISSUE TITLE
Aktion - Setze Motor Port B Tempo 60 ohne Wirkung

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#62]
verändert nicht die Motorgeschwindigkeit und auch nicht den Wert
— siehe Screenshot eines Beispielprogramms —
![setzemotorporttempo](https://cloud.githubusercontent.com/assets/1613069/13393145/d323199a-dedf-11e5-8b1a-5853a10c7f2d.png)

**Comment by bjost2s** [comment]
Please check if this is also an issue on ev3dev

**Comment by ensonic** [comment]
Filed ev3dev/ev3dev#558, I can do a workaround if we need one.

**Comment by cvejoski** [comment]
This is a bug in the Lejos API it is fixed with the new version of Lejos

**Comment by ensonic** [comment]
Fixed on ev3dev too. @cvejoski feel free to close when it is fixed for lejos too.
