### ISSUE TITLE
Bob3 backgrounds and help pages missing

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#624]
I get 404 on following files:
* css/img/bob3BackgroundConf.svg 404 (Not Found)
* help/progHelp_bob3_en.html 404 (Not Found)
* css/img/bob3Background.jpg 404 (Not Found)

They should probably be added.

**Comment by bjost2s** [comment]
As we have used fot the hole bob3 integration issue #345, please leave it open until we have finished version 2.3.0.

**Comment by bjost2s** [comment]
help pages are not available, background images are added
