### ISSUE TITLE
Stop Button in Simulation should toogle after end of program

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#626]
Simulation: After finishing a program the Stop-Button should toogle back to Play-Button.

**Comment by bjost2s** [comment]
I cannot reproduce this bug, please provide more information, robot system, browser etc

**Comment by Thorlogy** [comment]
My fault. Tested it with Calliope mini, but forgot that programs running on Calliope never stop.
So no bug.
