### ISSUE TITLE
User registration dissapears 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#629]
If the user clicks besides the registration dialog, the dialog pop-up dissapears and the user has to fill in the whole dialog again.

![image](https://user-images.githubusercontent.com/19221359/30953715-6496b81e-a42d-11e7-98b7-1a0051c15dff.png)

**Comment by bjost2s** [comment]
fixed already here: https://github.com/OpenRoberta/robertalab/commit/a45194d779a51a41ea316c9e60f226baab6c3042
