### ISSUE TITLE
NEPO rechnet komplexere Rechnungen möglicherweise nicht korrekt.

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#63]
Beispiel: 60 / 180 * pi
geklammert: (60 / 180) * pi = 1,0472
falsch geklammert: 60 / (180 * pi) = 0,1061
NEPO gibt für beide geklammerten Rechnungen das gleiche Ergebnis aus, nämlich 1,0472.
Programm im Anhang
![rechenfehler nepo - falsche behandlung von klammern](https://cloud.githubusercontent.com/assets/1613069/13393216/3fc132b2-dee0-11e5-9362-0c2e1a03cd5a.png)

**Comment by bjost2s** [comment]
Please check if this is also an issue on ev3dev

**Comment by cvejoski** [comment]
This is a problem in general because we do not know when to use parentheses. We can add parentheses with every math expression like Blockly is doing.

**Comment by bjost2s** [comment]
As a user I would expect that each block is surrounded by parentheses, similar to blockly

**Comment by bjost2s** [comment]
Kostadin, can you fix this for 1.4?

**Comment by cvejoski** [comment]
This is fixed for 1.5. We wrap nested binary expressions with parentheses.

**Comment by ensonic** [comment]
@cvejoski was it does for all code generators?

**Comment by cvejoski** [comment]
@ensonic this is done for all but I have only pushed for java and javascript, for python I have changed it but I have not pushed the commit

**Comment by ensonic** [comment]
@cvejoski I can't test it right now, but maybe it is obvious. Could you paste the diff to a gist?

**Comment by ensonic** [comment]
Looks good to me, please push.

**Comment by cvejoski** [comment]
I have already pushed the changes for the python code generator

**Comment by ensonic** [comment]
Works, thanks!
