### ISSUE TITLE
Declaration of variables is hidden in the start block

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#630]
Showing a hint in the empty variable flyout makes it easier for nebies to find the variable declaration button
From users reported

**Comment by Thorlogy** [comment]
Text does not appear completely in Safari and Firefox
![image](https://user-images.githubusercontent.com/19221359/31044987-7da5452e-a5da-11e7-9c91-62cc716e87ef.png)

**Comment by bjost2s** [comment]
Could you please checkt it again?

**Comment by Thorlogy** [comment]
fixed. The text is now displayed in its entirety.
