### ISSUE TITLE
Robot/System name in galery 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#633]
On my smartphone (android/chrome) the robot name e.g. EV3 / NXT is fixed during scrolling and different names (EV3 / NXT) overlay

![galery_test_smartphone](https://user-images.githubusercontent.com/19221359/31048624-7bfee06c-a621-11e7-8595-a7a6ae5bba77.png)

**Comment by Thorlogy** [comment]
This bug appears not only on smartphone. It seems to be a "responsive bug". If you downsize the browser window the same behaviour is observable

**Comment by bjost2s** [comment]
Now the preview for uploading to the gallery has lost the icon completely:
![image](https://user-images.githubusercontent.com/1613069/31315863-4edaa7be-ac21-11e7-8866-ffb6dc00c9a5.png)
