### ISSUE TITLE
Simulation doesn't run a program after "Welcome tour" usage

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#637]
When I try to run a simulation after welcome tour, it opens normally, but when I push "play" button nothing happens. It was working fine on a66805d417440b7b04dbac347460a4ad153c65f2 commit,so probably something in 09fcddbc6206d35e3d49442f98b159f7abd24afe or some other commit frim #613 causes this problem.

**Comment by bjost2s** [comment]
fixed here https://github.com/OpenRoberta/robertalab/commit/b76977ffd1b7e4c43810afc83552a1139274a0f7
