### ISSUE TITLE
Nao LED eyes block crashes blocks when running program

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#638]
When I try to run a program with LED eye block the program runs fine, but all blocks disappear:
![image](https://user-images.githubusercontent.com/13983474/31081766-2b13e478-a78d-11e7-9dd7-faafc5266f15.png)

Upd: the block works with some colors, but breaks with the others

**Comment by JanisM91** [comment]
If the set LED color block is used from the expert toolbox it is not generating code at all.
