### ISSUE TITLE
Math - modes of list

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#64]
This block with the "modes" setting does nothing but returning the list that was given as input value.
![nepo modulo-restwert einer liste](https://cloud.githubusercontent.com/assets/1613069/13393351/3c6ec70e-dee1-11e5-87f8-8b0e0a8fd8a7.png)

**Comment by bjost2s** [comment]
The "mode" is copied from blockly, but there, it is not really clear what the result should be (generating always [0,1,3])

-> +1 for deleting this drop down value

**Comment by ensonic** [comment]
For reference: this is the js impl
https://github.com/google/blockly/blob/master/generators/javascript/math.js#L288

The "mode" is the value that occurs most often. If no number is repeated, then there is no mode for the list.

**Comment by bjost2s** [comment]
as discussed: will be removed see OpenRoberta/blockly#9

**Comment by bjost2s** [comment]
fixed
