### ISSUE TITLE
Missing brackets for Bob3

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#641]
Brackets are missing for the generated code, if you use a minus:
![grafik](https://user-images.githubusercontent.com/25958792/31170013-d74178d2-a8fa-11e7-9187-2d0597efb44b.png)

Example with the same blocks but using sqrt:
![grafik](https://user-images.githubusercontent.com/25958792/31170122-3eaab2f4-a8fb-11e7-9691-282873838d61.png)

**Comment by elhele** [comment]
It seems to be an issue for all of the robots, not only Bob3.
