### ISSUE TITLE
NAO Face Detection Error

### ISSUE THREAD

**Issue by nicolaipoehner** [OpenRoberta/robertalab#642]
Dear all,

I finally got the OpenRobertaLab working with our NAO but found some small mistakes while playing around with it this morning:

Robot: Error!	ALFaceDetection::setRecoginitionEnabled
	Can't find method: setRecoginitionEnabled (resolved to '(b)')

I guess the mistake might be the missspelling of recognition.

**Comment by JanisM91** [comment]
typo fixed with  OpenRoberta/robertalab-naoprogram@f2210ad2e8dde817cd46dcef339b2d9006ece650

**Comment by bjost2s** [comment]
This fix forces us to have again a new release for the naoprogram. Wouldn't it better to fix it in the codegeneration?

**Comment by bjost2s** [comment]
Is this resolved? If so please add the label resolved and move it to the right project. Is there a new release for the NAO program?

**Comment by cvejoski** [comment]
fixed with ddb90cc9d615beda602fe205d2bcbc8ca975fde9
