### ISSUE TITLE
Layout-Problem with Gallery

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#660]
Mac Browser: Chrome Version 61.0.3163.100 64-bit
![image](https://user-images.githubusercontent.com/19221359/31655684-f1bfe868-b329-11e7-8f44-5dfaa6d4566a.png)

Mac Browser: Firefox Version 56.0 64-bit
![image](https://user-images.githubusercontent.com/19221359/31655702-03d8194e-b32a-11e7-9a19-2a16c9023d48.png)

Mac Browser: Safari Version 11.0 
![image](https://user-images.githubusercontent.com/19221359/31656438-d94dca96-b32b-11e7-8801-25daaa5871d6.png)

**Comment by ensonic** [comment]
We should figure if we can use the free offer from sauselabs for cross browser testing:
https://saucelabs.com/blog/Announcing-Open-Sauce-free-unlimited-testing-for-Open-Source-projects

**Comment by bjost2s** [comment]
now back to overflow hidden
