### ISSUE TITLE
Add information to "Eclipse setup" wiki page

### ISSUE THREAD

**Issue by dbilay** [OpenRoberta/robertalab#661]
Please add an information at the "Eclipse setup" wiki page, that a OpenRobertaServer/db-x-y-z subfolder is required to start the server. Without the db, the server startup hang on 
"_INFO d.f.i.roberta.util.RobertaProperties - As temporary directory /tmp/ will be used_"

For a beginner it is hard to find the reason. So that will help to save a lot of time. 
Following my suggestion.

Eclipse setup is fairly simple,
* Make sure that the OpenRobertaServer folder has a subfolder db-x.y.z with the database inside, where x.y.z is the current version from the server.
* Open eclipse and use File->Import to import new maven projects
* Select the root directory and tick all related projects to import
* After importing go to Window->Preferences->Java->Code Style->Formatter and import java formatter from Resources folder
* Do the same for Javascript
* Go to OpenRobertaServer project (de.fhg.iais.roberta.main) locate and run as java program ServerStarter.java

You are now running OpenRoberta server locally on tour machine and can edit all the code and see the effect in the browser at localhost:1999

If you encounter an error with "...db parent folder OpenRobertaServer..." go to run configurations in Eclipse (drop-down arrow next to green run button), select ServerStarter and go to Arguments.
In this tab add:
`-d database.parentdir=<path to git repository>\OpenRobertaServer\`
argument and now the database will be found.
If you have errors with hibernate, add this argument as well:
`-d hibernate.connection.url=jdbc:hsqldb:file:<path to git repository>\OpenRobertaServer\db-<insert version here>\openroberta-db`

After updating certain resources or if something gets cached and does not change, right click on any project and go to Maven->Update project, in the window that pops up, select all related projects and update.

If you encounter "name of robot" has invalid factory - class not found exception - this is due to the fact that your classpath is not updated. Right click OpenRobertaServer project, go to properties -> java build path -> projects and add all robot plugin projects (not sure if TestResources should be there) and click apply. Now all needed classes should be on the class path.

If the server startup hangs on "INFO d.f.i.roberta.util.RobertaProperties - As temporary directory /tmp/ will be used", make sure that the OpenRobertaServer folder has a subfolder db-x.y.z with the database inside, where x.y.z is the current version from the server.

If you wish to counter long package names and provide somewhat clearer package explorer view, then go to Window -> Preferences -> Java -> Appearance and tick the "Abbreviate package names" checkbox. A suggested template for this is as follows:

* de.fhg.iais.roberta={rob}
* de.fhg.iais.roberta.syntax={syntax}
* de.fhg.iais.roberta.mode={mode}
* de.fhg.iais.roberta.factory={factory}

**Comment by bjost2s** [comment]
Thank you very much! It is in the wiki now. For the database, it is already in the readme. This is usually the very first instruction to follow
