### ISSUE TITLE
No guarda Info (Do not save Info)

### ISSUE THREAD

**Issue by adelmar1971** [OpenRoberta/robertalab#668]
Se escribe comentarios. Se guarda. Pero... cuando se inicia el simulador, se pierde lo guardado.
_Write comments. You save. But ... when the simulator is started, the saved is lost._
Un ejemplo de pantalla en  [ https://youtu.be/G2B3NikfU88](https://youtu.be/G2B3NikfU88)

**Comment by bjost2s** [comment]
Thanks, we will fix it asap

**Comment by adelmar1971** [comment]
## Excelente. Lo probamos y ahora sí lo reconoce. Éxitos.
Excellent. We tried it and now you recognize it. Successes.
