### ISSUE TITLE
Simple program not running on ev3dev - configuration problem

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#68]
When starting a simple program on ev3dev with no sensors attached the robot does nothing
- no error message
- no action
- blank display for a short time

it is requested to let the robot execute everything which is not against the configuration, like with lejos
![image](https://cloud.githubusercontent.com/assets/1613069/13407100/0261ca2a-df27-11e5-8c2e-1eee030ae657.png)

**Comment by ensonic** [comment]
Did you run:
```
sudo apt-get update
sudo apt-get dist-upgrade
```
on the ev3 recently? I released a new package last week that handles the exceptions regarding not conencted sensors in the config.

**Comment by bjost2s** [comment]
Thanks, this works, but it took more than one hour to execute this two commands!

**Comment by dlech** [comment]
The update took so long because debian did a point release since the last ev3dev image was release, so many packages were updated. In the future, to only update one package, you can run

    sudo apt-get update
    sudo apt-get install openrobertalab
