### ISSUE TITLE
Información borrada [Info deleted when is downloaded to the NXT via USB

### ISSUE THREAD

**Issue by adelmar1971** [OpenRoberta/robertalab#683]
Se escribe comentarios. Se guarda. Pero... cuando se descarga a la controladora NXT víaUSB, se pierde lo guardado.
Write comments. You save. But ... when it is downloaded to the NXT controller via USB, what is saved is lost.
It is the same problem reported but in this case it happens when it is downloaded to the NXT controller. https://github.com/OpenRoberta/robertalab/issues/668

**Comment by bjost2s** [comment]
Is it still a bug?
I' m not sure if we already have fixed it with #668
