### ISSUE TITLE
Run simulation from code directly?

### ISSUE THREAD

**Issue by DanTulovsky** [OpenRoberta/robertalab#685]
Hi.

Is it possible to run the simulator from code directly?  I am at a point where I want to write in code, rather than using blocks, but would love to be able to run the code through the simulator.  Is there an easy way to accomplish this?

Thank you
dan

**Comment by DanTulovsky** [comment]
This is for ev3dev/python specifically.

**Comment by ensonic** [comment]
We don't let the user edit the code right now, since there is no mapping of arbitrary code back to blockly. The simulator is based on the code structure defined by the blocks, so there is currently no way to run this for arbitrary code.

**Comment by bjost2s** [comment]
For the simulation we cannot use python (or java). Instead we generate lists of commands evaluated by javascript. So no way to use python or any other programming language. We also do not have a plan to support this.
