### ISSUE TITLE
 Open Roberta Create Agents for Chromebooks

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#686]
Is / Will the program also be available for Chromebooks?

**Comment by ensonic** [comment]
Unlikely. Maybe we can have something for newer chromebooks based on an android app, that offers the create agent service (see arduino/arduino-create-agent#130)

**Comment by bjost2s** [comment]
currently we are in the discussion if we want to use create agent in general, because of the self signed certificates for localhost and the browsers complaint.

**Comment by bjost2s** [comment]
Please reopen when there are new ideas.
