### ISSUE TITLE
Gallery view

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#689]
- Change double click to one
- Show menu button as gray-disabled, since it is actually disabled (this problem also occurs in program view)

**Comment by ensonic** [comment]
Can we add a way to filter per robot? This could be next to the search field.
Personally I'd like that when I open the gallery from the roberta-lab it would filter by default by the robot that I have selected.

**Comment by bjost2s** [comment]
We decided in the beginning of the gallery development not to do this. People should see more than their own environment and maybe filter it by solutions e.g. linefollower . Filtering is always possible for robot types in the search field.

**Comment by bjost2s** [comment]
nothing to do
