### ISSUE TITLE
Program with unregulated motors causes error on brick:

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#69]
Fehler im EV3  press any key

![image](https://cloud.githubusercontent.com/assets/1613069/13407228/92eac376-df27-11e5-809c-9394137854bd.png)

![image](https://cloud.githubusercontent.com/assets/1613069/13407236/9df59886-df27-11e5-90a6-c73c0bb49323.png)

**Comment by ensonic** [comment]
This was before you updated the libraries, right. Please reopen if still happens. I just tries it and it works.

**Comment by bjost2s** [comment]
Not working for me :-(. Maybe I have to update it again?

**Comment by ensonic** [comment]
I have done a lot of fixes and will push another update next week. I've tested it and it works. There was another bug in the codegen, that missed a quote for the "motor port x on speed" block. I need more tests for the codegen :)
