### ISSUE TITLE
program links are broken

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#690]
1. open a program from the galery
2. select "create program link" from the file menu
3. open a new tab/window and paste the link

I get an error `».xml« is not a valid NEPO program and cannot be uploaded!`

**Comment by labcode-de** [comment]
That's also if you create a program link on the robots:
- Calliope
- BOB3

**Comment by labcode-de** [comment]
And this bug is only if you choose one program which is build for one of these robots
