### ISSUE TITLE
Functions renaming themselves

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#692]
If you place these three blocks in a certan order (from top to bottom) and open the simulation, the called function "doSomething" will rename itself to "doSomething2":

1. 
![grafik](https://user-images.githubusercontent.com/25958792/32667287-9464b5da-c63a-11e7-86f8-dc380e296694.png)

2.
![grafik](https://user-images.githubusercontent.com/25958792/32667326-b0cfcb06-c63a-11e7-99cb-45fd10b13953.png)

3.
![grafik](https://user-images.githubusercontent.com/25958792/32667349-c0c8a37a-c63a-11e7-88b8-605e06534715.png)

This behavior only occurs under certain circumstances:
- the default name of a function in the currently selected language mustn't have any spaces (so only german and english are concerned)
- the base function (2.) has to have the default name of a function of that language
- the other function (3.) has to start with that default name and continues with a attachment of any kind (in this example the number "2")
- the blocks are placed in one of the following orders: 
 -132
 -312
 -231

The genarted code seems unremarkable.

**Comment by elhele** [comment]
It also changes the name if try to upload the program, so it is not only simulation issue.

**Comment by elhele** [comment]
It is a purely blockly bug that was already fixed. In a blockly repo a year ago it was also broken in the same way. So, to fix it we need to update blockly.

**Comment by bjost2s** [comment]
it is a blockly bug, but we have created our own renaming process. So we will fix it in our way, so no need to update to blockly which we definitly can't do for the next release ( and don't want to)
