### ISSUE TITLE
Sound sensor implementation for EV3

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#694]
Implement sound sensor blocks for EV3.

**Comment by bjost2s** [comment]
I have moved this issue to TODO, because I couldn't find an implementation for ev3dev. 
Please also implement it there.

**Comment by ensonic** [comment]
The soundSensor should be already supported:
https://github.com/OpenRoberta/robertalab-ev3dev/blob/develop/roberta/ev3.py#L140
I need to find one to test it though and check the the code-generator makes the blocks.

**Comment by ensonic** [comment]
The sound-sensor block reads "get value sound sensor port 1", should this be "get level sound sensor port 1". Also in German we could call it "Gib Lautstärke Geräuschsensor Port 1".

**Comment by boonto** [comment]
Now it says "get sound % sound sensor" and "Gib Geräusch % Geräuschsensor" in german which doesnt sound right. I think value/Wert or level/Pegel are both better.

The ev3dev implementation currently returns negative dB values, can you map them to the 0-100 range?

**Comment by ensonic** [comment]
> The ev3dev implementation currently returns negative dB values, can you map them to the 0-100 range?
With 0 for quiet and 100 for loudest? The db-scale is kind of open ended.

**Comment by boonto** [comment]
I think for children its more intuitive the other way round: 0 being silent and 100 being loud.
