### ISSUE TITLE
lejos 0.9.0-beta update not successfull

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#695]
The update process does not work. I am constantly being asked to update the EV3 - the lejos system.  Even after I agreed to the update.

OR: 2.3.0
EV3Runtime: 2.3.0
leJOS: 0.9.0-beta

**Comment by bjost2s** [comment]
fixed directly on the public server. We need to create a more flexible update functionality!

**Comment by bjost2s** [comment]
fixed in #711
