### ISSUE TITLE
The message key tests are only working partially

### ISSUE THREAD

**Issue by philippmaurer** [OpenRoberta/robertalab#696]
Currently the tests, that test which keys are used in the robertalab / blockly project, are not exhaustive. 

The keys are extracted from the robMessage.js file and then each file is checked for an occurance of that string by simply using the Java `String.contains(String s)` function.
Due to the usage of message keys, the prefix **Blockly.Msg.** and optional **ORA_** are removed before that. 

This leads to the problem, that the message key **ORA_TOOLBOX_SAVE_ERROR** matches to the Java code `private static String TOOLBOX_SAVE_ERROR = "Hallo Welt!";`, which is wrong behavior.
The test also does not find keys, that are used in the code, but are not defined in the robMessage.js file.

**Comment by VinArt** [comment]
How do I run these tests? They do not seem to be JUnit tests.
