### ISSUE TITLE
Disordered parameters when using microbit getPixelValue(x,y) 

### ISSUE THREAD

**Issue by dr0i** [OpenRoberta/robertalab#713]
For example, doing `setPixelValue(0,2,1)` the pendant `getPixelValue(0,2,1)` wouldn't come with `1` as the result but with `0`. Changing the `x` with the `y` seems to do the trick but that's weired also the code-block says "get LED brightness x" while it's in fact `y`.

I use `lab.open-roberta.org` to code for `calliope mini`. Open-Roberta uses the [microbit-dal](https://github.com/lancaster-university/microbit-dal) library for the `micro:bit` robots . I would have expected the issue there but a quick look on their code seems ok for me, but I am no c++ programmer.

Here is the code-snippet of the `micro:bit` robot (which also doesn't work as expected):
```cpp
import microbit

microbit.display.set_pixel(0, 2, 1);
microbit.display.scroll(str(microbit.display.get_pixel(0, 2)))
```

**Comment by VinArt** [comment]
@dr0i thank you for reporting this bug.
Affected: mbed simulation
With real board it was working, please correct me if I am wrong.

**Comment by dr0i** [comment]
@VinArt ACK, real board working.

**Comment by dr0i** [comment]
I think, as 9d33010f4e04f30100feac3227cae36b9bece92d was reverted, this issue should be reopened.
