### ISSUE TITLE
Write Text does not clear display

### ISSUE THREAD

**Issue by patric30** [OpenRoberta/robertalab#714]
Writing text on the display is not clearing the display first which leads to black boxes if values are changing over time. This is not intuitive for beginners.

**Comment by ensonic** [comment]
This is mentioned in the docs and I'd say expected. How much should it clear? If you print "Hello" and then "I", both at (0,0) - the "I" is narrower and would only clear parts of the "H" if we'd clear the background.

**Comment by patric30** [comment]
I was thinking of the (0,0) as a grid/table on the display. Whenever I write to (x,y) this cell gets cleared completely independent of the width of the old text.

**Comment by bjost2s** [comment]
What about using the "clear display" block right before the "write text" block?
