### ISSUE TITLE
Simulation "for each item ... in list" not working in a loop

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#717]
beiliegendes Programm liefert in der Simulation: true false true   false true  . Darauf folgt nichts sichtbares.
Es sollte endlos angezeigt werden: true false true   true false true ...
Die Schleife "Für Wert aus der Liste" funktioniert auch in anderen Programmen nicht.

![image](https://user-images.githubusercontent.com/1613069/33525840-67705af2-d837-11e7-8d46-852531f1c64c.png)

**Comment by VinArt** [comment]
Which robot is this? For Ev3 simulation is funny, it actually stops and behaviour is "true-false-true-false-true"
![image](https://user-images.githubusercontent.com/3738015/33544672-f831f8b2-d8db-11e7-91ca-6154919452c2.png)

**Comment by bjost2s** [comment]
Simulation problems are usually not related to a specific robot type, especially if the block is a not robot related one.
