### ISSUE TITLE
Issues with Acounts (not logged in, duplicate entry on save)

### ISSUE THREAD

**Issue by jexp** [OpenRoberta/robertalab#719]
We have a number of oracle issues when using open-roberta

One is that kids can log in but not save their programs, it fails with a "duplicate entry" error when trying to save.

Another one is this "not logged in" issue that happens several times.

The user is logged in but the system thinks they are not, see below:

![open roberta lab](https://user-images.githubusercontent.com/67427/33596311-8fb6881e-d99b-11e7-8504-29c3764bc5f6.jpg)

**Comment by cvejoski** [comment]
Do you use the public version of the OpenRoberta Lab?

**Comment by ensonic** [comment]
FYI: ORA stands for OpenRobertA :)

**Comment by bjost2s** [comment]
trying to fix this, but when I am logged in I can always save programs etc. Any idea how to run into this issue?
