### ISSUE TITLE
Executing program on ev3dev causes display issue

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#72]
there is a strange collection of small letters/symbols on the ev3 display during executing this program
![image](https://cloud.githubusercontent.com/assets/1613069/13461431/926c6084-e081-11e5-9244-9c8eb98da2a4.png)

Here the same, but the issue disappears immediatly, then a little underscore is blinking at the same location 
![image](https://cloud.githubusercontent.com/assets/1613069/13461512/44d3abe2-e082-11e5-8bae-02f7f79c9375.png)

**Comment by bjost2s** [comment]
Maybe caused also by a wrong ev3dev version?

**Comment by dlech** [comment]
I don't think the ev3dev version puts the console into graphics mode or raw keyboard mode. The symbols you are seeing are probably escape codes from when keys were pressed in a previous program.

I have a python program with a proper-ish way to do this - well switching to graphics mode anyway. <https://github.com/dlech/ev3dev-photo-booth/blob/master/ev3dev-photo-booth.py>. The framebuffer and virtual terminal code should be made into separate libraries and integrated with ev3dev-lang-python.

**Comment by dlech** [comment]
I've actually started work on cleaning up the code for separate libraries. I haven't published it anywhere yet, so if anyone would like to take over working on it, let me know.

**Comment by ensonic** [comment]
I am turning off the cursor, but there seems to be indeed still some issue. I'll take a look next week.

**Comment by dlech** [comment]
Even if you turn off the cursor, you still have stdin echoing and stdout/stderr printing on the console. Any time you press a button, you will see things like `^[` printed on the screen.

**Comment by bjost2s** [comment]
Is this still an issue?

**Comment by ensonic** [comment]
Yes, I did not had time to work on this, but I'll move it to robertalab-ev3dev, since it is unrelated to the server.

**Comment by ensonic** [comment]
I just fixed it. Will release a new version of the package soon.
