### ISSUE TITLE
cast range end to integer

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#723]
When using a math block in a loop, we generate code like:
```python
for k0 in range(0, 10 / float(3), 1):
  pass
```
This will throw `TypeError: 'float' object cannot be interpreted as an integer`.
Instead we need to always round() or cast the result to integer.

**Comment by boonto** [comment]
I added rounding to all the parameters because with the "count with i from x while counter < x by x" block it was possible to change all of them, not just the range end, to floats.
