### ISSUE TITLE
Pop-up massage "Server not available"

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#724]
I would like to recommend that the pop-up message - server unavailable - is no longer displayed as a pop-up message. but to bring the note as "toast" - as long as the server is not reachable. 

![image](https://user-images.githubusercontent.com/19221359/33767120-af16e3e8-dc20-11e7-857d-586a484c2786.png)

**Comment by bjost2s** [comment]
I think that moving it to the toast will not really help, because if the connection is really lost, it will not be visible enough.
What about showing this message only if the problem pops up for the third (or maybe fifth) time one after the other?
