### ISSUE TITLE
"Run program" message is misleading for NXT and Calliope 2016

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#738]
to do, create a new message for systems that do not start downloaded programs automatically

**Comment by elhele** [comment]
Calliope is fixed, but NXT still shows "Your program >>NEPOprog<< will run in a moment!".
Then it shows the following: 
![image](https://user-images.githubusercontent.com/13983474/34940782-396e6ac8-f9f1-11e7-9791-8274696684a3.png)
May be we could say "press exit button" or "press exit button (*picture of the button*)", the picture of the button is a bit confusing, I thought that it is a thick "minus" sign first.
