### ISSUE TITLE
Improve program layout when printing programs from the browser's print function

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#739]
Some css for media print is  needed to only show the program

**Comment by elhele** [comment]
[mozilla.pdf](https://github.com/OpenRoberta/robertalab/files/1631266/mozilla.pdf)
a larger program doesn't fit into the printed page. May be it could be centered better.

**Comment by bjost2s** [comment]
this is the first step, for the next release we expect more improvements
