### ISSUE TITLE
Missing type conversion ManagedString to double (calliope enhancement)

### ISSUE THREAD

**Issue by kwollw** [OpenRoberta/robertalab#741]
![transmitter](https://user-images.githubusercontent.com/6341023/34950202-c70523c4-fa12-11e7-8d9f-0d034957e196.png)
fig 1: Transmitter

![receiver](https://user-images.githubusercontent.com/6341023/34950255-e8a9e8ca-fa12-11e7-86de-210762dbdbe6.png)
fig 2: Receiver

NEPO with calliope permits only sending and receiving of Strings.

Collecting numeric data and transmitting is possible due to the fact that a String can be build from numerical values. 
(fig1: BLOCKLY: create text with get value temperature sensor < >line 20: ManagedString(ubit.thermometer.getTemperature())

On the  receiver the handling of the received data is restricted to String operations because of the lack of type conversion.
(fig2: BLOCKLY: set (numeric variable) to ... received_msg < > line 25: temp_numeric = ...)

I suggest to implement a type conversion e.g. "create number with < String" into the group Math to make numerical operations on received data possible.

As an alternative solution the sending and receiving of numbers could be implemented.

**Comment by bjost2s** [comment]
We do not plan to offer a type conversion string, but we will extend the sending and receiving message block to accept numbers, see #750

**Comment by bjost2s** [comment]
please reopen, if needed
