### ISSUE TITLE
NXT: Adding "other power consumer" in robot configuration leads to server error

### ISSUE THREAD

**Issue by larspelz** [OpenRoberta/robertalab#743]
Adding "other power consumer" in the NXT robot configuration leads to a server error. 
I connected some RCX lights to the motor ports and thought they had to be configured as "other power consumer"s. The program wouldn't compile if only one "other power consumer" was configured in any of the three NXT motor ports.

**Comment by boonto** [comment]
For now I removed the "other power consumer" block from the configuration.
As the lights apparently work with "big motor" #744 you can keep using that. We will look into adding a functioning power consumer block in the future.

**Comment by larspelz** [comment]
Thanks a lot!
