### ISSUE TITLE
Interface for interactive tutorials for the different (robot) systems

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#751]
As a user I would like to start programming with NEPO guided by an interactive tutorial. As the main subject of the Open Roberta Lab is programming real devices / systems, the tutorial should have steps where I can observe my system and decide by my self, if my program fulfills the task. Also variants for the simulation are possible.
Basic parts:

- choose a tutorial
- follow the instructions of e.g. step 1
- check the result / outcome 
- answer a short quiz
- go to next step
- ....
- get credentials / badges / smilies ...
- go back to the normal environment and get a hint, that you can save / export your program now

**Comment by bjost2s** [comment]
The functionality is ready and we are waiting for some feedback from the designers, also real tutorials are not available. Will be reopened if the work on it will be continued

**Comment by bjost2s** [comment]
Here c342b2e909ede23b4934694262afdd650f1f095f we have disabled the dir listing, so it is also forbidden on client side. The lookup in the corresponding folder has to move to the server side (init REST call).

**Comment by bjost2s** [comment]
With the last commit I've also added getting available help file names, so that the client in best case does not run into the  404 (Not Found) error anymore.

**Comment by rbudde** [comment]
For ev3 there is a tutorial overview available as a tutorial. This should not be deployed in the productive code. Or should it?

**Comment by rbudde** [comment]
BTW: in step 3 only 2 blocks are allowed (text says 4)

**Comment by bjost2s** [comment]
![image](https://user-images.githubusercontent.com/1613069/39562402-cde71772-4eab-11e8-9fe9-905bf6ac9373.png)
Blockly counts each block, not steps, so in the image abouve one can see 4 blocks, start, drive forward, math 30 and math 20.

**Comment by rbudde** [comment]
Wow. This is counter-intuitive.
Tutorials ok.
