### ISSUE TITLE
Arduino (Uno, Mega, Nano, etc.) configuration

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#756]
Configuration for the board from issue #745 
As an option -- extension of Botnroll configuration in such a way that it would be possible to use its Arduino ports.

- [x] Add a new configuration block that will not be connected to anything and used only for Arduino board choice (Uno, Mega, Nano). Board is chosen from a list in the block's dropdown:

![arduino choice](https://user-images.githubusercontent.com/13983474/36032779-5fb55f6c-0daf-11e8-82d9-b3a648ba7de7.jpeg)

- [x] Add/modify configuration sensors and action blocks so they would not be connectable and would contain the following:

- Sensor type;
- Sensor name input field;
- Sensor pin names with dropdowns containing numbers of pins to which they are connected.

![screenshot from 2018-02-09 15-40-13](https://user-images.githubusercontent.com/13983474/36033158-7870fc72-0db0-11e8-9573-430b8a5c477e.png)

- [x] Generate code for configuration #840

- [x] Synchronize configuration blocks' names with the list of block names in program blocks -- similar to variables. #833

- [x] Synchronize pin values with the chosen Arduino board.

- [x] Fix configuration toolboxes (sensors, action) in arduino.properties

- [ ]  Add  a picture with Arduino board that will be changing according to the chosen sensors: when a sensor is added to configuration it also appears on the picture with Arduino connected to the corresponding pins.

Usage:

In order to use sensors with Arduino one should connect pins of the sensors to the corresponding pins of the Arduino board. An example of such connection is shown below:

![arduinoconnection](https://user-images.githubusercontent.com/13983474/36033331-04cbb310-0db1-11e8-9901-549300d3ec8d.jpeg)

Our implementation of these connection is based on blockly library and that is why the connections can be created by users in the following way:

1. User is in the configuration tab. First user should press on the dropdown of the main Arduino block and choose his/her Arduino board from the list:

![screenshot from 2018-02-09 16-01-19](https://user-images.githubusercontent.com/13983474/36033988-cdff0cfe-0db2-11e8-8bd1-43a45d3798dd.png)

This will define which digital and analogue pins can be used in the configuration.

2. To connect a new sensor or actuator user presses "sensors" of "actors" correspondingly:

![screenshot from 2018-02-09 16-08-37](https://user-images.githubusercontent.com/13983474/36034378-34f6b3d4-0db4-11e8-80cd-e9b8f0a29f87.png)

There user can choose the needed actuator or sensor. To "attach" it to Arduino user drags it to any place in the configuration workspace and then chooses the correct Arduino pins in the dropdowns by the corresponding sensor pin name:

![arduino_sensorsactors](https://user-images.githubusercontent.com/13983474/36034606-de8e661c-0db4-11e8-8da6-e2bba65807e6.jpeg)
 
That is it. The actuator or sensor is connected to Arduino. For example, connection below:

![image](https://user-images.githubusercontent.com/13983474/36035135-5794629a-0db6-11e8-9d6c-ebb6e45682ab.png)

corresponds to the following configuration on real Arduino:

![led-rgb](https://user-images.githubusercontent.com/13983474/36035016-03ab9888-0db6-11e8-93d4-2e53d927c63f.png)

**Comment by rbudde** [comment]
the description of the issue is very understandable.
