### ISSUE TITLE
index.html und require.js

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#76]
the main entry file `index.html` contains the lines
```
<script type="text/javascript" src="js/app/simulation/robertaLogic/constants.js"></script>
<script type="text/javascript" src="js/app/simulation/robertaLogic/program.builder.js"></script>
<script type="text/javascript" src="js/libs/code-prettify/prettify.js"></script>

<script data-main="js/main" src="js/require.js"></script>
```
at least the first two scripts (we own) should be loaded with require. The last one is code supplied by others, but loading with require would be much more robust and safe.
Btw: it would nice to cleanup `index.html`.

**Comment by cvejoski** [comment]
When we put in require there are some problems with loading the prettify. Next week I will work more on cleaning the client side code and loading all js files with require

**Comment by ensonic** [comment]
I'll change the pretty.js part to use require.

**Comment by bjost2s** [comment]
I think this is fixed, please confirm and close, if so

**Comment by ensonic** [comment]
two files still need to be converted:
https://github.com/OpenRoberta/robertalab/blob/develop/OpenRobertaServer/staticResources/index.html#L28_L30

**Comment by bjost2s** [comment]
we discussed to remove pace.js and convert the functionality to pure css

**Comment by bjost2s** [comment]
pace.js and dependencies are removed, needs some testing on safari etc
