### ISSUE TITLE
the message is misleading

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#778]
![image](https://user-images.githubusercontent.com/1613069/36846811-6b87e230-1d5c-11e8-8490-b8d39891ed38.png)

**Comment by rishabhdeepsingh** [comment]
@bjost2s Can u tell us how did u get this bug?

**Comment by ensonic** [comment]
* you need to log in
* switch to the configuration tab
* select the file menu on the top-left and save-as
* there you enter e.g. "EV3-" and press Tab
This should get the error "Please fill in a correct name. A correct name begins with a letter and can only contain letters or numbers."

**Comment by rbudde** [comment]
the message is now correct (but needs a bit of interpretation)
