### ISSUE TITLE
Blocks collapse after clicking "run" while in code view

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#779]
Let us consider the following program:
![image](https://user-images.githubusercontent.com/3738015/36899087-d226a686-1e1d-11e8-8824-1c837cd32676.png)

If "run" is clicked at this stage with no code view open, program compiles.

After opening code view and clicking "run", the following happens:
![image](https://user-images.githubusercontent.com/3738015/36899127-04646f3e-1e1e-11e8-9dd2-1db42d9aa98f.png)
Note the collapsed blocks without block images (text only) on the left of the picture above

After closing and opening code view, blocks restore, but they are scrambled:
![image](https://user-images.githubusercontent.com/3738015/36899174-382da664-1e1e-11e8-91cf-24e9b7e911de.png)

And the problem now is that item2 block will not be attachable in display image block, like if the type is mismatching if the new display image block is dragged out of the toolbox, because the original one is missing:
![image](https://user-images.githubusercontent.com/3738015/36899223-777dbf02-1e1e-11e8-857d-c5b196ff2b8d.png)

**Comment by bjost2s** [comment]
this problem exists not only for calliope/mbet.
