### ISSUE TITLE
 Color sensor detection boundary is not clear

### ISSUE THREAD

**Issue by lccopp** [OpenRoberta/robertalab#782]
![1](https://user-images.githubusercontent.com/34764041/37140714-adb7cee0-22ed-11e8-893f-6f88d4e85583.png)
In this case, there is no grey, but the gray was detected.
![2](https://user-images.githubusercontent.com/34764041/37141889-74e68332-22f1-11e8-9ffc-cd6ab63de5c1.png)
In this case the ground line is black, but I need to use grey to make it run.

**Comment by bjost2s** [comment]
Sorry for this. Grey is not grey but no colour. Unfortunately there is no way to label it differently then grey. The simulation is here close to the real color sensor which is returning a colour or if no colour could be detected, none. In your example the sensor is over yellow and white which results in no colour.

For your project, line following, you should use the light mode from the colour sensor which is returning grey values from 0 (dark) to 100 (bright).

**Comment by bjost2s** [comment]
Please reopen, if you have further questions
