### ISSUE TITLE
Codegeneration "for each loop" in botn'roll, NXT and bob3 is wrong

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#783]
![image](https://user-images.githubusercontent.com/1613069/37254011-8ca0fe54-2539-11e8-9dda-827aa78d936e.png)

This issue is popped up with the fix for #779. Please activate the test again, once this issue is fixed and a better testcase is found https://github.com/OpenRoberta/robertalab/blob/922e704ef6de880892331ab406fd4585a2a49d94/OpenRobertaParent/RobotArdu/src/test/java/de/fhg/iais/roberta/syntax/codegen/arduino/botnroll/CppVisitorTest.java

**Comment by VinArt** [comment]
- NXT fixed in #1050 
- bob3 fixed due to #1015 
- botnroll fixed due to #1015
