### ISSUE TITLE
if then else + causes compiler error, only IE!

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#786]
![image](https://user-images.githubusercontent.com/1613069/37331921-9d1b4858-26a5-11e8-9397-07e57a2c4c0e.png)
![image](https://user-images.githubusercontent.com/1613069/37332000-cea1f426-26a5-11e8-93a9-f087329ff1d1.png)

**Comment by rbudde** [comment]
works as expected.
