### ISSUE TITLE
position of info button is not right

### ISSUE THREAD

**Issue by lccopp** [OpenRoberta/robertalab#796]
![1](https://user-images.githubusercontent.com/34764041/37568053-e21ae67a-2b0a-11e8-84c2-fb05f2356c7d.png)
when I click the button of code view , the button of info view stay in that position

**Comment by bjost2s** [comment]
interesting, how did you managed to click on the code view button while the help view is opened?

**Comment by lccopp** [comment]
When I click on the code view button, the information popped was loading slowly. And the button of info view was moved together. then it stayed there. I think maybe at that time my network was not good. I was trying many times but not saw this case again.

**Comment by bjost2s** [comment]
Please reopen, if it is reproducable!
