### ISSUE TITLE
Arduino break/continue loop in wait until block is not working as expected

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#800]
seems that working cpp implementation in the robot project is overwritten
![image](https://user-images.githubusercontent.com/1613069/37664196-183ce216-2c5b-11e8-8d01-e484c03e58c1.png)

**Comment by bjost2s** [comment]
@cvejoski could you please work on it?

**Comment by rishabhdeepsingh** [comment]
@bjost2s I find a Solution we need to return from the Function as break will only break the last loop and you are using two infinite loops. So returning from the function will solve the issue.
I will send a PR Regarding this.

**Comment by cvejoski** [comment]
@bjost2s yes I am on it

**Comment by elhele** [comment]
Not resolved. When uploading program, it returns the following error:
"/tmp/userProjects/4cNN_Qa-_7t3/NEPOprog/src/NEPOprog.ino: In function 'void loop()':
/tmp/userProjects/4cNN_Qa-_7t3/NEPOprog/src/NEPOprog.ino:34:5: error: expected primary-expression before '}' token
     }break_loop2:
     ^
exit status 1"
