### ISSUE TITLE
Simulation Robot and Sensor boxes overlay in gallery and configuration

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#801]
If simulation is opened and robot view and/or sensor view is opened and after gallery or configuration is selected, the aforementioned views persist.

![image](https://user-images.githubusercontent.com/3738015/37708597-85f60376-2d07-11e8-9905-e7d1eb3c7143.png)
![image](https://user-images.githubusercontent.com/3738015/37708607-90bac148-2d07-11e8-81a9-16d10a6744a2.png)

**Comment by bjost2s** [comment]
already mentioned and fixed with #795
