### ISSUE TITLE
Robot can leave simulation arena

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#802]
It is possible to drive the robot outside of the simulation arena under certain conditions, like putting it on the edge/hazard line

![image](https://user-images.githubusercontent.com/3738015/37708848-7189e06e-2d08-11e8-8507-4cbd04d396f7.png)

Note Robot X coordinate

**Comment by rishabhdeepsingh** [comment]
@VinArt  Can u tell me how did u make the robot go outside the Simulation Area?

**Comment by bjost2s** [comment]
This is a special realtime simulation. The robot cannot go out of the room when the door is closed, but if you carry it out of the room, it is out of the room. Definitely the robot cannot go outside the walls by itself. I think that is sufficient.
If you don't agree, please provide some ideas where to place it when it is set outside via the mouse.
