### ISSUE TITLE
Calliope "is prime" and "is whole" not working

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#803]
![image](https://user-images.githubusercontent.com/7438960/37716015-cc382628-2d1d-11e8-81b2-a0f64656c3fd.png)
Both functions of the math prop block generate uncompilable code.

**Comment by elhele** [comment]
Still doesn't work for me on Calliope 2016:
![image](https://user-images.githubusercontent.com/13983474/38301165-1060f438-37ff-11e8-81a3-4d338c38cad2.png)
Calliope 2017 seems to be fine.

**Comment by Fr4n2** [comment]
Version 2.7.1
the "prime"-block is not properly working.

Works in simulationmode
but cannot download to calliope
![prime](https://user-images.githubusercontent.com/36298448/42080870-4aefada6-7b84-11e8-9998-1d2765675519.jpg)

"iswhole"-block is working
