### ISSUE TITLE
Nao communication interface

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#804]
Currently Nao communicates via the Nao program with the lab server, but Nao is capable to communicate directly to the lab server similar to how EV3 is doing it via Wifi.

As a user I would like to activate the communication between Nao and the lab server via an app from the Nao's app store. Once one ordered the Open Roberta app it will be installed on Nao, so that Nao connects to the server automatically. 
* Nao (the interface) creates a token (parts of the mac adress) and sends it to the lab server
* the user can ask Nao to speak out the token via an event (to discuss with Softbank)
* the user provides the token in the GUI to establish the connection

**Comment by bjost2s** [comment]
@VinArt please attach here the sequence diagram, to show the interactions between server, GUI and Nao

**Comment by VinArt** [comment]
Also a diagram that roughly shows how the client on NAO works:
![nao_client](https://user-images.githubusercontent.com/3738015/37817702-f021c8f4-2e77-11e8-91c4-2fd49b672160.png)
