### ISSUE TITLE
Block redundancy for Calliope Motors

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#807]
![grafik](https://user-images.githubusercontent.com/25958792/37828570-119ea2ee-2e9c-11e8-9a33-6e992ac15505.png)

**Comment by bjost2s** [comment]
What exactly is the problem here?

**Comment by cvejoski** [comment]
The problem is that the mode is not taken into account when we use 2 motor. This is so because, the microbit library does not support modes in stopping the motors in dual motor mode only in single.

We should remove the mode from the stop block

**Comment by rbudde** [comment]
works as expected.
