### ISSUE TITLE
ast issue with foreach loops

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#81]
While adding a test for "/syntax/stmt/forEach_stmt.xml" I noticed that it would generate bad code for both python and java:
```python
for variablenName2 = in variablenName:
    hal.drawText(str(variablenName2), 0, 0)
```
```java
for (PickcolorvariablenName2 = 0 : variablenName) {
      hal.drawText(String.valueOf(variablenName2),0,0);
}
```
The problem seems to be that the expression in the loop that is processed in visitVarDeclaration() is not BlockType.EMPTY_EXPR.

**Comment by cvejoski** [comment]
Yes, I have created this bug with the implementation of the shadow block
