### ISSUE TITLE
Toolbox representation in .properties files

### ISSUE THREAD

**Issue by VinArt** [OpenRoberta/robertalab#810]
Currently toolboxes are written directly to robot properties file as a single line XML this is not convenient to work with and sometimes leads to errors.

It would be better to move this XML to a separate file and format it accordingly. The other idea is to make a textual representation of the toolbox (e.g. yaml or json) and a translator to XML for blockly usage.(thank you @rbudde)

**Comment by bjost2s** [comment]
I would prefer yaml for this
