### ISSUE TITLE
Will be stuck when opening a webpage

### ISSUE THREAD

**Issue by MRNIU** [OpenRoberta/robertalab#819]
[robertalab's web site](https://lab.open-roberta.org), every time I open it will display a window "Attention" and I can't close it, so I have to Refresh the page. My Web browser is Safair.

**Comment by rishabhdeepsingh** [comment]
Can u share the Screenshot of it?

**Comment by VinArt** [comment]
Could you also traceroute till lab.open-roberta.org? it might be timing issues.

**Comment by MRNIU** [comment]
The Screenshot @rishabhdeepsingh 
![2018-03-27 12 15 34](https://user-images.githubusercontent.com/12967882/37946618-e275e106-31b8-11e8-803a-e2ff7ff4ec84.png) 

Still not working, but this page in Chrome were all right.
@VinArt 

Thanks you.

**Comment by VinArt** [comment]
I am not sure what I am looking at, but am I correct to see pings up to 0.8 seconds?

**Comment by MRNIU** [comment]
It's a successful  example
![2018-03-27 20 29 26](https://user-images.githubusercontent.com/12967882/37967391-c578959a-31fd-11e8-9948-4a3348fdbaea.png)

And it's a failing
![2018-03-27 20 29 53](https://user-images.githubusercontent.com/12967882/37967496-2462acd0-31fe-11e8-9a0a-32375e322105.png)

Their request is different, is this the cause of the problem?

Now that I can visit normally, maybe there is a reason for the time.
