### ISSUE TITLE
german color names in the code base

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#82]
See
https://github.com/OpenRoberta/robertalab/blob/HEAD/OpenRobertaShared/src/main/java/de/fhg/iais/roberta/shared/Pickcolor.java#L11-L17

We probably want to find a different way, if those are needed at all. Please also clarify the value 'NONE'. This is used in testing, but to me is a bit of black magic.

**Comment by cvejoski** [comment]
The german names of the color are from old version of the blocks and I have removed them. The ev3 color sensor returns 'NONE' color when cannot detect exactly the color.
