### ISSUE TITLE
Web browser going slow when clicking on the code tag

### ISSUE THREAD

**Issue by MRNIU** [OpenRoberta/robertalab#820]
I noticed that the code tag is very slow when I click on it, and make my computer stuck sometime, maybe we can do some optimization here.

**Comment by ensonic** [comment]
Do you see any warning in the developer console? Which browser/os are you seeing this on?

**Comment by MRNIU** [comment]
Thanks. This is the Screenshot, and it's all right in Chrome.
my info: macOS High Sierea, Safari

![2018-03-27 12 46 11](https://user-images.githubusercontent.com/12967882/37947373-50245b84-31bd-11e8-80e7-7b92f25874bf.png)

**Comment by bjost2s** [comment]
We know that many people from China have problems to access the Open Roberta Lab. The messages in the console are not reproducable for us, unfortunately.
Maybe it is a problem with High Sierra, I will try to find a device next week to test this in detail.

**Comment by MRNIU** [comment]
So unlucky. Thank you for your help.
