### ISSUE TITLE
Different spelling - German

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#824]
![image](https://user-images.githubusercontent.com/19221359/38026587-edad500c-328c-11e8-8aa9-fe5df5f04674.png)

Wiederhole unendlich oft - Capital letter
wiederhole 10 mal - lower case

**Comment by bjost2s** [comment]
We should think about updating the german translation of blockly. This will fix errors like this, but also change wordings like "Blöcke" -> "Bausteine"

**Comment by Thorlogy** [comment]
I think we should change all wrong translation, without changing wordings like Blöcke -> Bausteine. We assured our partners that we are not change important wordings.
