### ISSUE TITLE
Function/Procedure that start with a Comment - Exec-Problem in Simulator ?

### ISSUE THREAD

**Issue by faenvie** [OpenRoberta/robertalab#834]
This is Open-Roberta Release 2.6.1 for Calliope 2017. Function/Procedure that start(s) with a Comment do not execute properly in the Simulator. May it be possible, that one of the latest Changes causes this ? I am not sure, but i think, that it worked before(days ago).

`
void blinkLED() {
        // LED (kurz) blinken lassen

        uBit.display.image.setPixelValue(2, 2, 5 * _SET_BRIGHTNESS_MULTIPLIER);

        uBit.sleep(50);

        uBit.display.clear();
}
`

**Comment by bjost2s** [comment]
Thank you, we will have a look at this asap

**Comment by rbudde** [comment]
Comments in main and function decls work as expected.
