### ISSUE TITLE
"Show Sensor Data" issue on EV3 Lejos 0.9.1 

### ISSUE THREAD

**Issue by a-pasquale** [OpenRoberta/robertalab#836]
With the 2.6.1 update, programs no longer run if the "Show Sensor Data" option is checked. Programs seem to work fine if not using any sensor blocks. If using sensor blocks, code executes if the checkbox is unselected. 

Let me know if more information is needed. Thank you!

**Comment by bjost2s** [comment]
Thank you very much for this bug report. We will check it asap (tomorrow).

**Comment by bjost2s** [comment]
We figured it out, there will be a hotfix today, maybe tomorrow that will fix this issue. You will have to update your robot again, but than it will work as expected

**Comment by a-pasquale** [comment]
Thank you!
