### ISSUE TITLE
Blocks are moving when switching tabs or views

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#837]
This does not happen all the time, but the problem is, that we reload the blocks each time we switch the tabs. Reloading the blocks is only possible when they are stored before switching. For connecting program workspace and configuration workspace (Arduino) this is not a good workflow. We will change the blockly workspace to become a resizable workspace so that blocks doesn't have to be reloaded each time.

**Comment by rbudde** [comment]
I found no visible difference between old and new behavior (this seems to be expected as the issue is a kind of refactoring).
