### ISSUE TITLE
EV3 WiFi settings are lost after restart

### ISSUE THREAD

**Issue by spidgorny** [OpenRoberta/robertalab#839]
Every time I start an EV3 brick I need to select a WiFi network and enter the password. Is this not supposed to be saved to the SD Card and resused after reboot?

**Comment by bjost2s** [comment]
Could you please tell us what firmware you use?

**Comment by spidgorny** [comment]
I've updated to 2.6.0 and it works now. Thank you. Issue can be closed.

**Comment by bjost2s** [comment]
Thanks
