### ISSUE TITLE
Infinite loop in simulation

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#841]
![image](https://user-images.githubusercontent.com/15834363/38620455-ca41ec8c-3d9e-11e8-945c-69f5bc96e73a.png)
terminates on the "real" Calliope2017 as expected. Simulation loops infinitely. A loop w.o. nesting does work as expected.

**Comment by rbudde** [comment]
the bug hits every simulator.

**Comment by bjost2s** [comment]
working as expected, tried 5 nestings
