### ISSUE TITLE
Provide missing sensor values for the executing program in simulation

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#85]
#29 
Ultrasonic sensor distance: cut at 255 (like the real sensor)
Ultrasonic sensor presence: false
Infrared sensor distance: cut at 70 and map to 0 - 100 (approx. like the real sensor)
Infrared sensor presence: false
Gyro sensor: rate and angle, reset will be handled in the executing part
EV3 buttons: 6 pressed or not

**Comment by ensonic** [comment]
What about moving this to #28

**Comment by bjost2s** [comment]
I think #28 and #29 are nearly the same, so I connected it to #29, but now we have also a link to #28

**Comment by bjost2s** [comment]
done
