### ISSUE TITLE
GainNode.gain.value setter smoothing is deprecated

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#855]
Appears when opening the simulation, because the function is used for simulating tones.
![image](https://user-images.githubusercontent.com/1613069/38884878-4961e9aa-4271-11e8-8387-2554ecbe5fc1.png)

**Comment by rbudde** [comment]
I can't see the console messages, thus issue not yet closed.

**Comment by bjost2s** [comment]
Please open the simulation of either NXT or Calliope, both are using the microphone and will show you the messages. For EV3 there is no support of the sound sensor (because it is not standard) so the message won't show up.
I add nxt and calliope as labels

**Comment by rbudde** [comment]
OK.
