### ISSUE TITLE
Add Grove LED-Bar v2.0 to Calliope

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#862]
Add the [Grove Led Bar v2.0 by Seeed](https://www.seeedstudio.com/Grove-LED-Bar-v2.0-p-2474.html) [(Wiki)](http://wiki.seeedstudio.com/Grove-LED_Bar/) to the lab.
- [x] Libraries
- [x] Blockly
- [x] Code generation
- [x] Tests

**Comment by rbudde** [comment]
code generation works. No simulation available. Without sensor no test on the robot possible.
