### ISSUE TITLE
Robot configuration not available

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#869]
Using Open Roberta Lab on my smartphone - the robot configuration menu is not available when i use landscape format:
![image](https://user-images.githubusercontent.com/19221359/39426922-0b94fdfe-4c82-11e8-9c10-0e5a30583a5d.png)

upright format it is:
![image](https://user-images.githubusercontent.com/19221359/39426913-00bc6d72-4c82-11e8-975c-0ec8927f9906.png)

Browser: Chrome 66.0.3359.136
OS: Android 8.1

**Comment by rbudde** [comment]
Size calculation is working on my S6 (... but is slow ...)
