### ISSUE TITLE
Default Motor port "B" vs "A"

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#870]
Is there a reason why motor port B is set by default (in section 2, category "move")? And motor port A is set within the block "stop motor" ?

![image](https://user-images.githubusercontent.com/19221359/39427304-95faf72c-4c83-11e8-89cb-ff12028a311c.png)

**Comment by bjost2s** [comment]
A is a "bug", we have chosen B because this is the first connected motor in the standard configuration.
I will change this also to B.

**Comment by rbudde** [comment]
now "B" is used consistently.
