### ISSUE TITLE
Simulation: NXT Colour sensor doesn't return anything

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#872]
![grafik](https://user-images.githubusercontent.com/25958792/39524167-65017556-4e18-11e8-8d39-685bcb39c51f.png)
Eventhough the Sensors' data view shows the right color, the programm itself doesn't recieve anything and the Display stays empty:
![grafik](https://user-images.githubusercontent.com/25958792/39524414-2ffbcce8-4e19-11e8-8c19-8599db47cdff.png)

**Comment by boonto** [comment]
As different NXT packages were sold (one with a light, one with a colour sensor) we should allow changing the configuration for the simulation in this case. This should enable users to change to a colour sensor and use it in the configuration.
