### ISSUE TITLE
Toolbox width varies

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#873]
The menu width varies in the selection -2 Advanced - -Control- 
Language: selection German 
Browser: Chrome, Safari, Firefox

When Control is clicked, the menu moves slightly to the right (widens).

This "behavior" does not happen in English. Not even when clicking on -Action-. 

![image](https://user-images.githubusercontent.com/19221359/39618888-f72229f8-4f85-11e8-8cb9-b9b291d83ff0.png)

**Comment by bjost2s** [comment]
This is caused by the longest name of subcatagories "Entscheidungen". It doesn't fit into the given space from the collapsed catagories.
This is intended and won't be changed.
