### ISSUE TITLE
Import xml-Program

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#880]
The first attempt to import a xml Program (EV3, Calliope,...) does not work. 
The second attempt always works.

Browser: Chrome

**Comment by elenadorogush** [comment]
I've just tried to reproduce this, but XML program import for EV3dev worked fine on the first try. My Chrome version (chrome://version) is 67.0.3396.87.

**Comment by bjost2s** [comment]
this is already solved with #874 @Thorlogy ,@elenadorogush could you please both test it at https://test.lab.open-roberta.org and give feedback?
Thank you

**Comment by Thorlogy** [comment]
works. But often the start-block moves and sometimes the whole program is shiftet like following example:

![image](https://user-images.githubusercontent.com/19221359/41846569-5eb09dec-7877-11e8-8378-68b98109d02d.png)

**Comment by Thorlogy** [comment]
here you go:
Program for Calliope 2017:

[Schere.zip](https://github.com/OpenRoberta/robertalab/files/2135719/Schere.zip)
