### ISSUE TITLE
Confusing Error message "Robot does not wait for a run command"

### ISSUE THREAD

**Issue by lotu** [OpenRoberta/robertalab#891]
Sometimes, (I have not been able to isolate the exact cause) when running a program on an EV3 robot (I have only tested EV3) this error message appears.  "Attention; The robot does not wait for a run command.  <OK>".  

This error message is totally non-actionable by the user, (their is nothing the user can do to fix it).  it It is confusing I as an engineer and teacher don't understand what it means, other than "try pushing play again".  Students who see it are confused, they think they did something wrong and the robot is broken.  This is discouraging.

Solutions: Reword the text so it is clear to developers, teachers and especially students who have little understanding of engineering behind the system.  Include why this time was different from other times the play button was pressed and explicit instructions of what to do next.

**Comment by pablopoo** [comment]
for me, the most important part missing in the original message is the "try again". At least, trying again worked when a users saw this error message.
