### ISSUE TITLE
Need a way to store assets with a program

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#90]
OpenRoberta/robertalab#89 asks for custom simulation maps. Also for the showPicture() and playFile() blocks, it would be nice to be able to have custom assets.

In the java case we could have them in the jar, but that would make the uploaded slower - ideally we only send them as needed. So for java we could have a prog.jar and prog-data.jar.

In python we'd include them as a module. The module can be built-in or a separate file.

If we go for separate files, we can upload them as needed.

Especially on ev3dev I'd propose to use a hidden $HOME/.roberta directory to not clutter the file-view. So the layout would be:

```
$HOME/
  program1.py
  .roberta/
    program1-data/
       program1.xml
       picture.png
       sound.wav
    program2-data/
      program2.xml
```

We need to expand the push protocol to check if an asset is already uploaded (use a content digest) to avoid re-uploades.

We can also use this to eventually offer to load programs back from the robot (e.g. great for users without an account).

**Comment by ilovefroyos** [comment]
Hi @ensonic :) ! I'm an undergraduate student at The University of British Columbia studying computer science, and I'm interested in contributing to Open Roberta Lab for GSoC. Has this issue already been claimed/assigned/addressed for/by any other applicants?

**Comment by rbudde** [comment]
GSOC project
