### ISSUE TITLE
EV3 USB Programm for Mac not working

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#901]
After downloading and starting the recommended program https://github.com/OpenRoberta/robertalab-usbprogram/releases 

Following Massage appears:
![image](https://user-images.githubusercontent.com/19221359/40832402-8a2d8be6-658b-11e8-91de-3a9383e899d8.png)

Mac OS:
![image](https://user-images.githubusercontent.com/19221359/40832453-a87531da-658b-11e8-81a3-cce762e1ca31.png)

**Comment by VinArt** [comment]
<img width="960" alt="macos" src="https://user-images.githubusercontent.com/3738015/40842537-80017ccc-65ae-11e8-841f-270555bd7b4f.png">

**Comment by bjost2s** [comment]
@Thorlogy could we please have your macbook to make some tests next week?
As you can see above, ours is working.

**Comment by Thorlogy** [comment]
Yes - on Monday.

**Comment by bjost2s** [comment]
Could you please also copy and paste the content of the file Users/thorstenleimbach/OpenRobertaUSB/OpenRobertaUSB.log

**Comment by Thorlogy** [comment]
01/06/2018 10:03:22.399 - [de.fhg.iais.roberta.usb.Main.configureLogger] - [INFO] - Logging to file: /Users/thorstenleimbach/OpenRobertaUSB/OpenRobertaUSB.log
01/06/2018 10:03:24.408 - [de.fhg.iais.roberta.usb.Main$1.getLocals] - [CONFIG] - Language de
01/06/2018 10:03:24.412 - [de.fhg.iais.roberta.connection.EV3USBConnector.<init>] - [CONFIG] - Robot ip 10.0.1.1
