### ISSUE TITLE
Import EV3 Lego IDE files

### ISSUE THREAD

**Issue by MagicMarvMan** [OpenRoberta/robertalab#911]
Hello.

It would be cool if we could import the files generated by the original Lego Mindstorms EV3 IDE to the lab. So I can transform my `.ev3` files to Roberta Projects.

Thank you,
MagicMarvMan

**Comment by bjost2s** [comment]
I am very sorry, but this is not what we want to offer our users. Although technical possible we would like the users to learn with NEPO. So if they have already programmed with Lego Mindstorms EV3 IDE it should not be a big thing to rewrite the program in the Open Roberta Lab with NEPO. Just give it a try, it is a good exercise ;-)

**Comment by ensonic** [comment]
+1 I'd be worries that imported programs would be not educational to kids.
Writing e.g. a blog post or making a youtube tutorial about how to redo programs in nepo would be cool though!
