### ISSUE TITLE
Wedo blocks and configuration blocks

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#914]

**Comment by MagicMarvMan** [comment]
@bjost2s I know, that this comment does not fit into this issue, but I don‘t know where I should write it.

A general question: When are you reviewing pull requests and what conditions do they have to meet? It would be cool, if you add a PR template to this repo where you describe that.

Thank you, and sorry again,
MagicMarvMan

**Comment by ensonic** [comment]
@MagicMarvMan we have https://groups.google.com/forum/#!forum/open-roberta as a discussion group and https://gitter.im/open-roberta-lab/Lobby as a chat.
