### ISSUE TITLE
EV3 Functions can't handle "say"-Blocks

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#915]
![grafik](https://user-images.githubusercontent.com/25958792/41356017-21218368-6f23-11e8-9463-c129ff6424bf.png)

This applies for all combinations of "says"-Blocks and functions

**Comment by boonto** [comment]
I just checked: this happens due to the Exceptions thrown by the hal.sayText function, which would normally be caught by the catch all in the run method.
I guess just ignoring the exceptions in the Hal would be possible, retroactively adding throws to userdefined functions does not seem nice.

**Comment by bjost2s** [comment]
I cannot reproduce this error:
![image](https://user-images.githubusercontent.com/1613069/41508345-ae1f0268-7243-11e8-9786-bc077175b37a.png)
Could you please give us more information, please upload the whole program, if possible

**Comment by bjost2s** [comment]
@boonto the error message was coming from the code generation, which has no access to hal at that moment. I cannot reproduce this error on lab.open-roberta.org.

**Comment by boonto** [comment]
@bjost2s the block has to be inside a function block.

**Comment by bjost2s** [comment]
@boonto sorry, now I understand.
