### ISSUE TITLE
Allow users to start the lab with the desired robot system preselected

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#924]
This can be achieved by adding dedicated parameter(s) to the url like we do it for the "create program link", e.g. https://lab.open-roberta.org/#loadProgram&&ev3lejosv1&&...
We could agree on something like https://lab.open-roberta.org/#loadSystem&&ev3lejosv1
Functionallity should be added in [menu.controller.js](https://github.com/OpenRoberta/robertalab/blob/develop/OpenRobertaParent/OpenRobertaServer/staticResources/js/app/roberta/controller/menu.controller.js) 
![image](https://user-images.githubusercontent.com/1613069/41651359-ae153d5c-7480-11e8-9fe3-e1b6e3e0add8.png)
where we handle parameters of the url

**Comment by ensonic** [comment]
url params are usually in the form:
```
https://lab.open-roberta.org/path?key1=value1&key2=value2&...
```
(see https://en.wikipedia.org/wiki/Query_string).

Do we support any parameters right now? Do we have some docs about it (e.g. a wiki page)?

**Comment by bjost2s** [comment]
We dont have a wike page for this, but as you can see in my comment above what we already support.

**Comment by ensonic** [comment]
I'd suggest to do `&` and not `&&` and use `key=value`. E.g. `robotSystem=ev3lejosv1`.

**Comment by alexfh** [comment]
I'd take a look at this.

**Comment by elenadorogush** [comment]
Should this issue be marked as a duplicate of #498?

**Comment by alexfh** [comment]
Probably yes, or the other way round. Thanks for fixing this, btw!
