### ISSUE TITLE
robertalab chrome app is / becomes deprecated soon

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#925]
see [here: robertalab-chromeapp](https://github.com/OpenRoberta/robertalab-chromeapp)

- A new strategy is needed to provide further support for windows, linux and macosx users, if it is possible to support same functionality with an web app.

- It is not clear for us what happens in the near future to chrome apps for chromebooks. Although they are still supported it seems that also this support might become deprecated soon. How can we be prepared for further generations of chromebooks?

**Comment by ensonic** [comment]
One options for chromebook could be an android app.
