### ISSUE TITLE
document translation process

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#936]
* [ ] wiki page describing how to add/update messages and what needs to be done to have the messages show up in the server
* [ ] make sure that all generated files are marked with a comment that tells that they are generated **and** that points to the file that should be edited instead
* [ ] make sure the master file(s) have a comment telling what to run to update the documentation.

**Comment by philippmaurer** [comment]
Created the first iteration of the [translation wiki page](https://github.com/OpenRoberta/robertalab/wiki/Translations). I will discuss with Beate which information should be public (e.g. read access to the translation wiki) and publish the result here for further discussions with you.
