### ISSUE TITLE
button a pressed - and - get pressed button a

### ISSUE THREAD

**Issue by Fr4n2** [OpenRoberta/robertalab#944]
Version 2.7.1
Using a button it is possible to use the block from the sensors library "button A pressed".

But in the precomposed block "wait till button pressed" it is called "get pressed button A". 

Especially working with children this is a bit confusing as there are two different blocks that have the same meaning and are also translated to the same source code. 
I believe the "get pressed button A"-block is a leftover from an older version.

![button_a_pressed](https://user-images.githubusercontent.com/36298448/42082059-4cdd87ca-7b87-11e8-82d3-0aa74905f226.jpg)

**Comment by bjost2s** [comment]
Hi, no, the get pressed button is a complete different block than the button A pressed button. We tried to find a way to combine all sensor blocks in a single dropdown and this is the result. The block only exists in the wait until block.
You could try to show the kids createing their own wait until like 
![image](https://user-images.githubusercontent.com/1613069/42294026-59eab6da-7fde-11e8-9657-f00f2be24c78.png)

**Comment by Fr4n2** [comment]
Hi, 
thank you very much for your answer.

Can you go deeper in explanation where the difference is? Just to understand.
Thank you very much.

![button_a](https://user-images.githubusercontent.com/36298448/42315688-5ac830c2-8048-11e8-82c6-8b812d076abe.jpg)
