### ISSUE TITLE
Block in wrong Category 2 - WeDo

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#948]
The block "Repeat x-time" is in category 2. 
This block belongs to category 1. Please change. 

![image](https://user-images.githubusercontent.com/19221359/42503388-d04657f4-8438-11e8-96f6-c8aef9ed1c93.png)

**Comment by bjost2s** [comment]
Wedo is currently not available in the lab. Please write this kind of issues as comments for still open tickets e.g. #914. Thank you.
btw. The decision where blocks belongs too is highly depending on the target group, we decide to have less blocks in the beginner toolbox for the youngest once than usual.
