### ISSUE TITLE
Remove Calliope 2016 from the start popup to make the chose of Calliope easier

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#950]
because Calliope 2016 is deprecated.
Important: Calliope 2016 will still be available from the menu dropdown, so support in general will be continued.

**Comment by kunkunuzzi** [comment]
There might be included an easy detection of the correct calliope type at program start (wrong selection means, all sensors show 0 including all 3 directions of acceleration, which only will occur during free flight in vacuum, or in space)
