### ISSUE TITLE
Improve data logging for statistics

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#951]
In order to be able to provide general statistics, logging in general should be improved.
A special statistics logger should be included that provides this information.
- [x] errors, with error message
- [x] run program, with login status
- [x] login/logout
- [x] gallery actions
- [x] import/export program
- [x] sim background uploaded
- [x] log browser/system
- [x] include user agent analyzing library
- [x] log screen size
- [x] start session
- <strike>[ ] end session (@boonto I could not find a sensible way)</strike>

The statistics can be used by the server host to see how the lab is used.

<strike>Statistics console logs are structured as follows:
STATISTICS; TIME; SESSIONID; ROBOTNAME; LOGLEVEL; MESSAGE

MESSAGE consists of
ACTION; ARGS..

ARGS are key: value pairs.</strike>

The log entries start with the keyword STATISTICS and are followed by a JSON string. Example (formatted):
```
STATISTICS {
	"time": "2018-07-13 11:09:42,639",
	"sessionId": "1",
	"robotName": "calliope2017",
	"logLevel": "INFO",
	"message": {
		"args": [{
			"LoggedIn": "false"
		}],
		"action": "ProgramRunBack"
	}
}
```

**Comment by boonto** [comment]
@bjost2s @rbudde what do you think about structuring the logs in JSON format?

**Comment by rbudde** [comment]
I prefer JSON over other formats, because:
1. the client generates JSON already
2. the JSON-toString-method does all the necessary quotations of " etc. This is much more complex with other formats (e.g. csv)

**Comment by boonto** [comment]
Okay, I will restructure the logging to JSON.
