### ISSUE TITLE
why are all users created with role=TEACHER?

### ISSUE THREAD

**Issue by ensonic** [OpenRoberta/robertalab#954]
https://github.com/OpenRoberta/robertalab/blob/master/OpenRobertaParent/OpenRobertaServer/src/main/resources/create-tables.sql#L152

The roles are declared here:
https://github.com/OpenRoberta/robertalab/blob/HEAD/OpenRobertaParent/OpenRobertaServer/src/main/java/de/fhg/iais/roberta/persistence/bo/Role.java

but are completely undocumented :/ Happy to turn any replies here nto a PR with a doc comment.

**Comment by bjost2s** [comment]
The roles in the database never have been used, so the default is / was "teacher". The problem is, that we don't see any way to verify this kind of roles. I think we will rename this field, document it and reuse it in the dashboard project, where users could become an admin of a group.
