### ISSUE TITLE
WeDo Blank screen

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#960]
After renaming the motor (m -> mott) and switching back to "Program" the screen is blank.

System: Android 8.1.0,
Browser: Chrome 67.0.3396.87

![wedo_screen](https://user-images.githubusercontent.com/19221359/42927689-87affe7e-8b35-11e8-890c-17eeae5cce1e.jpg)

**Comment by rbudde** [comment]
this seems to be another variant of the annoying problem with Chrome: if view is set to 110% e.g., the width information is delivered wrong by jquery (some other zoom level show the same behavior, others don't). This will hide tabs. If the window is resized (a bit), the tab re-appears.

This issue should be resolved!

**Comment by rbudde** [comment]
working fine now
