### ISSUE TITLE
WeDo blank screen Robot Configuration

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#962]
After changing from "Progam" to "Robot Configuration" the screen was blank. 

![wedo_blank_screen_rc](https://user-images.githubusercontent.com/19221359/42928185-ebb4f662-8b36-11e8-874b-3edf70629cf2.jpg)

Beforehand i switched the ports where the infrared sensor was connected (direktly at the hub)

System: Android 8.1.0
Browser: Chrome 76.0.3396.87
Wedo 2.0

**Comment by rbudde** [comment]
see issue #960 : this seems to be another variant of the annoying problem with Chrome: if view is set to 110% e.g., the width information is delivered wrong by jquery (some other zoom level show the same behavior, others don't). This will hide tabs. If the window is resized (a bit), the tab re-appears.

working now

**Comment by bjost2s** [comment]
some improvement available, please test
