### ISSUE TITLE
Wedo and wifi

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#964]
When I use the app, I am notified that I do not have a WLAN connection. 
Why do I need a WLAN connection?

![wedo_wifi](https://user-images.githubusercontent.com/19221359/43244994-0418d5a4-90ad-11e8-8977-843b316ac2fb.jpg)

**Comment by bjost2s** [comment]
The Open Roberta App has no inbuild robertalab server. If you want to use the app, you have to access either a local server or lab.open-roberta.org.
AFAIK there is currently no other way for Android mobile devices to connect to a network than via a wifi connection. Thats why the wifi connection is required to use this app.
(Internet access is not required but recommended)

**Comment by Thorlogy** [comment]
Sry i do not understand. You mean that Android Apps need WiFi connection to connect with the internet? Or what do you mean with "Network"?
