### ISSUE TITLE
Lab deleted saved Programm

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#966]
I created a programm on Calliope 2017 under the account "roberta_zentrale".
I saved said programm in this account under the name of "JumpAndRunAway".
Then I wanted to test something and went back to the Programm. I removed the main loop from the start block and placed these three blocks instead:
![grafik](https://user-images.githubusercontent.com/25958792/43395633-fea85f5e-93fe-11e8-95c4-bdc8bdbfe903.png)

As soon as I pressed the play button i got a Server Error and my Programm so deleted.
Not only in the workspace but also under "my Programms"

**Comment by bjost2s** [comment]
This is quite hard to reproduce. Could you provide us a minimal example of the workflow which causes this issue?
