### ISSUE TITLE
new leJOS: program execution in menu process

### ISSUE THREAD

**Issue by dpyka** [OpenRoberta/robertalab#97]
To make the program execution more robust, add a finally block to the existing wrapping try catch statement in the NEPO program. Add the following code there
```
hal.closeResources();
```
This calls some addition cleanup, motor stopping etc. to make it more stable for excecution in the same process.

**Comment by cvejoski** [comment]
The close resource method `hal.closeResources();`  is generated by the JavaCodeVisitor
