### ISSUE TITLE
Calliope C++ Code for functions with multiple array arguments aren't created correctly

### ISSUE THREAD

**Issue by kunkunuzzi** [OpenRoberta/robertalab#971]
If a function has more than one array argument, they all use in c++ function declaration the same c++ template constant 'N' for the size, causing a function, which expects the SAME array size for ALL its (array-)arguments.

**Comment by rbudde** [comment]
gelöst durch template param N0

**Comment by rbudde** [comment]
solved by introducing templatae parameter N0 (:-)
