### ISSUE TITLE
Calliope: The test block (ternary operator) does not work correctly inside math blocks

### ISSUE THREAD

**Issue by kunkunuzzi** [OpenRoberta/robertalab#972]
For Calliope, if you use a subtraction block, and in the first argument you put a 'test' block from 'logic' (the ternary operator), the subtraction will only occur in case the 'test' will fail. It seems, some curved brackets are missing in the c++ source code of 'test' .

**Comment by VinArt** [comment]
Merged with 2ce35a52448e76ca57565ec53cdb7671bb8451c4

**Comment by rbudde** [comment]
fix merged by @VinArt. Closed.
