### ISSUE TITLE
Multiple robot simulation : debugging

### ISSUE THREAD

**Issue by akshat-khare** [OpenRoberta/robertalab#981]
### The following tasks were discussed with @bjost2s  and assigned to be done by me regarding multiple simulation feature #976 #977   :
- [x] Debug ultrasonic sensor to make it detect other robots, ultrasonic sensor not detecting other robots but bump feature is working correctly
- [x] The multiple simulation works only on the default field, make it working on other fields too
- [x] Color Values be picked up from the toolbar and random coloring technique should be removed
- [x] Selection of robots be done via color and not numbering
- [x] Set the icon of mult sim option to the main menu simulation option 
- [x] Reduce the number of obstacles from 21 to 1 
- [x] Change the text value of mult sim option to lowercase and other appropriate word
- [x] Multiple Simulation popup heading be enlarged and font style made similar to the project
- [x] Search box be indented properly
- [x] Robot name be removed
- [x] Css of selection list made similar to that tables used in project
- [x] Text of Run Simulation and Close changed to Ok and Cancel and rearranged
- [x] Saved Name be changed to Program name

**Comment by akshat-khare** [comment]
The issues were solved and merged in the multiple_robots_simulation branch #990

**Comment by rbudde** [comment]
the button multiple robot simulation stopped to work. Why?

**Comment by bjost2s** [comment]
Also a lot of unwanted console.log cammands are still in the code

**Comment by akshat-khare** [comment]
I'll look into it, it was working before, some commit after my work may have introduced error. I will remove the extra console.log statements also. It might take some time as I am involved in some other engagement. Thanks

**Comment by bjost2s** [comment]
As we would like to close develop next week I will revise as much as I can do this weekend.
Thank you again for your valuable contribution

**Comment by akshat-khare** [comment]
I compiled code after a long time in my system and I see that the feature is working. The only bug I can see is that when selecting a robot, its code in workspace is not changing. I don't know if that thing is done deliberately or it is a bug that came up during the further change of code. Please clarify @bjost2s .

**Comment by bjost2s** [comment]
I have marked this issue as resolved, because I think we can publish it.
There are still some known issues, e.g. the robot's display is not working reliable (only one div for all) which will be fixed in a next release.

**Comment by akshat-khare** [comment]
Cool, Thanks for the help

**Comment by bjost2s** [comment]
- [ ] Display  and buttons from the robots are still not connected to multiple robots
So we move it to the next release

**Comment by bjost2s** [comment]
- [ ] resetting, refreshing and restarting multiple programs in the simulation needs revision
