### ISSUE TITLE
calliope bluetooth connection fails sometimes (accessed from calliope app)

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#982]
We allready have created new binaries for calliope for bluetooth support. They have been tested on the prod server already and should be integrated in the repo

**Comment by rbudde** [comment]
It was not clear to me, whether this issues is solved. The binaries are new, then changed, later reverted. No clear 'definition of done' is available. We have to have a discussion abourt that issue.

@bjost2s @cvejoski @VinArt

**Comment by bjost2s** [comment]
We tested new binaries with a different configuration. This binaries broke the compiler workflow so that we switched back to the old binaries.
We should open a new issue once we get fixes from calliope
