### ISSUE TITLE
Calliope: setPixelValue-Block works wrong, if the brightness is calculated with the addition-math-block 

### ISSUE THREAD

**Issue by kunkunuzzi** [OpenRoberta/robertalab#983]
It seems, that similiar as issue #972, a curved bracket is missing somewhere. Only the last argument of this block is affected, since it does internally a multiplication with the _SET_BRIGHTNESS_MULTIPLIER constant, which gains precedence by C++-Rules. 
Since there might be more blocks affected, it could malke sense to enclose all the the math blocks in curved brackets.

**Comment by rbudde** [comment]
@kunkunuzzi  you are right, enclosing everything in parentheses would make it right (and not introduce syntax errors). But as many user look at the generated code (and even ask, whether they can upload modified code), we like to keep the code as readable as possible. Readability decreases when brackets are inserted and not needed. Thus: thank you for your report, we'll try to fix the errors step by step :-)

**Comment by rbudde** [comment]
but see #1006 and the same bug in NXT. There is a **general** solution needed.
