### ISSUE TITLE
Simulation: The letter 'w' is not displayed

### ISSUE THREAD

**Issue by Dittse** [OpenRoberta/robertalab#984]
This applies only to the lowercase'w' and also only to the simulation

![grafik](https://user-images.githubusercontent.com/25958792/44651997-133d6700-a9eb-11e8-9c88-337d5e4ec455.png)

**Comment by bjost2s** [comment]
Indeed!
"w" is missing in the letter description ;-)

**Comment by rbudde** [comment]
solved (btw: the "X" is shown like the "H")

**Comment by rbudde** [comment]
no: X is a bit different from H (my mistake :-)
