### ISSUE TITLE
BOB3 connected, but transmission not possible

### ISSUE THREAD

**Issue by springob** [OpenRoberta/robertalab#985]
Bob3 programming not possible: programmer will be connected (ORCA), but whenever I click on play-button, the program can't be transmitted (see attached image)'. Problem started with release 2.8.1...

![lab-open-roberta-bug-20180822](https://user-images.githubusercontent.com/3384098/44790325-5fc9a380-ab9f-11e8-9241-fd7d243e4a7b.png)

**Comment by VinArt** [comment]
Sorry, we are experiencing problems with the Create Agent with our current deployment, they will be gone in a short period of time when the server will be re-deployed, stay tuned.

**Comment by VinArt** [comment]
So with the currently deployed lab I can flash the BOB3, so I will close this. If the problem persists, please let us know.
