### ISSUE TITLE
Bob3/Arduino/etc  bug in randomInteger()

### ISSUE THREAD

**Issue by springob** [OpenRoberta/robertalab#986]
implementation of randomInteger(a,b) is not compatible with pythons random.randint(a, b)
Please increment max by one to get a closed interval! 

Fixed version of OpenRobertaParent/RobotArdu/resources/libraries/RobertaFunctions/RobertaFunctions.cpp:
```
int RobertaFunctions::randomIntegerInRange(int val1, int val2){
        int min = fmin(val1, val2);
        int max = fmax(val1, val2) + 1;
        return min + (rand()%(min - max));
}
```

**Comment by VinArt** [comment]
Thanks for the notice, used your solution.

**Comment by springob** [comment]
Thanks for the fix!
