### ISSUE TITLE
block annotations/errors not distinguishable enough

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#989]
I tested a function with return value and didn't return a value. This is detected and marked with a small X within a circle by the lab. **But: this is likely to be overseen. It should be much more "prominent"**

**Comment by bjost2s** [comment]
@rbudde please test if this solution solves your problem. If not, I can revert it easily. Unfortunately it is not trivial to let the errors and warning instantiated directly from blockly behave in the same way. So now we have a kind of not common behaviour.
