### ISSUE TITLE
no clear design decision w.r.t. to missing values

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#993]
if values are missing (example: Calliope), defaults are used ("" or 0 e.g.). Sometimes NULL is used (raises sometimes warnings from the cross-compiler). The program compiles.

My opinion here is: it should be checked, a (good visible!) error attached to the blocks sent back to the user and the compile should be suppressed. I think, these defaults are especially bad from a didactic point of view.

The semantics of NEPO-programs should be documented in the wiki.

**Comment by VinArt** [comment]
![image](https://user-images.githubusercontent.com/3738015/45154277-4811a100-b1d7-11e8-9790-140fe414b750.png)

This program does not compile, since some values that are left empty produce nothing and not a default value. Variables that are not set are not initialised as well.

**Comment by VinArt** [comment]
![image](https://user-images.githubusercontent.com/3738015/45478562-8ca3bc00-b744-11e8-8315-90750992195e.png)
Default value for connection is missing for the send message block as well as for the receive block:
![image](https://user-images.githubusercontent.com/3738015/45478746-ec9a6280-b744-11e8-8773-a296c2328b58.png)

**Comment by VinArt** [comment]
A possible solution that was discussed in today's meeting: enhance the block checker and when the values for blocks are empty, provide an error (like observed for the "and" block) so users would complete their programs.

It is still unclear what to show in the code pane to the user though.
