### ISSUE TITLE
integration tests (ITs) fail on bamboo

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#996]
at least some Calliope tests (math constants, ...) fail

**Comment by boonto** [comment]
**Definition of Done**
1. Integration tests are running again and the result is readable.
2. Integration tests are extended to cover almost all blocks and robots.

**Comment by rbudde** [comment]
after the refactoringd and after solving the problems with ubuntu 16/18 and their packages for crosscompiler the ITs run again. But more tests are missing.
