### ISSUE TITLE
Microbit code generation uses invalid constant for math.PHI: BlocklyMethods.GOLDEN_RATIO

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#997]
**To Reproduce**
1. Select microbit as robot
2. Add a "show text" block
3. Select advanced toolbox
4. Drag Math/"constant" block into the "show text" block
5. Select phi in the "constant" block
6. Look at the generated code
7. Running the code generates a NotANumber exception on the microbit

**Expected behavior**
 - A proper constant is used.

**Screenshots**
![image](https://user-images.githubusercontent.com/7438960/45219656-ea9b5400-b2ab-11e8-8f7c-3d493e14cf60.png)

**Comment by boonto** [comment]
phi is not contained in math.

**Solution**
 - hard code the value of phi

**Definition of Done**
 - use phi and check the generated code.

**Future improvements**
 - make sure that an integration test with phi exists
 - add a lint tool to the integration test to detect undefined constants
